import { defineConfig, devices } from "@playwright/test";
import { join } from "node:path";
import { tmpdir } from "node:os";

const preview = {
  VERCEL_ENV: "preview",
  VERCEL_GIT_COMMIT_REF: "feature/v17-consolidated-preview",
  VITE_VERCEL_ENV: "preview",
  VITE_VERCEL_GIT_COMMIT_REF: "feature/v17-consolidated-preview",
  VITE_OSI_HUB_MODE: "PREVIEW_REHEARSAL",
  VITE_CRM_PIPELINE_CLIENT_MODE: "PREVIEW_REHEARSAL",
  VITE_CRM_PIPELINE_READ_MODE: "PREVIEW_REHEARSAL",
  VITE_CRM_PIPELINE_CASE_MUTATION_MODE: "PREVIEW_REHEARSAL",
  VITE_V17_COMMERCIAL_CRM_PREVIEW_BATCH: "V17-COMMERCIAL-CRM-PREVIEW-01",
  VITE_CRM_ICP_V2_UI_MODE: "PREVIEW_REHEARSAL",
  VITE_CRM_ICP_V2_UI_BATCH: "V17-ICP-CONSOLIDATION-02A-PREVIEW",
  VITE_CRM_SERVICES_UI_MODE: "PREVIEW_REHEARSAL",
  VITE_CRM_SERVICES_UI_BATCH: "V17-SERVICES-TENANT-FIRST-03A-PREVIEW",
  VITE_CRM_SURVEY_UI_MODE: "PREVIEW_REHEARSAL",
  VITE_CRM_SURVEY_UI_BATCH: "V17-SURVEY-FOUNDATION-04A-PREVIEW",
  VITE_MATERIALS_INVENTORY_UI_MODE: "PREVIEW_REHEARSAL",
  VITE_MATERIALS_INVENTORY_UI_BATCH: "V17-MATERIALS-INVENTORY-05A-PREVIEW",
  VITE_TOOLS_EQUIPMENT_UI_MODE: "PREVIEW_REHEARSAL",
  VITE_TOOLS_EQUIPMENT_UI_BATCH: "V17-TOOLS-EQUIPMENT-06A-PREVIEW",
  VITE_LOGISTICS_ENGINE_UI_MODE: "PREVIEW_REHEARSAL",
  VITE_LOGISTICS_ENGINE_UI_BATCH: "V17-LOGISTICS-ENGINE-07A-PREVIEW",
  VITE_COSTING_UI_MODE: "PREVIEW_REHEARSAL",
  VITE_COSTING_UI_BATCH: "V17-COSTING-08A-PREVIEW",
  VITE_QUOTE_UI_MODE: "PREVIEW_REHEARSAL",
  VITE_QUOTE_UI_BATCH: "V17-QUOTE-09A-PREVIEW",
  VITE_MT01B2_CLIENT_ENABLED: "false",
  VITE_ADMIN_TENANT_MEMBERSHIP_MODE: "DISABLED",
  VITE_ADMIN_IDENTITY_INVITATION_MODE: "DISABLED",
};

export default defineConfig({
  testDir: "./tests/v17-consolidated-preview",
  outputDir: join(tmpdir(), `v17-consolidated-preview-${process.pid}`),
  timeout: 60_000,
  globalTimeout: 15 * 60_000,
  expect: { timeout: 10_000 },
  workers: 1,
  retries: 0,
  forbidOnly: true,
  reporter: "list",
  use: { baseURL: "http://preview.localhost:4202", trace: "retain-on-failure", screenshot: "only-on-failure", video: "off", serviceWorkers: "block" },
  webServer: { command: "npm run dev -- --host 0.0.0.0 --port 4202", url: "http://127.0.0.1:4202/", reuseExistingServer: false, timeout: 120_000, env: { ...preview, VITE_API_PROXY: "http://127.0.0.1:59999" } },
  projects: [
    { name: "chromium-desktop", use: { ...devices["Desktop Chrome"] } },
    { name: "firefox-desktop", use: { ...devices["Desktop Firefox"] } },
    { name: "webkit-desktop", use: { ...devices["Desktop Safari"] } },
    { name: "chromium-mobile", use: { ...devices["Pixel 7"] } },
    { name: "firefox-mobile", use: { ...devices["Desktop Firefox"], viewport: { width: 390, height: 844 } } },
    { name: "webkit-mobile", use: { ...devices["iPhone 13"] } },
  ],
});
