export type CommunicationVariable = Readonly<{ name: string; source: string; type: string; pii: boolean; contexts: readonly string[]; fallback: string }>;
export type CommunicationVersion = Readonly<{ versionRef: string; version: number; state: "DRAFT" | "PUBLISHED" | "INACTIVE"; audiences: readonly string[]; channels: readonly string[]; subject: string | null; bodyText: string; bodyHtml: string | null; variables: { catalogVersion: number; names: readonly string[] } | readonly string[]; contentSha256: string; validFrom: string | null; validTo: string | null; createdAt: string; publishedAt: string | null }>;
export type CommunicationTemplate = Readonly<{ templateRef: string; code: string; name: string; category: string; state: string; currentVersion: number; current: CommunicationVersion | null; versions: readonly CommunicationVersion[]; updatedAt: string }>;
export type CommunicationRecord = Readonly<{ communicationRef: string; templateRef: string; templateCode: string; templateVersion: number; milestone: string; channel: string; recipientType: string; recipient: { displayName: string; destination: string | null }; subject: string | null; bodyText: string; bodyHtml: string | null; status: string; preparedAt: string; sentAt?: string | null; deliveredAt?: string | null; failedAt?: string | null }>;
export type CommunicationRecipient = Readonly<{ recipientType: string; recipientRef: string; displayName: string; email: string | null; phone: string | null; availableChannels: readonly string[] }>;
function headers(authorization?: string) { return { "Content-Type": "application/json", ...(authorization ? { Authorization: authorization } : {}) }; }
async function request<T>(authorization: string | undefined, path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, { ...init, headers: { ...headers(authorization), ...(init?.headers || {}) }, credentials: "omit", cache: "no-store" }); const json = await response.json().catch(() => null); if (!response.ok || !json?.ok) throw new Error(json?.error || "COMMUNICATION_REQUEST_FAILED"); return json.data as T; }
function canonical(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value as object).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`; return JSON.stringify(value); }
async function sha256(value: unknown) { const bytes = new TextEncoder().encode(canonical(value)); const digest = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function command<T>(authorization: string | undefined, path: string, operation: string, payload: Record<string, unknown>, method = "POST", hashPayload: Record<string, unknown> = payload) { const requestId = crypto.randomUUID(); const payloadHash = await sha256({ operation, requestId, ...hashPayload }); return request<T>(authorization, path, { method, body: JSON.stringify({ requestId, payloadHash, ...payload }) }); }
export const communicationsApi = Object.freeze({
  templates: (authorization?: string) => request<readonly CommunicationTemplate[]>(authorization, "/api/communications/templates"),
  variables: (authorization?: string) => request<{ catalogVersion: number; variables: readonly CommunicationVariable[] }>(authorization, "/api/communications/variables"),
  create: (authorization: string | undefined, payload: Record<string, unknown>) => command<CommunicationTemplate>(authorization, "/api/communications/templates", "TEMPLATE_CREATE", payload),
  createVersion: (authorization: string | undefined, templateRef: string, payload: Record<string, unknown>) => command<CommunicationTemplate>(authorization, `/api/communications/templates/${encodeURIComponent(templateRef)}/versions`, "TEMPLATE_VERSION", payload, "POST", { templateRef, ...payload }),
  updateDraft: (authorization: string | undefined, templateRef: string, payload: Record<string, unknown>) => command<CommunicationTemplate>(authorization, `/api/communications/templates/${encodeURIComponent(templateRef)}/versions`, "TEMPLATE_DRAFT_UPDATE", payload, "PATCH", { templateRef, ...payload }),
  publish: (authorization: string | undefined, templateRef: string, version: number) => command<{ templateRef: string; version: number; state: string }>(authorization, `/api/communications/templates/${encodeURIComponent(templateRef)}/publish`, "TEMPLATE_PUBLISH", { version, expectedState: "DRAFT" }, "POST", { templateRef, version, expectedState: "DRAFT" }),
  inactivate: (authorization: string | undefined, templateRef: string, expectedVersion: number) => command<{ templateRef: string; version: number; state: string }>(authorization, `/api/communications/templates/${encodeURIComponent(templateRef)}/inactivate`, "TEMPLATE_INACTIVATE", { expectedVersion }, "POST", { templateRef, expectedVersion }),
  preview: (authorization: string | undefined, payload: Record<string, unknown>) => request<{ context: "SYNTHETIC"; rendered: { subject: string | null; bodyText: string; bodyHtml: string | null } }>(authorization, "/api/communications/preview", { method: "POST", body: JSON.stringify(payload) }),
  records: (authorization: string | undefined, caseRef: string) => request<readonly CommunicationRecord[]>(authorization, `/api/communications/records?caseRef=${encodeURIComponent(caseRef)}`),
  recipients: (authorization: string | undefined, payload: Record<string, unknown>) => request<readonly CommunicationRecipient[]>(authorization, "/api/communications/recipients", { method: "POST", body: JSON.stringify(payload) }),
  prepare: (authorization: string | undefined, payload: Record<string, unknown>) => command<CommunicationRecord>(authorization, "/api/communications/prepare", "COMMUNICATION_PREPARE", payload),
});
