import { useCallback, useEffect, useMemo, useState } from "react";
import { MessageSquareText, Plus, ShieldCheck } from "lucide-react";
import { communicationsApi, type CommunicationRecipient, type CommunicationRecord, type CommunicationTemplate } from "./api";
import type { CommunicationsAccess } from "./access";

type Props = Readonly<{ caseRef: string; authorization?: string; access: CommunicationsAccess; context: "CASE" | "SCHEDULING" | "QUOTE"; surveyAssignmentRef?: string | null; quoteRevisionRef?: string | null; onUnauthorized(): void }>;
const MILESTONES: Record<Props["context"], readonly string[]> = { CASE: ["CLIENT_INFORMATION_REQUEST", "DOCUMENT_REQUEST", "BOOKER_NOTIFICATION", "AGENT_NOTIFICATION", "LEAD_ACCOUNT_NOTIFICATION"], SCHEDULING: ["VISIT_CONFIRMATION", "EVALUATOR_ASSIGNMENT", "SURVEY_PIC_CLIENT", "SURVEY_PIC_EVALUATOR", "VISIT_RESCHEDULED", "VISIT_CANCELLED"], QUOTE: ["QUOTE_SENT", "FOLLOW_UP_1", "FOLLOW_UP_2", "EXPIRY_REMINDER", "QUOTE_ACCEPTED", "QUOTE_REJECTED"] };
function date(value: string) { return new Intl.DateTimeFormat("es-DO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
export default function CommunicationPanel({ caseRef, authorization, access, context, surveyAssignmentRef = null, quoteRevisionRef = null, onUnauthorized }: Props) {
  const [records, setRecords] = useState<readonly CommunicationRecord[]>([]); const [templates, setTemplates] = useState<readonly CommunicationTemplate[]>([]); const [recipients, setRecipients] = useState<readonly CommunicationRecipient[]>([]); const [open, setOpen] = useState(false); const [templateRef, setTemplateRef] = useState(""); const [recipientRef, setRecipientRef] = useState(""); const [channel, setChannel] = useState(""); const [milestone, setMilestone] = useState(MILESTONES[context][0]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const values = await Promise.all([access.canView ? communicationsApi.records(authorization, caseRef) : Promise.resolve([]), access.canPrepare ? communicationsApi.templates(authorization) : Promise.resolve([])]); setRecords(values[0]); setTemplates(values[1].filter((item) => item.state === "PUBLISHED")); } catch (cause) { const code = cause instanceof Error ? cause.message : "COMMUNICATION_REQUEST_FAILED"; if (/AUTH/.test(code)) onUnauthorized(); else setError(code); } }, [access.canPrepare, access.canView, authorization, caseRef, onUnauthorized]);
  useEffect(() => { void load(); }, [load]);
  const selectedTemplate = useMemo(() => templates.find((item) => item.templateRef === templateRef) || null, [templateRef, templates]);
  const selectTemplate = async (ref: string) => { setTemplateRef(ref); setRecipientRef(""); setChannel(""); const template = templates.find((item) => item.templateRef === ref); const audience = template?.current?.audiences[0]; if (!audience) { setRecipients([]); return; } try { const rows = await communicationsApi.recipients(authorization, { caseRef, audience, surveyAssignmentRef, quoteRevisionRef }); setRecipients(rows); } catch (cause) { setError(cause instanceof Error ? cause.message : "COMMUNICATION_RECIPIENTS_UNAVAILABLE"); } };
  const prepare = async () => { const template = selectedTemplate; const recipient = recipients.find((item) => item.recipientRef === recipientRef); if (!template?.current || !recipient || !channel) return; setBusy(true); setError(null); try { await communicationsApi.prepare(authorization, { templateRef: template.templateRef, version: template.current.version, caseRef, surveyAssignmentRef, quoteRevisionRef, recipientType: recipient.recipientType, recipientRef, channel, milestone }); setOpen(false); setTemplateRef(""); setRecipientRef(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "COMMUNICATION_PREPARE_FAILED"); } finally { setBusy(false); } };
  if (!access.canView && !access.canPrepare) return null;
  return <section className="mt-4 border border-slate-200 bg-white" data-testid={`communications-${context.toLowerCase()}`}><header className="flex flex-wrap items-center justify-between gap-2 border-b bg-slate-50 px-3 py-2"><div><h3 className="text-xs font-black uppercase tracking-wide text-[#003366]"><MessageSquareText className="mr-1 inline h-4 w-4" />Comunicaciones</h3><p className="text-[10px] text-slate-500">Registro inmutable · transporte externo desactivado</p></div>{access.canPrepare && <button type="button" onClick={() => setOpen((value) => !value)} className="rounded border bg-white px-2 py-1 text-xs font-bold"><Plus className="mr-1 inline h-3 w-3" />Preparar</button>}</header>{error && <p role="alert" className="border-b bg-red-50 px-3 py-2 text-xs text-red-800">No fue posible completar la operación.</p>}
    {open && <div className="grid gap-2 border-b bg-indigo-50/40 p-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-[10px] font-bold uppercase">Plantilla<select value={templateRef} onChange={(event) => void selectTemplate(event.target.value)} className="mt-1 h-9 w-full rounded border bg-white px-2 text-xs"><option value="">Seleccionar…</option>{templates.map((item) => <option key={item.templateRef} value={item.templateRef}>{item.code} · {item.name}</option>)}</select></label><label className="text-[10px] font-bold uppercase">Destinatario<select value={recipientRef} onChange={(event) => { const value = event.target.value; setRecipientRef(value); const row = recipients.find((item) => item.recipientRef === value); setChannel(row?.availableChannels[0] || ""); }} className="mt-1 h-9 w-full rounded border bg-white px-2 text-xs"><option value="">Seleccionar explícitamente…</option>{recipients.map((item) => <option key={item.recipientRef} value={item.recipientRef}>{item.displayName} · {item.email || item.phone || "sin canal"}</option>)}</select></label><label className="text-[10px] font-bold uppercase">Canal<select value={channel} onChange={(event) => setChannel(event.target.value)} className="mt-1 h-9 w-full rounded border bg-white px-2 text-xs"><option value="">Seleccionar…</option>{recipients.find((item) => item.recipientRef === recipientRef)?.availableChannels.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-[10px] font-bold uppercase">Hito<select value={milestone} onChange={(event) => setMilestone(event.target.value)} className="mt-1 h-9 w-full rounded border bg-white px-2 text-xs">{MILESTONES[context].map((item) => <option key={item}>{item}</option>)}</select></label><div className="sm:col-span-2 lg:col-span-4 flex items-center justify-between"><p className="text-[10px] text-slate-600"><ShieldCheck className="mr-1 inline h-3 w-3" />El servidor renderiza y guarda el snapshot. No se enviará.</p><button type="button" disabled={busy || !templateRef || !recipientRef || !channel} onClick={() => void prepare()} className="rounded bg-[#003366] px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{busy ? "Preparando…" : "Guardar como PREPARED"}</button></div></div>}
    <div className="divide-y">{records.map((item) => <article key={item.communicationRef} className="grid gap-1 px-3 py-2 text-xs sm:grid-cols-[140px_1fr_auto]"><div><strong>{item.status}</strong><br /><span className="text-[10px] text-slate-500">{date(item.preparedAt)}</span></div><div><p className="font-semibold">{item.templateCode} · {item.recipient.displayName}</p><p className="line-clamp-2 text-slate-600">{item.subject || item.bodyText}</p></div><span className="self-start rounded bg-slate-100 px-2 py-1 text-[10px] font-bold">{item.channel}</span></article>)}{records.length === 0 && <p className="p-4 text-center text-xs text-slate-500">Sin comunicaciones canónicas registradas.</p>}</div>
  </section>;
}
