import { expect, test, type Page } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { resolve } from "node:path";

const CASE_REF = "038f6d8f-8d11-4f39-8a2d-1b6c7e8f9012";
const MEMBERSHIP_REF = "048f6d8f-8d11-4f39-8a2d-1b6c7e8f9012";
const CLIENT_REF = "058f6d8f-8d11-4f39-8a2d-1b6c7e8f9012";
const PRIMARY_REF = "068f6d8f-8d11-4f39-8a2d-1b6c7e8f9012";
const COSTING_REF = "078f6d8f-8d11-4f39-8a2d-1b6c7e8f9012";
const privateHeaders = { "Cache-Control": "private, no-store", Vary: "Authorization, Origin" };
const permissions = [
  "pipeline:view", "pipeline:create", "pipeline:update:any", "pipeline:destination-pending:create",
  "services:case:view", "services:case:update", "survey:assignment:view", "survey:perform", "survey:publish", "survey:read",
  "survey:schedule:view", "survey:schedule:manage", "survey:schedule:assign", "survey:schedule:reschedule", "survey:visit-fee:view", "survey:visit-fee:approve",
  "inventory:catalog:view", "inventory:stock:view", "assets:instance:view",
  "logistics:plan:view", "logistics:plan:calculate", "logistics:plan:publish", "costing:view", "costing:calculate", "costing:publish",
  "quote:view", "quote:create", "quote:update", "quote:publish", "quote:send", "quote:record-client-decision", "quote:internal-cost:view",
  "commercial:relationships:view", "commercial:relationships:manage", "commercial:tariffs:view", "commercial:tariffs:manage",
  "commercial:referrals:view", "commercial:referrals:manage", "commercial:commissions:view", "commercial:commissions:manage",
  "commercial:associations:view", "commercial:associations:manage",
];

const crmDetail = { caseRef: CASE_REF, caseCode: "CS-2026-1004", version: 4, status: "QUOTE_SENT", mode: "EXPORT", serviceType: "INTERNATIONAL_MOVE", customerType: "CORPORATE", estimatedCbm: 18.4, requiresSurvey: true, surveyMethod: "PRESENCIAL", originLocation: "Santo Domingo", destinationLocation: "Madrid", destinationContracted: true, assetsCount: 0, quoteCount: 3, eventCount: 8, client: { clientRef: CLIENT_REF, displayName: "Cliente Preview Exportación", type: "ORGANIZATION", status: "ACTIVE" }, owner: { displayName: "Ventas Preview", isCurrentActor: true }, createdAt: "2026-09-05T12:00:00.000Z", updatedAt: "2026-09-05T13:00:00.000Z" };
const syntheticCases = [
  { ...crmDetail, caseRef: "018f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", caseCode: "CS-2026-1001", mode: "LOCAL", serviceType: "LOCAL_MOVE", requiresSurvey: false, quoteCount: 0, client: { ...crmDetail.client, displayName: "Cliente Preview Local" } },
  { ...crmDetail, caseRef: "028f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", caseCode: "CS-2026-1002", status: "SURVEY_COMPLETED", quoteCount: 0, client: { ...crmDetail.client, displayName: "Cliente Preview Survey y Crating" } },
  { ...crmDetail, caseRef: "048f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", caseCode: "CS-2026-1003", status: "PRICING_IN_PROGRESS", mode: "IMPORT", quoteCount: 0, client: { ...crmDetail.client, displayName: "Cliente Preview Proveedor pendiente" } },
  crmDetail,
];
const icpDetail = { caseRef: CASE_REF, caseCode: "CS-2026-1004", status: "QUOTE_SENT", version: 4, mode: "EXPORT", serviceType: "INTERNATIONAL_MOVE", volume: { status: "PUBLISHED_SURVEY", estimatedCbm: 18.4, source: "SURVEY" }, requiresSurvey: true, surveyMethod: "PRESENCIAL", intakeChannel: "REFERRED", clientProfileType: "CORPORATE", requirementNotes: "Exportación sintética con Crating", serviceDefinitionStatus: "DEFINED", surveyDecisionStatus: "DEFINED", ownerName: "Ventas Preview", caseContact: { displayName: "Contacto Preview", phone: "+18095550100", email: "contacto@example.invalid" }, client: { clientRef: CLIENT_REF, displayName: "Cliente Preview Exportación", type: "ORGANIZATION", status: "ACTIVE" }, route: { contractVersion: 2, revision: 1, destinationStatus: "CONFIRMED", origin: { countryCode: "DO", provinceState: "Distrito Nacional", cityMunicipality: "Santo Domingo", sector: "Piantini", streetAndNumber: "Origen sintético", buildingResidential: null, floorUnit: null, arrivalReference: null, locationContactName: null, locationContactPhone: null }, destination: { countryCode: "ES", provinceState: "Madrid", cityMunicipality: "Madrid", sector: null, streetAndNumber: "Destino sintético", buildingResidential: null, floorUnit: null, arrivalReference: null, locationContactName: null, locationContactPhone: null }, additionalStops: [] }, createdAt: "2026-09-05T12:00:00.000Z", updatedAt: "2026-09-05T13:00:00.000Z" };
const serviceWorkspace = { caseRef: CASE_REF, mode: "EXPORT", selection: { selectionRef: "138f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", revision: 2, mode: "EXPORT", source: "MANUAL", defaultCombinationRef: null, primary: { serviceRef: PRIMARY_REF, code: "EXPORT_MOVE", name: "Mudanza internacional", category: "Mudanzas", catalogVersion: 1, source: "CATALOG" }, complementaries: [{ serviceRef: "168f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", code: "CRATING", name: "Crating", category: "Empaque", catalogVersion: 1, source: "CATALOG" }], otherServices: [], historyCount: 2 }, primaries: [], allowedComplementaries: [], defaults: [] };
const surveyAssignment = { assignmentRef: "238f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", caseRef: CASE_REF, caseCode: "CS-2026-1004", clientDisplayName: "Cliente Preview Exportación", evaluator: { displayName: "Evaluador Preview" }, scheduledStart: "2026-09-05T12:00:00.000Z", scheduledEnd: null, status: "COMPLETED", arrivalAt: "2026-09-05T12:00:00.000Z", punctualityConfirmedAt: "2026-09-05T12:01:00.000Z", context: { origin: "Santo Domingo", destination: "Madrid", services: [{ name: "Mudanza internacional" }] }, instruction: null, version: 5, surveyRef: "248f6d8f-8d11-4f39-8a2d-1b6c7e8f9012" };
const schedulingWorkspace = { caseRef: CASE_REF, caseCode: "CS-2026-1004", routeVersion: 2, decision: { decisionRef: "218f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", method: "IN_PERSON", state: "COMPLETED", informationSource: "EVALUATOR", rationaleCode: "PREVIEW_SYNTHETIC", routeVersion: 2, version: 1, createdAt: "2026-09-05T11:00:00.000Z" }, assignment: { assignmentRef: surveyAssignment.assignmentRef, scheduledStart: surveyAssignment.scheduledStart, scheduledEnd: null, evaluator: surveyAssignment.evaluator, slotKey: "AFTERNOON", profile: "INTERIOR_SHORT", zoneCode: "PREVIEW", status: "COMPLETED", version: 5, instruction: null, routeStale: false, surveyRef: surveyAssignment.surveyRef }, policy: null, schedulingContext: { profile: "INTERIOR_SHORT", zoneCode: "PREVIEW", distanceStatus: "KNOWN", distanceKm: 18.5 }, availability: null, evaluatorCandidates: [], visitFee: null, communications: [], history: [], publication: { publicationRef: "228f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", publishedAt: "2026-09-05T13:00:00.000Z", evaluatorDisplayName: "Evaluador Preview", totals: { totalVolumeM3: 18.4 }, needs: { flaggedItems: 1 }, access: [] } };
const logistics = { planRef: "338f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", revisionRef: "348f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", revision: 2, status: "PUBLISHED", logicalSha256: "a".repeat(64), publishedAt: "2026-09-05T14:00:00.000Z", items: [{ itemRef: "358f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", family: "ZONE", kind: "VISIT_ZONE", label: "Zona de visita", quantity: null, unit: null, estimatedHours: null, trips: null, requiredQuantity: null, availableQuantity: null, reservedQuantity: null, shortageQuantity: null, availability: null, priceStatus: null, source: "ADMIN_RULE", sourceVersion: 1, snapshot: { zoneType: "INTERIOR_SHORT", zoneCode: "PREVIEW" } }, { itemRef: "368f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", family: "MATERIAL", kind: "PACKING", label: "Material de empaque derivado", quantity: 12, unit: "unidad", estimatedHours: null, trips: null, requiredQuantity: 12, availableQuantity: 8, reservedQuantity: 0, shortageQuantity: 4, availability: "PARTIAL", priceStatus: "CONFIRMED", source: "RECIPE", sourceVersion: 1 }], issues: [], overrides: [] };
const costing = { revisionRef: COSTING_REF, revision: 1, status: "PUBLISHED", baseCurrency: "USD", logicalSha256: "b".repeat(64), publishedAt: "2026-09-05T15:00:00.000Z", totals: { ownCosts: "300", externalCosts: "200", disbursements: "50", risks: "0", currencyCompensation: "0", totalCost: "550", suggestedPrice: "750", expectedMarginBps: 2667 }, lines: [], issues: [], overrides: [] };
const commercialContext = { commercialContextRef: "638f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", seriesRef: "648f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", version: 2, commercialRelationshipRef: null, payerRef: "658f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", pricingAgreementRef: "668f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", referralAgreementRef: "678f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", agreement: { pricingAgreementRef: "668f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", version: 1, validFrom: "2026-01-01T00:00:00.000Z", validTo: null, tariff: { tariffRef: "688f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", code: "CORP-USD", name: "Tarifario corporativo", version: 1, currency: "USD" }, adjustments: [{ adjustmentRef: "698f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", kind: "DISCOUNT", calculationType: "PERCENTAGE", value: 8, base: "SERVICE_TOTAL", reasonCode: "CORPORATE", authorized: true, validFrom: null, validTo: null }] }, referral: { referralAgreementRef: "678f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", version: 1, calculationType: "PERCENTAGE", value: 3, currency: "USD", reference: "Referido Preview", validFrom: null, validTo: null }, parties: [{ role: "COMPANY", entityRef: "718f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", relationshipRef: null, displayName: "Empresa Preview", kind: "COMPANY", validFrom: null, validTo: null, contacts: [] }, { role: "LEAD_ACCOUNT", entityRef: "728f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", relationshipRef: null, displayName: "Lead Account Preview", kind: "LEAD_ACCOUNT", validFrom: "2026-01-01T00:00:00.000Z", validTo: null, contacts: [{ contactRef: "738f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", displayName: "Contacto Lead Preview", position: "Coordinación", preferredChannel: "EMAIL" }] }, { role: "BOOKER", entityRef: "748f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", relationshipRef: null, displayName: "Booker Preview", kind: "PERSON", validFrom: null, validTo: null, contacts: [{ contactRef: "758f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", displayName: "Booker Preview", position: "Booker", preferredChannel: "PHONE" }] }, { role: "PAYER", entityRef: "658f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", relationshipRef: null, displayName: "Pagador Preview", kind: "COMPANY", validFrom: null, validTo: null, contacts: [] }, { role: "APPROVER", entityRef: "768f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", relationshipRef: null, displayName: "Aprobador actual distinto", kind: "PERSON", validFrom: null, validTo: null, contacts: [] }], associations: [{ membershipRef: "778f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", associationName: "Asociación Preview", membershipNumber: "SYNTH-001", validFrom: null, validTo: null }], instructions: [{ instructionRef: "788f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", category: "COMMERCIAL", priority: 10, content: { text: "Copiar al Booker en comunicaciones." } }], logicalSha256: "d".repeat(64) };
const proposals = [1, 2, 3].map((position) => ({ proposalRef: `${position}58f6d8f-8d11-4f39-8a2d-1b6c7e8f9012`, reference: `Q-2026-00000${position}`, position, state: position === 2 ? "ACCEPTED" : "SENT", revisionRef: `${position}68f6d8f-8d11-4f39-8a2d-1b6c7e8f9012`, revision: 2, proposalName: `Propuesta ${position}`, costingRevisionRef: COSTING_REF, currency: "USD", issueDate: "2026-09-05", validUntil: "2026-10-05", totals: { totalQuotedPrice: 800 + position * 50 }, lines: [], issues: [], logicalSha256: "c".repeat(64), commercialContext: { company: null, leadAccount: { displayName: "Lead Account histórico", reference: "opaque", kind: "LEAD_ACCOUNT", version: 1, validFrom: null, validUntil: null, conditions: null }, booker: { displayName: "Booker histórico", reference: "opaque", kind: "BOOKER", version: 1, validFrom: null, validUntil: null, conditions: null }, tariff: { displayName: "Tarifario histórico", reference: "opaque", kind: "PRICING_AGREEMENT", version: 1, validFrom: null, validUntil: null, conditions: null }, associations: ["Asociación histórica"], referral: { displayName: "Referido histórico", reference: "opaque", kind: "REFERRAL_AGREEMENT", version: 1, validFrom: null, validUntil: null, conditions: null }, commissionContext: null }, payer: { displayName: "Pagador histórico", reference: "opaque", kind: "COMPANY", sourceVersion: 1, validFrom: null, validUntil: null, conditions: null } }));

async function authorize(page: Page, deny = false) {
  await page.addInitScript(({ ref }) => { localStorage.setItem("osi-plus.token", "synthetic.consolidated.token"); localStorage.setItem("osi-plus.session", JSON.stringify({ name: "Administrador Preview", role: "A", membershipRef: ref, memberships: [{ membershipRef: ref, tenantName: "Tenant Preview aislado", role: "A", preferred: true }] })); }, { ref: MEMBERSHIP_REF });
  await page.route("**/api/auth/me", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, user: { name: "Administrador Preview", role: "A", status: "ACTIVE", permissions, deniedPermissions: deny ? ["pipeline:view"] : [], commercialCrmPreviewAuthorized: true, membership: { membershipRef: MEMBERSHIP_REF, tenantName: "Tenant Preview aislado", role: "A" }, memberships: [{ membershipRef: MEMBERSHIP_REF, tenantName: "Tenant Preview aislado", role: "A", preferred: true }] } }) }));
}

async function mockDomains(page: Page) {
  const byStatus = Object.fromEntries(["NEW_INBOX", "AWAITING_ICP", "GOVERNANCE_CONFIRMED", "REQUIREMENTS_CONFIRMED", "SURVEY_PLANNING", "SURVEY_SCHEDULED", "SURVEY_COMPLETED", "CRATING_ESTIMATE_PENDING", "PRICING_IN_PROGRESS", "QUOTE_DRAFT", "INTERNAL_REVIEW", "QUOTE_SENT", "NEGOTIATION", "WON", "LOST", "CHANGE_CONTROL", "APPROVED", "OPS_HANDOFF"].map((status) => [status, status === "QUOTE_SENT" ? 4 : 0]));
  await page.route("**/api/crm/pipeline-summary", (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: { total: 4, assigned: 4, unassigned: 0, byStatus, sla: { overdue: null, basis: "UNAVAILABLE" } } }) }));
  await page.route(/\/api\/crm\/pipeline-cases(?:\?.*)?$/, (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: syntheticCases, total: 4, page: 1, pageSize: 25 }) }));
  await page.route(`**/api/crm/pipeline-cases/${CASE_REF}`, (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: crmDetail }) }));
  await page.route(`**/api/crm/icp-v2/pipeline-cases/${CASE_REF}`, (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: icpDetail }) }));
  await page.route(`**/api/crm/services/cases/${CASE_REF}`, (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: serviceWorkspace }) }));
  await page.route("**/api/crm/survey/assignments", (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: [surveyAssignment] }) }));
  await page.route("**/api/crm/survey/scheduling?*", (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: schedulingWorkspace }) }));
  await page.route(`**/api/logistics/plans/${CASE_REF}`, (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: logistics }) }));
  await page.route(`**/api/costing/revisions/${CASE_REF}`, (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: costing }) }));
  await page.route(`**/api/quote/cases/${CASE_REF}`, (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: { caseRef: CASE_REF, caseCode: "CS-2026-1004", destinationStatus: "CONFIRMED", proposals } }) }));
  await page.route("**/api/commercial-relationships/entities?*", (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: { page: 1, pageSize: 20, total: commercialContext.parties.length, items: commercialContext.parties.map((party, index) => ({ entityRef: party.entityRef, code: `ENTITY-${index + 1}`, displayName: party.displayName, legalName: null, kind: party.kind, countryCode: "DO", status: "ACTIVE", validFrom: party.validFrom, validTo: party.validTo, version: 1, client: null, contacts: party.contacts })) } }) }));
  await page.route("**/api/commercial-relationships/relationships", (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: [] }) }));
  await page.route("**/api/commercial-relationships/workspace", (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: { tariffs: [{ tariffRef: commercialContext.agreement.tariff.tariffRef, code: "CORP-USD", name: "Tarifario corporativo", version: 1, currency: "USD", validFrom: null, validTo: null }], pricingAgreements: [{ pricingAgreementRef: commercialContext.pricingAgreementRef, tariffCode: "CORP-USD", version: 1, validFrom: null, validTo: null }], referrals: [{ referralAgreementRef: commercialContext.referralAgreementRef, reference: "Referido Preview", version: 1, validFrom: null, validTo: null }], commissions: [{ commissionAgreementRef: "798f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", kind: "INTERNAL", version: 1 }], associations: [{ membershipRef: "778f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", association: { displayName: "Asociación Preview" }, version: 1 }], certifications: [{ certificationRef: "7a8f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", type: "CERTIFICACIÓN PREVIEW", status: "ACTIVE", expiresAt: null }] } }) }));
  await page.route(`**/api/commercial-relationships/cases/${CASE_REF}`, (route) => route.fulfill({ status: 200, contentType: "application/json", headers: privateHeaders, body: JSON.stringify({ ok: true, data: commercialContext }) }));
}

test("recorre el caso desde ICP hasta Cotización en una sola Ficha", async ({ page }, testInfo) => {
  await authorize(page); await mockDomains(page); await page.goto(`/commercial/cases/${CASE_REF}`);
  const tabs = page.getByRole("tab"); await expect(tabs).toHaveCount(6); expect(await tabs.allTextContents()).toEqual(["Resumen", "Relaciones", "Servicios", "Evaluación", "Costos", "Cotización"]);
  await expect(page.getByTestId("case-workflow-progress")).toContainText("ICP"); await expect(page.getByTestId("ready-for-operations")).toBeVisible();
  const evidence = resolve(process.cwd(), ".artifacts", "v17-consolidated-preview-10a");
  if (testInfo.project.name === "chromium-desktop" || testInfo.project.name === "chromium-mobile") { mkdirSync(evidence, { recursive: true }); await page.screenshot({ path: resolve(evidence, `summary-${testInfo.project.name}.png`), fullPage: true }); }
  await page.getByRole("tab", { name: "Relaciones" }).click(); await expect(page.getByText("Responsable del pago")).toBeVisible(); await expect(page.getByText("Pagador Preview")).toBeVisible();
  await page.getByRole("tab", { name: "Servicios" }).click(); await expect(page.getByTestId("case-services-panel")).toBeVisible();
  await page.getByRole("tab", { name: "Evaluación" }).click(); await expect(page.getByTestId("survey-scheduling-workspace")).toContainText("Publicado"); await expect(page.getByTestId("scheduling-commercial-context")).toContainText("Booker Preview"); await expect(page.getByTestId("logistics-visit-summary")).toContainText("18.5 km"); await expect(page.getByTestId("logistics-visit-summary")).toContainText("Lead Account Preview");
  await expect(page.getByRole("tab", { name: "Motor Logístico" })).toHaveCount(0);
  await page.getByRole("tab", { name: "Costos" }).click(); await expect(page.getByTestId("costing-panel")).toBeVisible();
  await page.getByRole("tab", { name: "Cotización" }).click(); await expect(page.getByTestId("quote-ready-for-operations")).toBeVisible(); await expect(page.getByTestId("quote-commercial-snapshot")).toContainText("Pagador histórico"); await expect(page.getByTestId("quote-commercial-snapshot")).not.toContainText("Aprobador actual distinto"); await expect(page.getByRole("button", { name: "Registrar aceptación" })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
  if (testInfo.project.name === "chromium-desktop" || testInfo.project.name === "chromium-mobile") await page.screenshot({ path: resolve(evidence, `quote-${testInfo.project.name}.png`), fullPage: true });
});

test("deny detiene el flujo antes de chunks y APIs protegidas", async ({ page }) => {
  await authorize(page, true); let domainRequests = 0; page.on("request", (request) => { if (/^\/api\/(crm|logistics|costing|quote)/.test(new URL(request.url()).pathname) && !new URL(request.url()).pathname.endsWith("/auth/me")) domainRequests += 1; });
  await page.goto(`/commercial/cases/${CASE_REF}`); await expect(page.getByTestId("hub-forbidden")).toContainText("403"); expect(domainRequests).toBe(0);
  const chunks = await page.evaluate(() => performance.getEntriesByType("resource").map((entry) => entry.name).filter((name) => /AdvancedErpShell|CommercialCaseDetail|SurveyCasePanel|QuotePanel|CommercialRelationshipsAdmin|CaseCommercialContextPanel/.test(name)));
  expect(chunks).toHaveLength(0);
});

test("administra catálogos comerciales compactos sin afectar el flujo del caso", async ({ page }) => {
  await authorize(page); await mockDomains(page); await page.goto("/commercial/relationships");
  await expect(page.getByRole("heading", { name: "Relaciones Comerciales" })).toBeVisible();
  for (const tab of ["Tarifarios", "Referidos", "Comisiones", "Asociaciones", "Certificaciones"]) {
    await page.getByRole("tab", { name: tab }).click();
  }
  await expect(page.getByText("CERTIFICACIÓN PREVIEW")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
});
