import { Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";
import {
  CommercialRelationshipsError,
  commercialPayloadHash,
  normalizeCaseCommercialContextPublish,
  normalizeAssociationMembershipCreate,
  normalizeCertificationCreate,
  normalizeCommissionAgreementPublish,
  normalizeCommercialContactCreate,
  normalizeCommercialEntityCreate,
  normalizeCommercialEntityUpdate,
  normalizeCommercialRelationshipCreate,
  normalizeCommercialTariffPublish,
  normalizePricingAgreementPublish,
  normalizeReferralAgreementPublish,
  normalizeInstructionPublish,
  normalizeCommercialCaseRef,
  requirePublishedPayer,
} from "./commercialRelationshipsContract.js";

function fail(code, status = 400) { throw new CommercialRelationshipsError(code, status); }
function permit(context, permission) { if (!context.effectivePermissions?.includes(permission) || context.deniedPermissions?.includes(permission)) fail("COMMERCIAL_RELATIONSHIPS_FORBIDDEN", 403); }
function actor(context) { return { actorMembershipId: context.membershipId, actorUserId: context.userId }; }
function audit(context, action, entity, entityId, requestId, before, after) { return { tenant_id: context.tenantId, actor_user_id: context.userId, actor_membership_id: context.membershipId, role_snapshot: context.role, action, entity, entityId, before_json: before, after_json: after, source: "V17_COMMERCIAL_RELATIONSHIPS", request_id: requestId, correlation_id: requestId, critical: true }; }
async function replay(tx, context, input) { const previous = await tx.commercialRelationshipCommand.findUnique({ where: { tenantId_requestId: { tenantId: context.tenantId, requestId: input.requestId } } }); if (!previous) return null; if (previous.payloadHash !== input.payloadHash) fail("COMMERCIAL_RELATIONSHIPS_IDEMPOTENCY_CONFLICT", 409); return previous.resultJson; }
async function record(tx, context, input, targetRef, aggregateType, eventType, before, result) {
  await tx.commercialRelationshipCommand.create({ data: { tenantId: context.tenantId, requestId: input.requestId, operation: input.operation, payloadHash: input.payloadHash, targetRef, resultJson: result, ...actor(context) } });
  await tx.commercialRelationshipEvent.create({ data: { tenantId: context.tenantId, aggregateType, aggregateRef: targetRef, eventType, beforeSnapshot: before, afterSnapshot: result, requestId: input.requestId, ...actor(context) } });
  await tx.commercialAuditLog.create({ data: audit(context, eventType, aggregateType, targetRef, input.requestId, before, result) });
}
function entityDto(row) { return Object.freeze({ entityRef: row.entityRef, code: row.code, displayName: row.displayName, legalName: row.legalName, kind: row.kind, countryCode: row.countryCode, status: row.status, validFrom: row.validFrom?.toISOString() || null, validTo: row.validTo?.toISOString() || null, version: row.version, client: row.client ? { clientRef: row.client.publicRef, displayName: row.client.name, type: row.client.type, status: row.client.status } : null, contacts: Object.freeze((row.contacts || []).map((contact) => ({ contactRef: contact.contactRef, displayName: contact.displayName, position: contact.position, preferredChannel: contact.preferredChannel, status: contact.status, validFrom: contact.validFrom?.toISOString() || null, validTo: contact.validTo?.toISOString() || null, version: contact.version }))) }); }
function relationshipDto(row) { return Object.freeze({ relationshipRef: row.relationshipRef, source: { entityRef: row.sourceEntity.entityRef, displayName: row.sourceEntity.displayName, kind: row.sourceEntity.kind }, target: { entityRef: row.targetEntity.entityRef, displayName: row.targetEntity.displayName, kind: row.targetEntity.kind }, type: row.type, reference: row.reference, conditions: row.conditions, metadata: row.metadata, status: row.status, validFrom: row.validFrom?.toISOString() || null, validTo: row.validTo?.toISOString() || null, version: row.version }); }

export async function listCommercialEntities(prisma, context, query = {}) {
  permit(context, "commercial:relationships:view"); const page = Math.max(1, Number(query.page) || 1); const pageSize = Math.min(50, Math.max(1, Number(query.pageSize) || 20)); const search = String(query.search || "").trim();
  const where = { tenantId: context.tenantId, ...(query.kind ? { kind: String(query.kind) } : {}), ...(query.status ? { status: String(query.status) } : {}), ...(search ? { OR: [{ code: { contains: search, mode: "insensitive" } }, { displayName: { contains: search, mode: "insensitive" } }, { legalName: { contains: search, mode: "insensitive" } }] } : {}) };
  const [total, rows] = await Promise.all([prisma.commercialEntity.count({ where }), prisma.commercialEntity.findMany({ where, include: { client: true, contacts: { where: { status: "ACTIVE" }, orderBy: { displayName: "asc" } } }, orderBy: [{ displayName: "asc" }, { code: "asc" }], skip: (page - 1) * pageSize, take: pageSize })]);
  return Object.freeze({ page, pageSize, total, items: Object.freeze(rows.map(entityDto)) });
}

export async function listCommercialRelationships(prisma, context, query = {}) {
  permit(context, "commercial:relationships:view"); const where = { tenantId: context.tenantId, ...(query.status ? { status: String(query.status) } : {}), ...(query.type ? { type: String(query.type) } : {}) }; const rows = await prisma.commercialRelationship.findMany({ where, include: { sourceEntity: true, targetEntity: true }, orderBy: [{ updatedAt: "desc" }, { relationshipRef: "asc" }], take: 100 }); return Object.freeze(rows.map(relationshipDto));
}

export async function getCommercialRelationshipsWorkspace(prisma, context) {
  permit(context, "commercial:relationships:view");
  const now = new Date();
  const canViewCommissions = context.effectivePermissions?.includes("commercial:commissions:view") && !context.deniedPermissions?.includes("commercial:commissions:view");
  const active = { state: "PUBLISHED", AND: [{ OR: [{ validFrom: null }, { validFrom: { lte: now } }] }, { OR: [{ validTo: null }, { validTo: { gt: now } }] }] };
  const [tariffs, agreements, referrals, commissions, associations, certifications] = await Promise.all([
    prisma.commercialTariffVersion.findMany({ where: { tenantId: context.tenantId, ...active }, orderBy: [{ seriesRef: "asc" }, { version: "desc" }] }),
    prisma.commercialPricingAgreementVersion.findMany({ where: { tenantId: context.tenantId, ...active }, include: { entity: true, relationship: true, tariffVersion: true, adjustments: true }, orderBy: { version: "desc" } }),
    prisma.commercialReferralAgreementVersion.findMany({ where: { tenantId: context.tenantId, ...active }, include: { referrerEntity: true }, orderBy: { version: "desc" } }),
    canViewCommissions ? prisma.commercialCommissionAgreementVersion.findMany({ where: { tenantId: context.tenantId, ...active }, include: { beneficiaryEntity: true }, orderBy: { version: "desc" } }) : [],
    prisma.commercialAssociationMembership.findMany({ where: { tenantId: context.tenantId, status: "ACTIVE" }, include: { memberEntity: true, associationEntity: true }, orderBy: { updatedAt: "desc" } }),
    prisma.commercialCertification.findMany({ where: { tenantId: context.tenantId, status: "ACTIVE" }, include: { entity: true }, orderBy: { expiresAt: "asc" } }),
  ]);
  return Object.freeze({
    tariffs: tariffs.map((row) => ({ tariffRef: row.tariffRef, seriesRef: row.seriesRef, code: row.code, name: row.name, version: row.version, currency: row.currency, scope: row.scope, validFrom: row.validFrom?.toISOString() || null, validTo: row.validTo?.toISOString() || null })),
    pricingAgreements: agreements.map((row) => ({ pricingAgreementRef: row.agreementRef, seriesRef: row.seriesRef, version: row.version, entity: row.entity ? { entityRef: row.entity.entityRef, displayName: row.entity.displayName } : null, relationshipRef: row.relationship?.relationshipRef || null, tariffRef: row.tariffVersion.tariffRef, tariffCode: row.tariffVersion.code, serviceScope: row.serviceScope, modeScope: row.modeScope, adjustments: row.adjustments.map((item) => ({ adjustmentRef: item.adjustmentRef, kind: item.kind, calculationType: item.calculationType, value: Number(item.value), base: item.base, reasonCode: item.reasonCode })) })),
    referrals: referrals.map((row) => ({ referralAgreementRef: row.referralAgreementRef, seriesRef: row.seriesRef, version: row.version, referrer: { entityRef: row.referrerEntity.entityRef, displayName: row.referrerEntity.displayName }, calculationType: row.calculationType, value: Number(row.value), currency: row.currency, reference: row.reference, validFrom: row.validFrom?.toISOString() || null, validTo: row.validTo?.toISOString() || null })),
    commissions: commissions.map((row) => ({ commissionAgreementRef: row.commissionAgreementRef, seriesRef: row.seriesRef, version: row.version, kind: row.kind, beneficiary: { entityRef: row.beneficiaryEntity.entityRef, displayName: row.beneficiaryEntity.displayName }, calculationType: row.calculationType, value: Number(row.value), currency: row.currency, basisPolicy: row.basisPolicy })),
    associations: associations.map((row) => ({ membershipRef: row.membershipRef, member: { entityRef: row.memberEntity.entityRef, displayName: row.memberEntity.displayName }, association: { entityRef: row.associationEntity.entityRef, displayName: row.associationEntity.displayName }, membershipNumber: row.membershipNumber, validFrom: row.validFrom?.toISOString() || null, validTo: row.validTo?.toISOString() || null })),
    certifications: certifications.map((row) => ({ certificationRef: row.certificationRef, entity: { entityRef: row.entity.entityRef, displayName: row.entity.displayName }, type: row.type, issuer: row.issuer, issuedAt: row.issuedAt?.toISOString().slice(0, 10) || null, expiresAt: row.expiresAt?.toISOString().slice(0, 10) || null, status: row.status })),
  });
}

export async function createCommercialEntity(prisma, context, raw) {
  permit(context, "commercial:relationships:manage"); const input = normalizeCommercialEntityCreate(raw);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; let clientId = null; if (input.clientRef) { const client = await tx.client.findFirst({ where: { tenantId: context.tenantId, publicRef: input.clientRef }, select: { id: true } }); if (!client) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); clientId = client.id; }
    const possibleDuplicates = await tx.commercialEntity.findMany({ where: { tenantId: context.tenantId, OR: [{ displayName: { equals: input.displayName, mode: "insensitive" } }, ...(input.taxReference ? [{ taxReferenceNormalized: input.taxReference }] : [])] }, select: { entityRef: true, displayName: true, kind: true }, take: 5 });
    const row = await tx.commercialEntity.create({ data: { tenantId: context.tenantId, clientId, code: input.code, displayName: input.displayName, legalName: input.legalName, kind: input.kind, countryCode: input.countryCode, taxReferenceNormalized: input.taxReference, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null }, include: { client: true, contacts: true } }); const result = { ...entityDto(row), possibleDuplicates }; await record(tx, context, input, row.entityRef, "CommercialEntity", "COMMERCIAL_ENTITY_CREATED", null, result); return Object.freeze(result);
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function updateCommercialEntity(prisma, context, raw) {
  permit(context, "commercial:relationships:manage"); const input = normalizeCommercialEntityUpdate(raw);
  return prisma.$transaction(async (tx) => {
    const cached = await replay(tx, context, input); if (cached) return cached;
    const current = await tx.commercialEntity.findFirst({ where: { tenantId: context.tenantId, entityRef: input.entityRef }, include: { client: true, contacts: { where: { status: "ACTIVE" }, orderBy: { displayName: "asc" } } } });
    if (!current) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404);
    if (current.version !== input.expectedVersion) fail("COMMERCIAL_RELATIONSHIPS_VERSION_CONFLICT", 409);
    const changed = await tx.commercialEntity.updateMany({ where: { id: current.id, tenantId: context.tenantId, version: input.expectedVersion }, data: { displayName: input.displayName, legalName: input.legalName, countryCode: input.countryCode, taxReferenceNormalized: input.taxReference, status: input.status, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null, version: { increment: 1 } } });
    if (changed.count !== 1) fail("COMMERCIAL_RELATIONSHIPS_VERSION_CONFLICT", 409);
    const updated = await tx.commercialEntity.findFirst({ where: { tenantId: context.tenantId, entityRef: input.entityRef }, include: { client: true, contacts: { where: { status: "ACTIVE" }, orderBy: { displayName: "asc" } } } });
    const result = entityDto(updated); await record(tx, context, input, updated.entityRef, "CommercialEntity", "COMMERCIAL_ENTITY_UPDATED", entityDto(current), result); return result;
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function createCommercialRelationship(prisma, context, raw) {
  permit(context, "commercial:relationships:manage"); const input = normalizeCommercialRelationshipCreate(raw);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; const entities = await tx.commercialEntity.findMany({ where: { tenantId: context.tenantId, entityRef: { in: [input.sourceEntityRef, input.targetEntityRef] }, status: "ACTIVE" } }); if (entities.length !== 2) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); const byRef = new Map(entities.map((row) => [row.entityRef, row])); const row = await tx.commercialRelationship.create({ data: { tenantId: context.tenantId, sourceEntityId: byRef.get(input.sourceEntityRef).id, targetEntityId: byRef.get(input.targetEntityRef).id, type: input.type, reference: input.reference, conditions: input.conditions, metadata: input.metadata, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null }, include: { sourceEntity: true, targetEntity: true } }); const result = relationshipDto(row); await record(tx, context, input, row.relationshipRef, "CommercialRelationship", "COMMERCIAL_RELATIONSHIP_CREATED", null, result); return result; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function createCommercialContact(prisma, context, raw) {
  permit(context, "commercial:relationships:manage"); const input = normalizeCommercialContactCreate(raw);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; const entity = await tx.commercialEntity.findFirst({ where: { tenantId: context.tenantId, entityRef: input.entityRef, status: "ACTIVE" }, select: { id: true } }); if (!entity) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); const row = await tx.commercialEntityContact.create({ data: { tenantId: context.tenantId, entityId: entity.id, displayName: input.displayName, position: input.position, emailNormalized: input.email, phoneNormalized: input.phone, preferredChannel: input.preferredChannel, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null } }); const result = { contactRef: row.contactRef, entityRef: input.entityRef, displayName: row.displayName, position: row.position, preferredChannel: row.preferredChannel, status: row.status, validFrom: row.validFrom?.toISOString() || null, validTo: row.validTo?.toISOString() || null, version: row.version }; await record(tx, context, input, row.contactRef, "CommercialEntityContact", "COMMERCIAL_CONTACT_CREATED", null, result); return Object.freeze(result); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function createAssociationMembership(prisma, context, raw) {
  permit(context, "commercial:associations:manage"); const input = normalizeAssociationMembershipCreate(raw);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; const entities = await tx.commercialEntity.findMany({ where: { tenantId: context.tenantId, entityRef: { in: [input.memberEntityRef, input.associationEntityRef] }, status: "ACTIVE" } }); if (entities.length !== 2) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); const byRef = new Map(entities.map((row) => [row.entityRef, row])); if (byRef.get(input.associationEntityRef).kind !== "ASSOCIATION") fail("COMMERCIAL_ASSOCIATION_AUTHORITY_INVALID", 409); const row = await tx.commercialAssociationMembership.create({ data: { tenantId: context.tenantId, memberEntityId: byRef.get(input.memberEntityRef).id, associationEntityId: byRef.get(input.associationEntityRef).id, membershipNumber: input.membershipNumber, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null } }); const result = { membershipRef: row.membershipRef, memberEntityRef: input.memberEntityRef, associationEntityRef: input.associationEntityRef, membershipNumber: row.membershipNumber, status: row.status, validFrom: row.validFrom?.toISOString() || null, validTo: row.validTo?.toISOString() || null, version: row.version }; await record(tx, context, input, row.membershipRef, "CommercialAssociationMembership", "COMMERCIAL_ASSOCIATION_MEMBERSHIP_CREATED", null, result); return Object.freeze(result); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function createCommercialCertification(prisma, context, raw) {
  permit(context, "commercial:associations:manage"); const input = normalizeCertificationCreate(raw);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; const entity = await tx.commercialEntity.findFirst({ where: { tenantId: context.tenantId, entityRef: input.entityRef, status: "ACTIVE" }, select: { id: true } }); if (!entity) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); const row = await tx.commercialCertification.create({ data: { tenantId: context.tenantId, entityId: entity.id, type: input.type, issuer: input.issuer, documentRef: input.documentRef, issuedAt: input.issuedAt ? new Date(`${input.issuedAt}T00:00:00.000Z`) : null, expiresAt: input.expiresAt ? new Date(`${input.expiresAt}T00:00:00.000Z`) : null } }); const result = { certificationRef: row.certificationRef, entityRef: input.entityRef, type: row.type, issuer: row.issuer, documentRef: row.documentRef, issuedAt: input.issuedAt, expiresAt: input.expiresAt, status: row.status, version: row.version }; await record(tx, context, input, row.certificationRef, "CommercialCertification", "COMMERCIAL_CERTIFICATION_CREATED", null, result); return Object.freeze(result); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function publishCommercialInstruction(prisma, context, raw) {
  permit(context, "commercial:relationships:manage"); const input = normalizeInstructionPublish(raw);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; const [entity, relationship] = await Promise.all([input.entityRef ? tx.commercialEntity.findFirst({ where: { tenantId: context.tenantId, entityRef: input.entityRef }, select: { id: true } }) : null, input.relationshipRef ? tx.commercialRelationship.findFirst({ where: { tenantId: context.tenantId, relationshipRef: input.relationshipRef }, select: { id: true } }) : null]); if (!entity && !relationship) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); const seriesRef = input.seriesRef || randomUUID(); const version = await nextVersion(tx, "commercialInstructionVersion", context.tenantId, seriesRef, input.expectedVersion); const logicalSha256 = commercialPayloadHash({ entityRef: input.entityRef, relationshipRef: input.relationshipRef, category: input.category, serviceScope: input.serviceScope, content: input.content, validFrom: input.validFrom, validTo: input.validTo }); const row = await tx.commercialInstructionVersion.create({ data: { tenantId: context.tenantId, seriesRef, entityId: entity?.id, relationshipId: relationship?.id, version, state: "PUBLISHED", category: input.category, serviceScope: input.serviceScope, content: input.content, logicalSha256, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null, publishedAt: new Date() } }); const result = { instructionRef: row.instructionRef, seriesRef, entityRef: input.entityRef, relationshipRef: input.relationshipRef, version, state: row.state, category: row.category, serviceScope: row.serviceScope, content: row.content, logicalSha256 }; await record(tx, context, input, row.instructionRef, "CommercialInstructionVersion", "COMMERCIAL_INSTRUCTION_PUBLISHED", null, result); return Object.freeze(result); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

async function nextVersion(tx, model, tenantId, seriesRef, expectedVersion) { const current = await tx[model].findFirst({ where: { tenantId, seriesRef }, orderBy: { version: "desc" }, select: { version: true } }); if ((current?.version || 0) !== expectedVersion) fail("COMMERCIAL_RELATIONSHIPS_VERSION_CONFLICT", 409); return expectedVersion + 1; }

export async function publishCommercialTariff(prisma, context, raw) {
  permit(context, "commercial:tariffs:manage"); const input = normalizeCommercialTariffPublish(raw);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; const seriesRef = input.seriesRef || randomUUID(); const version = await nextVersion(tx, "commercialTariffVersion", context.tenantId, seriesRef, input.expectedVersion); const logicalSha256 = commercialPayloadHash({ code: input.code, name: input.name, currency: input.currency, scope: input.scope, rateDefinition: input.rateDefinition, validFrom: input.validFrom, validTo: input.validTo }); const row = await tx.commercialTariffVersion.create({ data: { tenantId: context.tenantId, seriesRef, code: input.code, name: input.name, version, state: "PUBLISHED", currency: input.currency, scope: input.scope, rateDefinition: input.rateDefinition, logicalSha256, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null, publishedAt: new Date() } }); const result = { tariffRef: row.tariffRef, seriesRef: row.seriesRef, code: row.code, name: row.name, version: row.version, state: row.state, currency: row.currency, scope: row.scope, validFrom: row.validFrom?.toISOString() || null, validTo: row.validTo?.toISOString() || null, logicalSha256 }; await record(tx, context, input, row.tariffRef, "CommercialTariffVersion", "COMMERCIAL_TARIFF_PUBLISHED", null, result); return Object.freeze(result); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function publishPricingAgreement(prisma, context, raw) {
  permit(context, "commercial:tariffs:manage"); const input = normalizePricingAgreementPublish(raw);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; const [entity, relationship, tariff] = await Promise.all([input.entityRef ? tx.commercialEntity.findFirst({ where: { tenantId: context.tenantId, entityRef: input.entityRef }, select: { id: true } }) : null, input.relationshipRef ? tx.commercialRelationship.findFirst({ where: { tenantId: context.tenantId, relationshipRef: input.relationshipRef }, select: { id: true } }) : null, tx.commercialTariffVersion.findFirst({ where: { tenantId: context.tenantId, tariffRef: input.tariffRef, state: "PUBLISHED" }, select: { id: true } })]); if (!tariff || (!entity && !relationship)) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); const seriesRef = input.seriesRef || randomUUID(); const version = await nextVersion(tx, "commercialPricingAgreementVersion", context.tenantId, seriesRef, input.expectedVersion); const snapshot = { entityRef: input.entityRef, relationshipRef: input.relationshipRef, tariffRef: input.tariffRef, serviceScope: input.serviceScope, modeScope: input.modeScope, conditions: input.conditions, administrativeTerms: input.administrativeTerms, adjustments: input.adjustments, validFrom: input.validFrom, validTo: input.validTo }; const logicalSha256 = commercialPayloadHash(snapshot); const row = await tx.commercialPricingAgreementVersion.create({ data: { tenantId: context.tenantId, seriesRef, entityId: entity?.id, relationshipId: relationship?.id, tariffVersionId: tariff.id, version, state: "PUBLISHED", serviceScope: input.serviceScope, modeScope: input.modeScope, conditions: input.conditions, administrativeTerms: input.administrativeTerms, logicalSha256, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null, publishedAt: new Date(), adjustments: { create: input.adjustments.map((row) => ({ kind: row.kind, calculationType: row.calculationType, value: row.value, base: row.base, reasonCode: row.reasonCode, approvalRef: row.approvalRef, validFrom: row.validFrom ? new Date(row.validFrom) : null, validTo: row.validTo ? new Date(row.validTo) : null })) } } }); const result = { pricingAgreementRef: row.agreementRef, seriesRef: row.seriesRef, version, state: row.state, ...snapshot, logicalSha256 }; await record(tx, context, input, row.agreementRef, "CommercialPricingAgreementVersion", "COMMERCIAL_PRICING_AGREEMENT_PUBLISHED", null, result); return Object.freeze(result); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function publishReferralAgreement(prisma, context, raw) {
  permit(context, "commercial:referrals:manage"); const input = normalizeReferralAgreementPublish(raw);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; const referrer = await tx.commercialEntity.findFirst({ where: { tenantId: context.tenantId, entityRef: input.referrerEntityRef }, select: { id: true } }); if (!referrer) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); const seriesRef = input.seriesRef || randomUUID(); const version = await nextVersion(tx, "commercialReferralAgreementVersion", context.tenantId, seriesRef, input.expectedVersion); const logicalSha256 = commercialPayloadHash(input); const row = await tx.commercialReferralAgreementVersion.create({ data: { tenantId: context.tenantId, seriesRef, referrerEntityId: referrer.id, version, state: "PUBLISHED", calculationType: input.calculationType, value: input.value, currency: input.currency, basisPolicy: input.basisPolicy, serviceScope: input.serviceScope, authorizationRef: input.authorizationRef, reference: input.reference, logicalSha256, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null, publishedAt: new Date() } }); const result = { referralAgreementRef: row.referralAgreementRef, seriesRef, referrerEntityRef: input.referrerEntityRef, version, state: row.state, calculationType: row.calculationType, value: Number(row.value), currency: row.currency, basisPolicy: row.basisPolicy, serviceScope: row.serviceScope, reference: row.reference, logicalSha256 }; await record(tx, context, input, row.referralAgreementRef, "CommercialReferralAgreementVersion", "COMMERCIAL_REFERRAL_AGREEMENT_PUBLISHED", null, result); return Object.freeze(result); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function publishCommissionAgreement(prisma, context, raw) {
  permit(context, "commercial:commissions:manage"); const input = normalizeCommissionAgreementPublish(raw);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; const [beneficiary, referral] = await Promise.all([tx.commercialEntity.findFirst({ where: { tenantId: context.tenantId, entityRef: input.beneficiaryEntityRef }, select: { id: true } }), input.referralAgreementRef ? tx.commercialReferralAgreementVersion.findFirst({ where: { tenantId: context.tenantId, referralAgreementRef: input.referralAgreementRef, state: "PUBLISHED" }, select: { id: true } }) : null]); if (!beneficiary || (input.referralAgreementRef && !referral)) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); const seriesRef = input.seriesRef || randomUUID(); const version = await nextVersion(tx, "commercialCommissionAgreementVersion", context.tenantId, seriesRef, input.expectedVersion); const logicalSha256 = commercialPayloadHash(input); const row = await tx.commercialCommissionAgreementVersion.create({ data: { tenantId: context.tenantId, seriesRef, beneficiaryEntityId: beneficiary.id, referralAgreementId: referral?.id, version, state: "PUBLISHED", kind: input.kind, calculationType: input.calculationType, value: input.value, currency: input.currency, basisPolicy: input.basisPolicy, serviceScope: input.serviceScope, logicalSha256, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null, publishedAt: new Date() } }); const result = { commissionAgreementRef: row.commissionAgreementRef, seriesRef, beneficiaryEntityRef: input.beneficiaryEntityRef, referralAgreementRef: input.referralAgreementRef, version, state: row.state, kind: row.kind, calculationType: row.calculationType, value: Number(row.value), currency: row.currency, basisPolicy: row.basisPolicy, serviceScope: row.serviceScope, logicalSha256 }; await record(tx, context, input, row.commissionAgreementRef, "CommercialCommissionAgreementVersion", "COMMERCIAL_COMMISSION_AGREEMENT_PUBLISHED", null, result); return Object.freeze(result); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export function buildCommercialContextSnapshot(contextRow) {
  if (!contextRow || contextRow.state !== "PUBLISHED") fail("COMMERCIAL_CONTEXT_NOT_PUBLISHED", 409);
  const parties = contextRow.parties.map((party) => ({ role: party.role, entityRef: party.entity.entityRef, relationshipRef: party.relationship?.relationshipRef || null, displayName: party.entity.displayName, kind: party.entity.kind, validFrom: party.relationship?.validFrom?.toISOString() || party.entity.validFrom?.toISOString() || null, validTo: party.relationship?.validTo?.toISOString() || party.entity.validTo?.toISOString() || null, contacts: (party.entity.contacts || []).map((contact) => ({ contactRef: contact.contactRef, displayName: contact.displayName, position: contact.position, preferredChannel: contact.preferredChannel })) }));
  const payer = parties.find((entry) => entry.role === "PAYER") || null;
  const agreement = contextRow.pricingAgreement ? { pricingAgreementRef: contextRow.pricingAgreement.agreementRef, version: contextRow.pricingAgreement.version, validFrom: contextRow.pricingAgreement.validFrom?.toISOString() || null, validTo: contextRow.pricingAgreement.validTo?.toISOString() || null, tariff: contextRow.pricingAgreement.tariffVersion ? { tariffRef: contextRow.pricingAgreement.tariffVersion.tariffRef, code: contextRow.pricingAgreement.tariffVersion.code, name: contextRow.pricingAgreement.tariffVersion.name, version: contextRow.pricingAgreement.tariffVersion.version, currency: contextRow.pricingAgreement.tariffVersion.currency } : null, adjustments: (contextRow.pricingAgreement.adjustments || []).map((item) => ({ adjustmentRef: item.adjustmentRef, kind: item.kind, calculationType: item.calculationType, value: Number(item.value), base: item.base, reasonCode: item.reasonCode, authorized: Boolean(item.approvalRef), validFrom: item.validFrom?.toISOString() || null, validTo: item.validTo?.toISOString() || null })) } : null;
  const referral = contextRow.referralAgreement ? { referralAgreementRef: contextRow.referralAgreement.referralAgreementRef, version: contextRow.referralAgreement.version, calculationType: contextRow.referralAgreement.calculationType, value: Number(contextRow.referralAgreement.value), currency: contextRow.referralAgreement.currency, reference: contextRow.referralAgreement.reference, validFrom: contextRow.referralAgreement.validFrom?.toISOString() || null, validTo: contextRow.referralAgreement.validTo?.toISOString() || null } : null;
  return Object.freeze({ commercialContextRef: contextRow.contextRef, seriesRef: contextRow.seriesRef, version: contextRow.version, commercialRelationshipRef: payer?.relationshipRef || null, payerRef: payer?.entityRef || null, pricingAgreementRef: agreement?.pricingAgreementRef || null, referralAgreementRef: referral?.referralAgreementRef || null, agreement, referral, parties: Object.freeze(parties), associations: contextRow.associationsSnapshot, instructions: contextRow.instructionsSnapshot, logicalSha256: contextRow.logicalSha256 });
}

export function buildCommercialQuoteSnapshot(contextRow) {
  const snapshot = buildCommercialContextSnapshot(contextRow);
  requirePublishedPayer(snapshot.parties);
  return snapshot;
}

function quoteRelationship(snapshot, role) {
  const party = snapshot.parties.find((entry) => entry.role === role);
  return party ? { kind: role, reference: party.relationshipRef || party.entityRef, displayName: party.displayName, version: snapshot.version, validFrom: null, validUntil: null, conditions: null } : null;
}

const commercialContextInclude = { parties: { include: { entity: { include: { contacts: { where: { status: "ACTIVE" }, orderBy: { displayName: "asc" } } } }, relationship: true }, orderBy: { role: "asc" } }, pricingAgreement: { include: { tariffVersion: true, adjustments: true } }, referralAgreement: true };

export async function resolveCommercialQuoteAuthority(prisma, context, pipelineCaseId) {
  const row = await prisma.pipelineCaseCommercialContextVersion.findFirst({ where: { tenantId: context.tenantId, pipelineCaseId, state: "PUBLISHED" }, include: commercialContextInclude, orderBy: { version: "desc" } });
  if (!row) return null;
  const snapshot = buildCommercialQuoteSnapshot(row);
  const payer = snapshot.parties.find((entry) => entry.role === "PAYER");
  const payerKind = payer.kind === "COMPANY" ? "COMPANY" : payer.kind === "LEAD_ACCOUNT" ? "LEAD_ACCOUNT" : payer.kind === "THIRD_PARTY" ? "THIRD_PARTY" : "AUTHORIZED_ENTITY";
  return Object.freeze({
    commercialContext: {
      company: quoteRelationship(snapshot, "COMPANY"),
      leadAccount: quoteRelationship(snapshot, "LEAD_ACCOUNT"),
      booker: quoteRelationship(snapshot, "BOOKER"),
      tariff: snapshot.pricingAgreementRef ? { kind: "PRICING_AGREEMENT", reference: snapshot.pricingAgreementRef, displayName: "Acuerdo comercial publicado", version: snapshot.version, validFrom: null, validUntil: null, conditions: null } : null,
      associations: snapshot.associations.map((entry) => entry.associationName),
      referral: snapshot.referralAgreementRef ? { kind: "REFERRAL_AGREEMENT", reference: snapshot.referralAgreementRef, displayName: "Acuerdo de referido publicado", version: snapshot.version, validFrom: null, validUntil: null, conditions: null } : null,
      commissionContext: null,
    },
    payer: { kind: payerKind, reference: snapshot.payerRef, displayName: payer.displayName, sourceVersion: snapshot.version, validFrom: null, validUntil: null, conditions: null },
    commercialContextRef: snapshot.commercialContextRef,
  });
}

export async function getCaseCommercialContext(prisma, context, caseRef, { requirePayer = false } = {}) {
  permit(context, "commercial:relationships:view");
  const normalizedCaseRef = normalizeCommercialCaseRef(caseRef);
  const pipelineCase = await prisma.pipelineCase.findFirst({ where: { tenantId: context.tenantId, publicRef: normalizedCaseRef }, select: { id: true } });
  if (!pipelineCase) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404);
  const row = await prisma.pipelineCaseCommercialContextVersion.findFirst({ where: { tenantId: context.tenantId, pipelineCaseId: pipelineCase.id, state: "PUBLISHED" }, include: commercialContextInclude, orderBy: { version: "desc" } });
  if (!row) return null;
  return requirePayer ? buildCommercialQuoteSnapshot(row) : buildCommercialContextSnapshot(row);
}

export async function publishCaseCommercialContext(prisma, context, caseRef, raw) {
  permit(context, "commercial:relationships:manage"); const input = normalizeCaseCommercialContextPublish(raw, caseRef);
  return prisma.$transaction(async (tx) => { const cached = await replay(tx, context, input); if (cached) return cached; const pipelineCase = await tx.pipelineCase.findFirst({ where: { tenantId: context.tenantId, publicRef: input.caseRef }, select: { id: true } }); if (!pipelineCase) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); const entityRefs = [...new Set(input.parties.map((party) => party.entityRef))]; const relationshipRefs = [...new Set(input.parties.map((party) => party.relationshipRef).filter(Boolean))]; const [entities, relationships, pricing, referral] = await Promise.all([tx.commercialEntity.findMany({ where: { tenantId: context.tenantId, entityRef: { in: entityRefs }, status: "ACTIVE" } }), tx.commercialRelationship.findMany({ where: { tenantId: context.tenantId, relationshipRef: { in: relationshipRefs }, status: "ACTIVE" } }), input.pricingAgreementRef ? tx.commercialPricingAgreementVersion.findFirst({ where: { tenantId: context.tenantId, agreementRef: input.pricingAgreementRef, state: "PUBLISHED" } }) : null, input.referralAgreementRef ? tx.commercialReferralAgreementVersion.findFirst({ where: { tenantId: context.tenantId, referralAgreementRef: input.referralAgreementRef, state: "PUBLISHED" } }) : null]); if (entities.length !== entityRefs.length || relationships.length !== relationshipRefs.length || (input.pricingAgreementRef && !pricing) || (input.referralAgreementRef && !referral)) fail("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); const entityByRef = new Map(entities.map((row) => [row.entityRef, row])); const relationshipByRef = new Map(relationships.map((row) => [row.relationshipRef, row])); for (const party of input.parties) { const relationship = party.relationshipRef ? relationshipByRef.get(party.relationshipRef) : null; if (relationship && relationship.sourceEntityId !== entityByRef.get(party.entityRef).id && relationship.targetEntityId !== entityByRef.get(party.entityRef).id) fail("COMMERCIAL_RELATIONSHIP_CONTEXT_MISMATCH", 409); }
    const seriesRef = input.seriesRef || randomUUID(); const version = await nextVersion(tx, "pipelineCaseCommercialContextVersion", context.tenantId, seriesRef, input.expectedVersion); const associations = await tx.commercialAssociationMembership.findMany({ where: { tenantId: context.tenantId, memberEntityId: { in: entities.map((row) => row.id) }, status: "ACTIVE" }, include: { associationEntity: true } }); const instructions = await tx.commercialInstructionVersion.findMany({ where: { tenantId: context.tenantId, state: "PUBLISHED", OR: [{ entityId: { in: entities.map((row) => row.id) } }, { relationshipId: { in: relationships.map((row) => row.id) } }] }, orderBy: { version: "desc" } }); const associationsSnapshot = associations.map((row) => ({ membershipRef: row.membershipRef, associationRef: row.associationEntity.entityRef, associationName: row.associationEntity.displayName, membershipNumber: row.membershipNumber, validFrom: row.validFrom?.toISOString() || null, validTo: row.validTo?.toISOString() || null })); const instructionsSnapshot = instructions.map((row) => ({ instructionRef: row.instructionRef, category: row.category, serviceScope: row.serviceScope, content: row.content, logicalSha256: row.logicalSha256 })); const logicalInput = { caseRef: input.caseRef, parties: input.parties, pricingAgreementRef: input.pricingAgreementRef, referralAgreementRef: input.referralAgreementRef, associations: associationsSnapshot, instructions: instructionsSnapshot }; const logicalSha256 = commercialPayloadHash(logicalInput); const row = await tx.pipelineCaseCommercialContextVersion.create({ data: { tenantId: context.tenantId, pipelineCaseId: pipelineCase.id, seriesRef, pricingAgreementId: pricing?.id, referralAgreementId: referral?.id, version, state: "PUBLISHED", associationsSnapshot, instructionsSnapshot, logicalSha256, publishedAt: new Date(), createdByMembershipId: context.membershipId, createdByUserId: context.userId, parties: { create: input.parties.map((party) => ({ entityId: entityByRef.get(party.entityRef).id, relationshipId: party.relationshipRef ? relationshipByRef.get(party.relationshipRef).id : null, role: party.role })) } }, include: commercialContextInclude }); const result = buildCommercialContextSnapshot(row); await record(tx, context, input, row.contextRef, "PipelineCaseCommercialContextVersion", "COMMERCIAL_CASE_CONTEXT_PUBLISHED", null, result); return result; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export function mapCommercialRelationshipsDatabaseError(error) { if (error instanceof CommercialRelationshipsError) return error; if (error?.code === "P2002") return new CommercialRelationshipsError("COMMERCIAL_RELATIONSHIPS_CONFLICT", 409); if (error?.code === "P2003") return new CommercialRelationshipsError("COMMERCIAL_RELATIONSHIPS_NOT_FOUND", 404); if (error?.code === "P2034") return new CommercialRelationshipsError("COMMERCIAL_RELATIONSHIPS_CONCURRENCY_CONFLICT", 409); return error; }
