import { PERMS } from "./rbac.js";

export const EMPLOYEE_PROVISIONING_PERMISSIONS = Object.freeze({
  REQUEST: "employee:provisioning:request",
  VIEW: "employee:provisioning:view",
  VIEW_PII: "employee:provisioning:pii:view",
  APPROVE: "employee:provisioning:approve",
  CANCEL: "employee:provisioning:cancel",
  ROLE_A_PROPOSE: "employee:role:a:propose",
  ROLE_A_ASSIGN: "employee:role:a:assign",
});

export const EMPLOYEE_PROVISIONING_ROLES = Object.freeze([
  "A", "V", "K", "B", "C", "C1", "D", "E", "G", "N", "PA", "PB", "PC", "PD", "PF", "I", "PE",
]);

export const NEVER_DELEGABLE = new Set([
  "users:create",
  EMPLOYEE_PROVISIONING_PERMISSIONS.ROLE_A_ASSIGN,
  EMPLOYEE_PROVISIONING_PERMISSIONS.ROLE_A_PROPOSE,
]);

// Catálogo cerrado. Un permiso nuevo en RBAC no se vuelve delegable por accidente.
const DELEGABLE_BY_ROLE = Object.freeze({
  A: [PERMS.TEMPLATES_VIEW, PERMS.TEMPLATES_CREATE, PERMS.TEMPLATES_EDIT_DRAFT, PERMS.TEMPLATES_SUBMIT,
    PERMS.TEMPLATES_APPROVE, PERMS.TEMPLATES_REJECT, PERMS.TEMPLATES_PUBLISH, PERMS.TEMPLATES_ARCHIVE,
    PERMS.USERS_VIEW, PERMS.USERS_EDIT, PERMS.USERS_DELETE, PERMS.USERS_REACTIVATE,
    PERMS.CLIENTS_VIEW, PERMS.CLIENTS_CREATE, PERMS.CLIENTS_EDIT,
    PERMS.PROJECTS_VIEW, PERMS.PROJECTS_CREATE, PERMS.PROJECTS_EDIT, PERMS.PROJECTS_VALIDATE, PERMS.PROJECTS_RELEASE,
    PERMS.OSI_VIEW, PERMS.OSI_CREATE, PERMS.OSI_EDIT, PERMS.OSI_DISPATCH, PERMS.OSI_ASSIGN,
    PERMS.OPS_VIEW, PERMS.OPS_TRACKING, PERMS.OPS_CALENDAR, PERMS.OPS_WALL,
    PERMS.WMS_VIEW, PERMS.WMS_SCAN, PERMS.WMS_TRANSFER, PERMS.INVENTORY_VIEW, PERMS.INVENTORY_EDIT,
    PERMS.PURCHASES_VIEW, PERMS.PURCHASES_CREATE, PERMS.HR_VIEW, PERMS.HR_KPI, PERMS.HR_NOTA, PERMS.HR_BADGES,
    PERMS.FLEET_VIEW, PERMS.FLEET_EDIT, PERMS.SECURITY_VIEW, PERMS.SECURITY_SCAN],
  V: [PERMS.TEMPLATES_VIEW, PERMS.TEMPLATES_CREATE, PERMS.TEMPLATES_EDIT_DRAFT, PERMS.TEMPLATES_SUBMIT,
    PERMS.CLIENTS_VIEW, PERMS.CLIENTS_CREATE, PERMS.CLIENTS_EDIT, PERMS.PROJECTS_VIEW, PERMS.PROJECTS_CREATE,
    PERMS.PROJECTS_EDIT, PERMS.OSI_VIEW, PERMS.OSI_CREATE, PERMS.OSI_EDIT, PERMS.OPS_CALENDAR],
  K: [PERMS.TEMPLATES_VIEW, PERMS.TEMPLATES_CREATE, PERMS.TEMPLATES_EDIT_DRAFT, PERMS.TEMPLATES_SUBMIT,
    PERMS.CLIENTS_VIEW, PERMS.PROJECTS_VIEW, PERMS.PROJECTS_CREATE, PERMS.PROJECTS_VALIDATE,
    PERMS.PROJECTS_RELEASE, PERMS.OSI_VIEW, PERMS.OSI_EDIT, PERMS.OPS_VIEW, PERMS.OPS_TRACKING, PERMS.OPS_CALENDAR],
  B: [PERMS.TEMPLATES_VIEW, PERMS.OPS_VIEW, PERMS.OPS_TRACKING, PERMS.OPS_CALENDAR, PERMS.OPS_WALL,
    PERMS.OSI_VIEW, PERMS.OSI_CREATE, PERMS.OSI_EDIT, PERMS.OSI_ASSIGN, PERMS.PROJECTS_VIEW],
  C: [PERMS.TEMPLATES_VIEW, PERMS.WMS_VIEW, PERMS.WMS_SCAN, PERMS.WMS_TRANSFER, PERMS.INVENTORY_VIEW,
    PERMS.INVENTORY_EDIT, PERMS.PURCHASES_VIEW, PERMS.PURCHASES_CREATE, PERMS.OSI_VIEW],
  C1: [PERMS.TEMPLATES_VIEW, PERMS.OSI_VIEW, PERMS.OSI_DISPATCH, PERMS.WMS_VIEW, PERMS.WMS_SCAN],
  D: [PERMS.OSI_VIEW, PERMS.OSI_EDIT, PERMS.OPS_VIEW, PERMS.OPS_TRACKING],
  E: [PERMS.OSI_VIEW, PERMS.OPS_TRACKING],
  G: [PERMS.SECURITY_VIEW, PERMS.SECURITY_SCAN, PERMS.OSI_VIEW],
  N: [PERMS.OSI_VIEW], PA: [PERMS.WMS_VIEW, PERMS.OSI_VIEW], PB: [PERMS.OSI_VIEW, PERMS.FLEET_VIEW],
  PC: [PERMS.OSI_VIEW], PD: [PERMS.OSI_VIEW, PERMS.FLEET_VIEW], PF: [PERMS.OSI_VIEW],
  I: [PERMS.TEMPLATES_VIEW, PERMS.USERS_VIEW, PERMS.USERS_REACTIVATE, PERMS.HR_VIEW, PERMS.HR_KPI,
    PERMS.HR_NOTA, PERMS.HR_BADGES, PERMS.OSI_VIEW],
  PE: [PERMS.OSI_VIEW],
});

/**
 * Política de delegación cerrada: sólo permisos conocidos por el rol de destino,
 * nunca permisos administrativos de cuatro ojos. No modifica el RBAC heredado.
 */
export function delegablePermissionsForRole(role) {
  return Object.freeze([...(DELEGABLE_BY_ROLE[String(role || "").trim().toUpperCase()] || [])]
    .filter((permission) => !NEVER_DELEGABLE.has(permission)).sort());
}

export function effectiveDelegatedPermissions({ role, requested = [], deciderEffective = [], denied = [] }) {
  const allowed = new Set(delegablePermissionsForRole(role));
  const decider = new Set(deciderEffective.map(String));
  const blocked = new Set(denied.map(String));
  return Object.freeze([...new Set(requested.map(String))]
    .filter((permission) => allowed.has(permission) && decider.has(permission) && !blocked.has(permission))
    .sort());
}
