import { Prisma } from "@prisma/client";
import {
  ToolsEquipmentError, assetAvailability, assetFail,
  normalizeAssetAssignment, normalizeAssetHandout, normalizeAssetIncident,
  normalizeAssetInspection, normalizeAssetInstanceCreate, normalizeAssetMaintenance,
  normalizeAssetModelCreate, normalizeAssetReservation, normalizeAssetReturn, normalizeAssetCostVersion,
  normalizeAssetStateChange, normalizeExternalOffer, normalizeExternalReservation,
} from "./toolsEquipmentContract.js";

function requirePermission(context, permission) {
  if (!context?.tenantId || !context?.membershipId || !context?.userId || !context?.effectivePermissions?.includes(permission) || context.deniedPermissions?.includes(permission)) assetFail("ASSET_FORBIDDEN", 403);
}
function actor(context) { return { actorMembershipId: context.membershipId, actorUserId: context.userId }; }
function audit(context, action, entity, entityId, requestId, after) {
  return { tenant_id: context.tenantId, actor_user_id: context.userId, actor_membership_id: context.membershipId, role_snapshot: context.role, action, entity, entityId: String(entityId), after_json: after, source: "V17_TOOLS_EQUIPMENT", request_id: requestId, correlation_id: requestId, critical: true };
}
async function replay(tx, context, input) {
  const row = await tx.assetMutationCommand.findUnique({ where: { tenantId_requestId: { tenantId: context.tenantId, requestId: input.requestId } } });
  if (!row) return null;
  if (row.payloadHash !== input.payloadHash || row.operation !== input.operation) assetFail("ASSET_IDEMPOTENCY_CONFLICT", 409);
  return Object.freeze(row.resultJson);
}
async function persist(tx, context, input, targetRef, result, action, entity) {
  await tx.assetMutationCommand.create({ data: { tenantId: context.tenantId, requestId: input.requestId, operation: input.operation, payloadHash: input.payloadHash, targetRef: String(targetRef), resultJson: result, ...actor(context) } });
  await tx.commercialAuditLog.create({ data: audit(context, action, entity, targetRef, input.requestId, result) });
  return Object.freeze(result);
}
function mapModel(row) { return { modelRef: row.modelRef, code: row.code, name: row.name, description: row.description, family: row.family, resourceType: row.resourceType, serialPolicy: row.serialPolicy, identificationPolicy: row.identificationPolicy, capacity: row.capacity, status: row.status, version: row.version, instanceCount: row._count?.instances ?? undefined }; }
function mapLocation(row) { return row ? { locationRef: row.locationRef, code: row.code, name: row.name, path: row.path, warehouse: row.warehouse ? { warehouseRef: row.warehouse.warehouseRef, code: row.warehouse.code, name: row.warehouse.name } : undefined } : null; }
function mapAssignment(row) { return { assignmentRef: row.assignmentRef, status: row.status, operationalReference: row.operationalReference, assignee: row.assigneeMembership ? { membershipRef: row.assigneeMembership.publicRef, displayName: row.assigneeMembership.user.name } : null, custodian: row.custodianMembership ? { membershipRef: row.custodianMembership.publicRef, displayName: row.custodianMembership.user.name } : null, handedOutAt: row.handedOutAt?.toISOString() ?? null, returnedAt: row.returnedAt?.toISOString() ?? null, handoutCondition: row.handoutCondition, returnCondition: row.returnCondition, version: row.version }; }
function mapAsset(row, range) {
  const availability = assetAvailability({ asset: row, reservations: row.reservations || [], assignments: row.assignments || [], maintenance: row.maintenanceOrders || [], startsAt: range.startsAt, endsAt: range.endsAt });
  return { assetRef: row.assetRef, internalCode: row.internalCode, serialNumber: row.serialNumber, barcode: row.barcode, model: mapModel(row.assetModel), operationalStatus: row.operationalStatus, physicalCondition: row.physicalCondition, location: mapLocation(row.currentLocation), acquiredAt: row.acquiredAt?.toISOString().slice(0, 10) ?? null, acquisitionCost: row.acquisitionCost == null ? null : Number(row.acquisitionCost), replacementCost: row.replacementCost == null ? null : Number(row.replacementCost), currency: row.currency, usageHours: row.usageHours == null ? null : Number(row.usageHours), usageCycles: row.usageCycles == null ? null : Number(row.usageCycles), odometerKm: row.odometerKm == null ? null : Number(row.odometerKm), version: row.version, availability };
}
function rangeFromQuery(query = {}) { const startsAt = query.startsAt ? String(query.startsAt) : new Date().toISOString(); const endsAt = query.endsAt ? String(query.endsAt) : new Date(Date.parse(startsAt) + 60 * 60 * 1000).toISOString(); return { startsAt, endsAt }; }
const assetInclude = (range) => ({ assetModel: true, currentLocation: { include: { warehouse: true } }, reservations: { where: { status: "ACTIVE", startsAt: { lt: new Date(range.endsAt) }, endsAt: { gt: new Date(range.startsAt) } } }, assignments: { where: { status: "ACTIVE" } }, maintenanceOrders: { where: { status: { in: ["SCHEDULED", "IN_PROGRESS"] }, scheduledStart: { lt: new Date(range.endsAt) }, scheduledEnd: { gt: new Date(range.startsAt) } } } });
async function resolveAsset(tx, tenantId, assetRef, include = undefined) { const row = await tx.assetInstance.findFirst({ where: { tenantId, assetRef }, include }); if (!row) assetFail("ASSET_NOT_FOUND", 404); return row; }
async function resolveMembership(tx, tenantId, membershipRef) { if (!membershipRef) return null; const row = await tx.tenantMembership.findFirst({ where: { tenantId, publicRef: membershipRef, status: "ACTIVE", user: { status: "ACTIVE" }, tenant: { status: "ACTIVE" } }, select: { id: true, userId: true, publicRef: true, user: { select: { name: true } } } }); if (!row) assetFail("ASSET_NOT_FOUND", 404); return row; }
async function resolveLocation(tx, tenantId, locationRef) { if (!locationRef) return null; const row = await tx.materialLocation.findFirst({ where: { tenantId, locationRef, status: "ACTIVE", warehouse: { status: "ACTIVE" } }, select: { id: true, locationRef: true } }); if (!row) assetFail("ASSET_NOT_FOUND", 404); return row; }
async function resolveCase(tx, tenantId, caseRef) { if (!caseRef) return null; const row = await tx.pipelineCase.findFirst({ where: { tenantId, publicRef: caseRef }, select: { id: true } }); if (!row) assetFail("ASSET_NOT_FOUND", 404); return row; }
async function lockAsset(tx, tenantId, assetId) { await tx.$executeRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtextextended(${`${tenantId}:${assetId}:asset`}, 0))`); }

export async function listAssetModels(prisma, context, query = {}) {
  requirePermission(context, "assets:model:view");
  const rows = await prisma.assetModel.findMany({ where: { tenantId: context.tenantId, ...(query.status ? { status: String(query.status) } : {}), ...(query.resourceType ? { resourceType: String(query.resourceType) } : {}), ...(query.family ? { family: String(query.family) } : {}), ...(query.search ? { OR: [{ code: { contains: String(query.search), mode: "insensitive" } }, { name: { contains: String(query.search), mode: "insensitive" } }] } : {}) }, include: { _count: { select: { instances: true } } }, orderBy: [{ family: "asc" }, { code: "asc" }] });
  return Object.freeze(rows.map(mapModel));
}

export async function createAssetModel(prisma, context, raw) {
  requirePermission(context, "assets:model:manage"); const input = normalizeAssetModelCreate(raw);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const row = await tx.assetModel.create({ data: { tenantId: context.tenantId, code: input.code, name: input.name, description: input.description, family: input.family, resourceType: input.resourceType, serialPolicy: input.serialPolicy, identificationPolicy: input.identificationPolicy, capacity: input.capacity } }); return persist(tx, context, input, row.modelRef, mapModel(row), "ASSET_MODEL_CREATE", "AssetModel"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function listAssetInstances(prisma, context, query = {}) {
  requirePermission(context, "assets:instance:view"); const range = rangeFromQuery(query); const page = Math.max(1, Number(query.page) || 1); const pageSize = Math.min(100, Math.max(1, Number(query.pageSize) || 25));
  const where = { tenantId: context.tenantId, ...(query.status ? { operationalStatus: String(query.status) } : {}), ...(query.condition ? { physicalCondition: String(query.condition) } : {}), ...(query.family ? { assetModel: { family: String(query.family) } } : {}), ...(query.locationRef ? { currentLocation: { locationRef: String(query.locationRef) } } : {}), ...(query.search ? { OR: [{ internalCode: { contains: String(query.search), mode: "insensitive" } }, { serialNumber: { contains: String(query.search), mode: "insensitive" } }, { assetModel: { name: { contains: String(query.search), mode: "insensitive" } } }] } : {}) };
  const [rows, total] = await Promise.all([prisma.assetInstance.findMany({ where, include: assetInclude(range), orderBy: [{ updatedAt: "desc" }, { internalCode: "asc" }], skip: (page - 1) * pageSize, take: pageSize }), prisma.assetInstance.count({ where })]);
  const mapped = rows.map((row) => mapAsset(row, range)); const availability = String(query.availability || "ALL"); const items = availability === "AVAILABLE" ? mapped.filter((row) => row.availability.available) : availability === "UNAVAILABLE" ? mapped.filter((row) => !row.availability.available) : mapped;
  return Object.freeze({ page, pageSize, total, interval: range, items });
}

export async function getAssetInstance(prisma, context, assetRef, query = {}) {
  requirePermission(context, "assets:instance:view"); const range = rangeFromQuery(query);
  const row = await prisma.assetInstance.findFirst({ where: { tenantId: context.tenantId, assetRef }, include: { ...assetInclude(range), assignments: { include: { assigneeMembership: { include: { user: true } }, custodianMembership: { include: { user: true } } }, orderBy: { createdAt: "desc" }, take: 50 }, inspections: { orderBy: { inspectedAt: "desc" }, take: 50 }, incidents: { orderBy: { occurredAt: "desc" }, take: 50 }, historyEvents: { orderBy: { occurredAt: "desc" }, take: 100 }, costVersions: { orderBy: { validFrom: "desc" }, take: 50 }, maintenanceOrders: { orderBy: { scheduledStart: "desc" }, take: 50 }, reservations: { orderBy: { startsAt: "desc" }, take: 50 } } }); if (!row) assetFail("ASSET_NOT_FOUND", 404);
  return Object.freeze({ ...mapAsset(row, range), assignments: row.assignments.map(mapAssignment), reservations: row.reservations.map((item) => ({ reservationRef: item.reservationRef, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), status: item.status, operationalReference: item.operationalReference, version: item.version })), inspections: row.inspections.map((item) => ({ inspectionRef: item.inspectionRef, inspectionType: item.inspectionType, physicalCondition: item.physicalCondition, safeToUse: item.safeToUse, inspectedAt: item.inspectedAt.toISOString() })), incidents: row.incidents.map((item) => ({ incidentRef: item.incidentRef, incidentType: item.incidentType, severity: item.severity, status: item.status, resultingCondition: item.resultingCondition, occurredAt: item.occurredAt.toISOString() })), maintenance: row.maintenanceOrders.map((item) => ({ maintenanceRef: item.maintenanceRef, maintenanceType: item.maintenanceType, status: item.status, title: item.title, scheduledStart: item.scheduledStart.toISOString(), scheduledEnd: item.scheduledEnd.toISOString(), costAmount: item.costAmount == null ? null : Number(item.costAmount), currency: item.currency, version: item.version })), costs: row.costVersions.map((item) => ({ costRef: item.costRef, costType: item.costType, amount: Number(item.amount), currency: item.currency, temporalUnit: item.temporalUnit, validFrom: item.validFrom.toISOString(), validTo: item.validTo?.toISOString() ?? null, version: item.version })), history: row.historyEvents.map((item) => ({ eventRef: item.eventRef, eventType: item.eventType, referenceType: item.referenceType, occurredAt: item.occurredAt.toISOString() })) });
}

export async function createAssetInstance(prisma, context, raw) {
  requirePermission(context, "assets:instance:manage"); const input = normalizeAssetInstanceCreate(raw);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; await tx.$executeRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtextextended(${`${context.tenantId}:${input.internalCodePrefix}:asset-code`}, 0))`); const [model, location] = await Promise.all([tx.assetModel.findFirst({ where: { tenantId: context.tenantId, modelRef: input.modelRef, status: "ACTIVE" } }), resolveLocation(tx, context.tenantId, input.locationRef)]); if (!model) assetFail("ASSET_NOT_FOUND", 404); if (model.serialPolicy === "REQUIRED" && !input.serialNumber || model.serialPolicy === "NONE" && input.serialNumber) assetFail("ASSET_SERIAL_POLICY_CONFLICT", 409);
    await tx.$executeRaw(Prisma.sql`INSERT INTO "asset_code_counters" ("id", "tenant_id", "prefix", "next_value", "updated_at") VALUES (${crypto.randomUUID()}, ${context.tenantId}, ${input.internalCodePrefix}, 2, now()) ON CONFLICT ("tenant_id", "prefix") DO UPDATE SET "next_value" = "asset_code_counters"."next_value" + 1, "updated_at" = now()`);
    const counter = await tx.assetCodeCounter.findUniqueOrThrow({ where: { tenantId_prefix: { tenantId: context.tenantId, prefix: input.internalCodePrefix } } }); const sequence = Number(counter.nextValue) - 1; const internalCode = `${input.internalCodePrefix}-${String(sequence).padStart(6, "0")}`;
    const row = await tx.assetInstance.create({ data: { tenantId: context.tenantId, assetModelId: model.id, currentLocationId: location?.id, internalCode, serialNumber: input.serialNumber, barcode: input.barcode, physicalCondition: input.physicalCondition, operationalStatus: input.physicalCondition === "UNSAFE" ? "OUT_OF_SERVICE" : "AVAILABLE", acquiredAt: input.acquiredAt ? new Date(`${input.acquiredAt}T00:00:00.000Z`) : null, acquisitionCost: input.acquisitionCost, replacementCost: input.replacementCost, currency: input.currency } }); const result = { assetRef: row.assetRef, internalCode: row.internalCode, model: mapModel(model), operationalStatus: row.operationalStatus, physicalCondition: row.physicalCondition, version: row.version };
    await tx.assetHistoryEvent.create({ data: { tenantId: context.tenantId, assetInstanceId: row.id, eventType: "ASSET_CREATED", resultingState: result, referenceType: "ASSET", referenceRef: row.assetRef, ...actor(context) } }); return persist(tx, context, input, row.assetRef, result, "ASSET_INSTANCE_CREATE", "AssetInstance");
  });
}

export async function changeAssetState(prisma, context, assetRef, raw) {
  requirePermission(context, "assets:instance:manage"); const input = normalizeAssetStateChange(raw, assetRef);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const current = await resolveAsset(tx, context.tenantId, input.assetRef); await lockAsset(tx, context.tenantId, current.id); const location = await resolveLocation(tx, context.tenantId, input.locationRef); if (input.physicalCondition === "UNSAFE" && !["OUT_OF_SERVICE", "MAINTENANCE", "RETIRED"].includes(input.operationalStatus)) assetFail("ASSET_UNSAFE_STATUS_CONFLICT", 409); const changed = await tx.assetInstance.updateMany({ where: { tenantId: context.tenantId, id: current.id, version: input.expectedVersion }, data: { operationalStatus: input.operationalStatus, physicalCondition: input.physicalCondition, currentLocationId: location?.id, retiredAt: input.operationalStatus === "RETIRED" ? new Date() : null, version: { increment: 1 } } }); if (changed.count !== 1) assetFail("ASSET_VERSION_CONFLICT", 409); const result = { assetRef: current.assetRef, operationalStatus: input.operationalStatus, physicalCondition: input.physicalCondition, locationRef: location?.locationRef ?? null, version: current.version + 1 }; await tx.assetHistoryEvent.create({ data: { tenantId: context.tenantId, assetInstanceId: current.id, eventType: "STATE_CHANGED", previousState: { operationalStatus: current.operationalStatus, physicalCondition: current.physicalCondition }, resultingState: result, referenceType: "ASSET", referenceRef: current.assetRef, ...actor(context) } }); return persist(tx, context, input, current.assetRef, result, "ASSET_STATE_CHANGE", "AssetInstance"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function createAssetReservation(prisma, context, raw) {
  requirePermission(context, "assets:reservation:manage"); const input = normalizeAssetReservation(raw);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const asset = await resolveAsset(tx, context.tenantId, input.assetRef); await lockAsset(tx, context.tenantId, asset.id); if (["MAINTENANCE", "OUT_OF_SERVICE", "LOST", "RETIRED"].includes(asset.operationalStatus) || asset.physicalCondition === "UNSAFE") assetFail("ASSET_UNAVAILABLE", 409); const pipelineCase = await resolveCase(tx, context.tenantId, input.caseRef); const row = await tx.assetReservation.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, pipelineCaseId: pipelineCase?.id, operationalReference: input.operationalReference, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), ...actor(context) } }); const result = { reservationRef: row.reservationRef, assetRef: asset.assetRef, startsAt: row.startsAt.toISOString(), endsAt: row.endsAt.toISOString(), status: row.status, version: row.version }; await tx.assetHistoryEvent.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, eventType: "RESERVED", resultingState: result, referenceType: "RESERVATION", referenceRef: row.reservationRef, ...actor(context) } }); return persist(tx, context, input, row.reservationRef, result, "ASSET_RESERVE", "AssetReservation"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function createAssetAssignment(prisma, context, raw) {
  requirePermission(context, "assets:assignment:manage"); const input = normalizeAssetAssignment(raw);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const asset = await resolveAsset(tx, context.tenantId, input.assetRef); await lockAsset(tx, context.tenantId, asset.id); const [reservation, pipelineCase, assignee, custodian, origin, destination] = await Promise.all([input.reservationRef ? tx.assetReservation.findFirst({ where: { tenantId: context.tenantId, reservationRef: input.reservationRef, assetInstanceId: asset.id, status: "ACTIVE" } }) : null, resolveCase(tx, context.tenantId, input.caseRef), resolveMembership(tx, context.tenantId, input.assigneeRef), resolveMembership(tx, context.tenantId, input.custodianRef), resolveLocation(tx, context.tenantId, input.originLocationRef), resolveLocation(tx, context.tenantId, input.destinationLocationRef)]); if (input.reservationRef && !reservation) assetFail("ASSET_NOT_FOUND", 404); const row = await tx.assetAssignment.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, reservationId: reservation?.id, pipelineCaseId: pipelineCase?.id, assigneeMembershipId: assignee?.id, assigneeUserId: assignee?.userId, custodianMembershipId: custodian?.id, custodianUserId: custodian?.userId, operationalReference: input.operationalReference, originLocationId: origin?.id, destinationLocationId: destination?.id, status: "PLANNED", ...actor(context) } }); const result = { assignmentRef: row.assignmentRef, assetRef: asset.assetRef, status: row.status, assigneeRef: assignee?.publicRef ?? null, custodianRef: custodian?.publicRef ?? null, version: row.version }; await tx.assetHistoryEvent.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, eventType: "ASSIGNMENT_PLANNED", resultingState: result, referenceType: "ASSIGNMENT", referenceRef: row.assignmentRef, ...actor(context) } }); return persist(tx, context, input, row.assignmentRef, result, "ASSET_ASSIGN", "AssetAssignment"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function handoutAsset(prisma, context, raw) {
  requirePermission(context, "assets:assignment:manage"); const input = normalizeAssetHandout(raw);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const current = await tx.assetAssignment.findFirst({ where: { tenantId: context.tenantId, assignmentRef: input.assignmentRef }, include: { assetInstance: true } }); if (!current) assetFail("ASSET_NOT_FOUND", 404); await lockAsset(tx, context.tenantId, current.assetInstanceId); if (current.status !== "PLANNED" || !current.custodianMembershipId) assetFail("ASSET_ASSIGNMENT_STATE_CONFLICT", 409); if (input.condition === "UNSAFE") assetFail("ASSET_UNAVAILABLE", 409); const destination = await resolveLocation(tx, context.tenantId, input.destinationLocationRef); const changed = await tx.assetAssignment.updateMany({ where: { tenantId: context.tenantId, id: current.id, version: input.expectedVersion, status: "PLANNED" }, data: { status: "ACTIVE", handedOutAt: new Date(input.handedOutAt), handoutCondition: input.condition, destinationLocationId: destination?.id, version: { increment: 1 } } }); if (changed.count !== 1) assetFail("ASSET_VERSION_CONFLICT", 409); await tx.assetInstance.update({ where: { id: current.assetInstanceId }, data: { operationalStatus: "IN_USE", physicalCondition: input.condition, currentLocationId: destination?.id, version: { increment: 1 } } }); if (current.reservationId) await tx.assetReservation.update({ where: { id: current.reservationId }, data: { status: "FULFILLED", version: { increment: 1 } } }); const result = { assignmentRef: current.assignmentRef, assetRef: current.assetInstance.assetRef, status: "ACTIVE", handedOutAt: input.handedOutAt, version: current.version + 1 }; await tx.assetHistoryEvent.create({ data: { tenantId: context.tenantId, assetInstanceId: current.assetInstanceId, eventType: "HANDED_OUT", resultingState: result, referenceType: "ASSIGNMENT", referenceRef: current.assignmentRef, ...actor(context) } }); return persist(tx, context, input, current.assignmentRef, result, "ASSET_HANDOUT", "AssetAssignment"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function returnAsset(prisma, context, raw) {
  requirePermission(context, "assets:assignment:manage"); const input = normalizeAssetReturn(raw);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const current = await tx.assetAssignment.findFirst({ where: { tenantId: context.tenantId, assignmentRef: input.assignmentRef }, include: { assetInstance: true } }); if (!current) assetFail("ASSET_NOT_FOUND", 404); await lockAsset(tx, context.tenantId, current.assetInstanceId); const location = await resolveLocation(tx, context.tenantId, input.locationRef); const changed = await tx.assetAssignment.updateMany({ where: { tenantId: context.tenantId, id: current.id, version: input.expectedVersion, status: "ACTIVE" }, data: { status: "RETURNED", returnedAt: new Date(input.returnedAt), returnCondition: input.condition, destinationLocationId: location.id, version: { increment: 1 } } }); if (changed.count !== 1) assetFail("ASSET_VERSION_CONFLICT", 409); const unsafe = input.condition === "UNSAFE"; const damaged = ["DAMAGED", "UNSAFE"].includes(input.condition); await tx.assetInstance.update({ where: { id: current.assetInstanceId }, data: { operationalStatus: unsafe ? "OUT_OF_SERVICE" : damaged ? "MAINTENANCE" : "AVAILABLE", physicalCondition: input.condition, currentLocationId: location.id, version: { increment: 1 } } }); let incidentRef = null; if (damaged) { const incident = await tx.assetIncident.create({ data: { tenantId: context.tenantId, assetInstanceId: current.assetInstanceId, assignmentId: current.id, incidentType: "DAMAGE", severity: unsafe ? "CRITICAL" : "HIGH", resultingCondition: input.condition, description: input.damageDescription, evidenceRefs: input.evidenceRefs, occurredAt: new Date(input.returnedAt), ...actor(context) } }); incidentRef = incident.incidentRef; }
    const result = { assignmentRef: current.assignmentRef, assetRef: current.assetInstance.assetRef, status: "RETURNED", condition: input.condition, incidentRef, version: current.version + 1 }; await tx.assetHistoryEvent.create({ data: { tenantId: context.tenantId, assetInstanceId: current.assetInstanceId, eventType: damaged ? "RETURNED_WITH_DAMAGE" : "RETURNED", resultingState: result, referenceType: "ASSIGNMENT", referenceRef: current.assignmentRef, ...actor(context) } }); return persist(tx, context, input, current.assignmentRef, result, "ASSET_RETURN", "AssetAssignment"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function createAssetInspection(prisma, context, raw) {
  requirePermission(context, "assets:inspection:perform"); const input = normalizeAssetInspection(raw);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const asset = await resolveAsset(tx, context.tenantId, input.assetRef); const [assignment, location] = await Promise.all([input.assignmentRef ? tx.assetAssignment.findFirst({ where: { tenantId: context.tenantId, assignmentRef: input.assignmentRef, assetInstanceId: asset.id } }) : null, resolveLocation(tx, context.tenantId, input.locationRef)]); if (input.assignmentRef && !assignment) assetFail("ASSET_NOT_FOUND", 404); const row = await tx.assetInspection.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, assignmentId: assignment?.id, locationId: location?.id, inspectionType: input.inspectionType, physicalCondition: input.physicalCondition, safeToUse: input.safeToUse, notes: input.notes, evidenceRefs: input.evidenceRefs, inspectedAt: new Date(input.inspectedAt), ...actor(context) } }); if (!input.safeToUse || input.physicalCondition === "UNSAFE") await tx.assetInstance.update({ where: { id: asset.id }, data: { physicalCondition: "UNSAFE", operationalStatus: "OUT_OF_SERVICE", version: { increment: 1 } } }); const result = { inspectionRef: row.inspectionRef, assetRef: asset.assetRef, inspectionType: row.inspectionType, physicalCondition: row.physicalCondition, safeToUse: row.safeToUse, inspectedAt: row.inspectedAt.toISOString() }; await tx.assetHistoryEvent.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, eventType: "INSPECTED", resultingState: result, referenceType: "INSPECTION", referenceRef: row.inspectionRef, ...actor(context) } }); return persist(tx, context, input, row.inspectionRef, result, "ASSET_INSPECTION", "AssetInspection"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function createAssetIncident(prisma, context, raw) {
  requirePermission(context, "assets:incident:manage"); const input = normalizeAssetIncident(raw);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const asset = await resolveAsset(tx, context.tenantId, input.assetRef); const assignment = input.assignmentRef ? await tx.assetAssignment.findFirst({ where: { tenantId: context.tenantId, assignmentRef: input.assignmentRef, assetInstanceId: asset.id } }) : null; const inspection = input.inspectionRef ? await tx.assetInspection.findFirst({ where: { tenantId: context.tenantId, inspectionRef: input.inspectionRef, assetInstanceId: asset.id } }) : null; if (input.assignmentRef && !assignment || input.inspectionRef && !inspection) assetFail("ASSET_NOT_FOUND", 404); const row = await tx.assetIncident.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, assignmentId: assignment?.id, inspectionId: inspection?.id, incidentType: input.incidentType, severity: input.severity, resultingCondition: input.resultingCondition, description: input.description, evidenceRefs: input.evidenceRefs, occurredAt: new Date(input.occurredAt), ...actor(context) } }); const unsafe = input.resultingCondition === "UNSAFE" || input.incidentType === "LOSS"; if (unsafe) await tx.assetInstance.update({ where: { id: asset.id }, data: { physicalCondition: input.resultingCondition || asset.physicalCondition, operationalStatus: input.incidentType === "LOSS" ? "LOST" : "OUT_OF_SERVICE", version: { increment: 1 } } }); const result = { incidentRef: row.incidentRef, assetRef: asset.assetRef, incidentType: row.incidentType, severity: row.severity, status: row.status, resultingCondition: row.resultingCondition }; await tx.assetHistoryEvent.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, eventType: "INCIDENT_REPORTED", resultingState: result, referenceType: "INCIDENT", referenceRef: row.incidentRef, ...actor(context) } }); return persist(tx, context, input, row.incidentRef, result, "ASSET_INCIDENT", "AssetIncident"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function createAssetMaintenance(prisma, context, raw) {
  requirePermission(context, "assets:maintenance:manage"); const input = normalizeAssetMaintenance(raw);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const asset = await resolveAsset(tx, context.tenantId, input.assetRef); await lockAsset(tx, context.tenantId, asset.id); const incident = input.incidentRef ? await tx.assetIncident.findFirst({ where: { tenantId: context.tenantId, incidentRef: input.incidentRef, assetInstanceId: asset.id } }) : null; if (input.incidentRef && !incident) assetFail("ASSET_NOT_FOUND", 404); const row = await tx.assetMaintenanceOrder.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, incidentId: incident?.id, maintenanceType: input.maintenanceType, title: input.title, notes: input.notes, scheduledStart: new Date(input.scheduledStart), scheduledEnd: new Date(input.scheduledEnd), costAmount: input.costAmount, currency: input.currency, ...actor(context) } }); const startsNow = Date.parse(input.scheduledStart) <= Date.now() && Date.parse(input.scheduledEnd) > Date.now(); if (startsNow) await tx.assetInstance.update({ where: { id: asset.id }, data: { operationalStatus: "MAINTENANCE", version: { increment: 1 } } }); const result = { maintenanceRef: row.maintenanceRef, assetRef: asset.assetRef, maintenanceType: row.maintenanceType, status: row.status, scheduledStart: row.scheduledStart.toISOString(), scheduledEnd: row.scheduledEnd.toISOString(), costAmount: row.costAmount == null ? null : Number(row.costAmount), currency: row.currency, version: row.version }; await tx.assetHistoryEvent.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, eventType: "MAINTENANCE_SCHEDULED", resultingState: result, referenceType: "MAINTENANCE", referenceRef: row.maintenanceRef, ...actor(context) } }); return persist(tx, context, input, row.maintenanceRef, result, "ASSET_MAINTENANCE_CREATE", "AssetMaintenanceOrder"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function createAssetCostVersion(prisma, context, raw) {
  requirePermission(context, "assets:instance:manage"); const input = normalizeAssetCostVersion(raw);
  return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const asset = await resolveAsset(tx, context.tenantId, input.assetRef); await lockAsset(tx, context.tenantId, asset.id); const current = await tx.assetCostVersion.findFirst({ where: { tenantId: context.tenantId, assetInstanceId: asset.id, costType: input.costType, validTo: null }, orderBy: { version: "desc" } }); const validFrom = new Date(input.validFrom); if (current && current.validFrom >= validFrom) assetFail("ASSET_COST_VERSION_CONFLICT", 409); if (current) await tx.assetCostVersion.update({ where: { id: current.id }, data: { validTo: validFrom } }); const row = await tx.assetCostVersion.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, costType: input.costType, amount: input.amount, currency: input.currency, temporalUnit: input.temporalUnit, validFrom, version: (current?.version ?? 0) + 1, source: input.source, createdByMembershipId: context.membershipId, createdByUserId: context.userId } }); const result = { costRef: row.costRef, assetRef: asset.assetRef, costType: row.costType, amount: Number(row.amount), currency: row.currency, temporalUnit: row.temporalUnit, validFrom: row.validFrom.toISOString(), version: row.version }; await tx.assetHistoryEvent.create({ data: { tenantId: context.tenantId, assetInstanceId: asset.id, eventType: "COST_VERSION_CREATED", resultingState: result, referenceType: "COST", referenceRef: row.costRef, ...actor(context) } }); return persist(tx, context, input, row.costRef, result, "ASSET_COST_VERSION_CREATE", "AssetCostVersion"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function listExternalOffers(prisma, context) { requirePermission(context, "assets:external:view"); const rows = await prisma.externalResourceOffer.findMany({ where: { tenantId: context.tenantId }, include: { assetModel: true, reservations: { where: { status: { in: ["REQUESTED", "CONFIRMED"] } } } }, orderBy: { updatedAt: "desc" } }); return Object.freeze(rows.map((row) => ({ offerRef: row.offerRef, provider: { reference: row.providerReference, displayName: row.providerNameSnapshot }, model: row.assetModel ? mapModel(row.assetModel) : null, resourceDescription: row.resourceDescription, capacity: row.capacity, rate: row.rateAmount == null ? null : { amount: Number(row.rateAmount), currency: row.currency, temporalUnit: row.temporalUnit }, validity: { from: row.validFrom?.toISOString() ?? null, to: row.validTo?.toISOString() ?? null }, availabilityStatus: row.availabilityStatus, contractualReference: row.contractualReference, status: row.status, activeReservations: row.reservations.length, version: row.version }))); }

export async function createExternalOffer(prisma, context, raw) { requirePermission(context, "assets:external:manage"); const input = normalizeExternalOffer(raw); return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const model = input.modelRef ? await tx.assetModel.findFirst({ where: { tenantId: context.tenantId, modelRef: input.modelRef, status: "ACTIVE" } }) : null; if (input.modelRef && !model) assetFail("ASSET_NOT_FOUND", 404); const row = await tx.externalResourceOffer.create({ data: { tenantId: context.tenantId, assetModelId: model?.id, providerReference: input.providerReference, providerNameSnapshot: input.providerName, resourceDescription: input.resourceDescription, capacity: input.capacity, rateAmount: input.rateAmount, currency: input.currency, temporalUnit: input.temporalUnit, validFrom: input.validFrom ? new Date(input.validFrom) : null, validTo: input.validTo ? new Date(input.validTo) : null, availabilityStatus: input.availabilityStatus, termsSnapshot: input.terms, contractualReference: input.contractualReference } }); const result = { offerRef: row.offerRef, resourceDescription: row.resourceDescription, availabilityStatus: row.availabilityStatus, rate: row.rateAmount == null ? null : { amount: Number(row.rateAmount), currency: row.currency, temporalUnit: row.temporalUnit }, version: row.version }; return persist(tx, context, input, row.offerRef, result, "EXTERNAL_OFFER_CREATE", "ExternalResourceOffer"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }

export async function createExternalReservation(prisma, context, raw) { requirePermission(context, "assets:external:manage"); const input = normalizeExternalReservation(raw); return prisma.$transaction(async (tx) => { const prior = await replay(tx, context, input); if (prior) return prior; const offer = await tx.externalResourceOffer.findFirst({ where: { tenantId: context.tenantId, offerRef: input.offerRef, status: "ACTIVE" } }); if (!offer) assetFail("ASSET_NOT_FOUND", 404); await tx.$executeRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtextextended(${`${context.tenantId}:${offer.id}:external-offer`}, 0))`); if (offer.availabilityStatus !== "AVAILABLE") assetFail("EXTERNAL_RESOURCE_UNCONFIRMED", 409); const pipelineCase = await resolveCase(tx, context.tenantId, input.caseRef); const overlaps = await tx.externalResourceReservation.aggregate({ where: { tenantId: context.tenantId, offerId: offer.id, status: { in: ["REQUESTED", "CONFIRMED"] }, startsAt: { lt: new Date(input.endsAt) }, endsAt: { gt: new Date(input.startsAt) } }, _sum: { quantity: true } }); const declared = Number(offer.capacity?.quantity || 1); if (Number(overlaps._sum.quantity || 0) + input.quantity > declared) assetFail("EXTERNAL_RESOURCE_UNAVAILABLE", 409); const row = await tx.externalResourceReservation.create({ data: { tenantId: context.tenantId, offerId: offer.id, pipelineCaseId: pipelineCase?.id, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), quantity: input.quantity, agreedAmount: input.agreedAmount, currency: input.currency, operationalReference: input.operationalReference, ...actor(context) } }); const result = { reservationRef: row.reservationRef, offerRef: offer.offerRef, startsAt: row.startsAt.toISOString(), endsAt: row.endsAt.toISOString(), quantity: row.quantity, agreedAmount: row.agreedAmount == null ? null : Number(row.agreedAmount), currency: row.currency, status: row.status, version: row.version }; return persist(tx, context, input, row.reservationRef, result, "EXTERNAL_RESERVATION_CREATE", "ExternalResourceReservation"); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }

export function mapToolsEquipmentDatabaseError(error) {
  if (error instanceof ToolsEquipmentError) return error;
  const message = String(error?.message || "");
  if (message.includes("asset_reservations_no_active_overlap") || message.includes("ASSET_MAINTENANCE_CONFLICT") || message.includes("ASSET_RESERVATION_CONFLICT")) return new ToolsEquipmentError("ASSET_INTERVAL_CONFLICT", 409);
  if (message.includes("asset_assignments_one_active_per_instance_key")) return new ToolsEquipmentError("ASSET_CUSTODY_CONFLICT", 409);
  if (error?.code === "P2002") return new ToolsEquipmentError("ASSET_DUPLICATE", 409);
  return error;
}
