import { expect, test, type Page } from "@playwright/test";
const REF = { membership: "048f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", material: "148f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", unit: "248f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", warehouse: "348f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", locationA: "448f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", locationB: "548f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", reservation: "648f6d8f-8d11-4f39-8a2d-1b6c7e8f9012" };
const permissions = ["inventory:catalog:view", "inventory:catalog:manage", "inventory:stock:view", "inventory:stock:receive", "inventory:stock:transfer", "inventory:stock:issue", "inventory:stock:adjust", "inventory:reservation:manage", "inventory:purchase:request", "inventory:recipes:view", "inventory:recipes:manage"];
async function session(page: Page, deny = false) {
  await page.addInitScript(({ membership }) => { localStorage.setItem("osi-plus.token", "synthetic.materials.token"); localStorage.setItem("osi-plus.session", JSON.stringify({ name: "Almacén sintético", role: "A", membershipRef: membership, memberships: [{ membershipRef: membership, tenantName: "Tenant sintético", role: "A", preferred: true }] })); }, { membership: REF.membership });
  await page.route("**/api/auth/me", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, user: { name: "Almacén sintético", role: "A", status: "ACTIVE", permissions: deny ? [] : permissions, deniedPermissions: deny ? ["inventory:catalog:view", "inventory:stock:view"] : [], membership: { membershipRef: REF.membership, tenantName: "Tenant sintético", role: "A" }, memberships: [{ membershipRef: REF.membership, tenantName: "Tenant sintético", role: "A", preferred: true }] } }) }));
}
async function api(page: Page) {
  let physical = 100; let reserved = 30; let reservationStatus = "RESERVED"; let reservationVersion = 1; const posts: string[] = [];
  await page.route("**/api/materials/catalog", (route) => { const assigned = reservationStatus === "ASSIGNED" ? reserved : 0; const committed = reservationStatus === "RESERVED" ? reserved : 0; return route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, data: { page: 1, pageSize: 25, total: 1, items: [{ materialRef: REF.material, code: "BOX-S", name: "Caja pequeña", description: "Caja de empaque", family: "CAJAS", subfamily: null, baseUnit: { unitRef: REF.unit, code: "UND", name: "Unidad" }, purchaseUnit: { unitRef: REF.unit, code: "UND", name: "Unidad" }, consumptionUnit: { unitRef: REF.unit, code: "UND", name: "Unidad" }, technicalFlags: ["CONSUMABLE"], dimensionPolicy: {}, lotTrackingEnabled: false, minimumStock: 10, maximumStock: 200, reorderPoint: 30, status: "ACTIVE", version: 1, currentCost: { costVersionRef: REF.unit, amount: 42.5, currency: "DOP", unitRef: REF.unit, unitCode: "UND", validFrom: "2026-09-04T00:00:00.000Z", version: 1 }, inventory: { physical, reserved: committed, assigned, available: physical - committed - assigned, byWarehouse: [{ warehouseRef: REF.warehouse, physical, reserved: committed, assigned, available: physical - committed - assigned }] } }] } }) }); });
  await page.route("**/api/materials/movements", async (route) => { if (route.request().method() === "POST") { posts.push(route.request().postDataJSON().movementType); physical += route.request().postDataJSON().movementType === "RECEIPT" ? Number(route.request().postDataJSON().quantity) : 0; return route.fulfill({ status: 201, contentType: "application/json", body: JSON.stringify({ ok: true, data: { transactionRef: crypto.randomUUID() } }) }); } return route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, data: { page: 1, pageSize: 25, items: [{ movementRef: crypto.randomUUID(), transactionRef: crypto.randomUUID(), movementType: "RECEIPT", material: { materialRef: REF.material, code: "BOX-S", name: "Caja pequeña" }, location: { locationRef: REF.locationA, code: "BIN-01", name: "Posición 01", warehouse: "Principal" }, quantity: 100, reasonCode: "PURCHASE_RECEIPT", occurredAt: "2026-09-04T12:00:00.000Z" }] } }) }); });
  await page.route("**/api/materials/reservations/assign", async (route) => { posts.push("ASSIGN"); reservationStatus = "ASSIGNED"; reservationVersion += 1; return route.fulfill({ status: 201, contentType: "application/json", body: JSON.stringify({ ok: true, data: { reservationRef: REF.reservation, status: reservationStatus, version: reservationVersion } }) }); });
  await page.route("**/api/materials/reservations/release", async (route) => { posts.push("RELEASE"); reserved = 0; reservationStatus = "RELEASED"; reservationVersion += 1; return route.fulfill({ status: 201, contentType: "application/json", body: JSON.stringify({ ok: true, data: { reservationRef: REF.reservation, status: reservationStatus, version: reservationVersion } }) }); });
  await page.route("**/api/materials/reservations", async (route) => { if (route.request().method() === "POST") { posts.push("RESERVE"); reserved += Number(route.request().postDataJSON().quantity); reservationStatus = "RESERVED"; reservationVersion = 1; return route.fulfill({ status: 201, contentType: "application/json", body: JSON.stringify({ ok: true, data: { reservationRef: REF.reservation, status: reservationStatus, version: reservationVersion } }) }); } return route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, data: [{ reservationRef: REF.reservation, material: { materialRef: REF.material, code: "BOX-S", name: "Caja pequeña" }, location: { locationRef: REF.locationA, code: "BIN-01", name: "Posición 01" }, quantity: reserved || 30, status: reservationStatus, version: reservationVersion, createdAt: "2026-09-04T12:00:00.000Z" }] }) }); });
  await page.route("**/api/materials/warehouses", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, data: [{ warehouseRef: REF.warehouse, code: "MAIN", name: "Principal", status: "ACTIVE", version: 1, locations: [{ locationRef: REF.locationA, code: "BIN-01", name: "Posición 01", kind: "BIN", depth: 2, path: "ROOT/A/BIN-01", status: "ACTIVE" }, { locationRef: REF.locationB, code: "BIN-02", name: "Posición 02", kind: "BIN", depth: 2, path: "ROOT/A/BIN-02", status: "ACTIVE" }] }] }) }));
  await page.route("**/api/materials/recipes", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, data: [{ recipeRef: REF.warehouse, code: "LOCAL-BOX", name: "Caja local", status: "ACTIVE", versions: [{ recipeVersionRef: REF.locationB, version: 1, status: "ACTIVE", lines: [{ materialRef: REF.material }] }] }] }) }));
  await page.route("**/api/materials/requirements", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, data: [{ requirementRef: REF.reservation, surveyPublicationRef: REF.locationA, recipe: { recipeRef: REF.warehouse, recipeVersionRef: REF.locationB, code: "LOCAL-BOX", version: 1 }, revision: 1, status: "CURRENT", createdAt: "2026-09-04T12:00:00.000Z", items: [{ materialRef: REF.material, code: "BOX-S", name: "Caja pequeña", quantity: 5, unit: { unitRef: REF.unit, code: "UND" } }] }] }) }));
  return posts;
}
test("catálogo, detalle y operaciones compactas", async ({ page }, testInfo) => {
  await session(page); const posts = await api(page); await page.goto("/materials"); await expect(page.getByRole("heading", { name: "Materiales e Inventario" })).toBeVisible(); await expect(page.getByText("Caja pequeña").first()).toBeVisible();
  await page.getByPlaceholder("Código o material").fill("BOX-S"); await page.getByLabel("Filtrar por estado").selectOption("ACTIVE"); await page.getByLabel("Filtrar por almacén").selectOption(REF.warehouse); await page.getByLabel("Filtrar por disponibilidad").selectOption("AVAILABLE"); await page.getByText("Caja pequeña").first().click(); await expect(page.getByText("Caja de empaque")).toBeVisible();
  await page.getByRole("button", { name: "Recepción" }).click(); await expect(page.getByRole("dialog")).toBeVisible(); await page.getByRole("button", { name: "Confirmar" }).click(); await expect.poll(() => posts.includes("RECEIPT")).toBeTruthy();
  await page.getByText("Caja pequeña").first().click(); await page.getByRole("button", { name: "Transferir" }).click(); await page.getByRole("button", { name: "Confirmar" }).click(); await expect.poll(() => posts.includes("TRANSFER_OUT")).toBeTruthy();
  await page.getByText("Caja pequeña").first().click(); await page.getByRole("button", { name: "Reservar" }).click(); await page.getByRole("button", { name: "Confirmar" }).click(); await expect.poll(() => posts.includes("RESERVE")).toBeTruthy();
  await page.getByRole("button", { name: "Movimientos" }).click(); await expect(page.getByText("Ledger append-only")).toBeVisible(); await page.getByRole("button", { name: "Reservas" }).click(); await expect(page.getByText("Reservas separadas del stock físico")).toBeVisible(); await page.getByRole("button", { name: "Asignar" }).click(); await expect.poll(() => posts.includes("ASSIGN")).toBeTruthy(); await page.getByRole("button", { name: "Liberar" }).click(); await expect.poll(() => posts.includes("RELEASE")).toBeTruthy(); await page.getByRole("button", { name: "Recetas" }).click(); await expect(page.getByText(/sin selección manual desde Survey/i)).toBeVisible(); await expect(page.getByText("Caja local")).toBeVisible(); await page.getByRole("button", { name: "Necesidades Survey" }).click(); await expect(page.getByText(/snapshots inmutables/i)).toBeVisible(); await expect(page.getByText("5 UND")).toBeVisible();
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth); expect(overflow, `${testInfo.project.name} no debe tener overflow`).toBe(false);
});
test("deny bloquea antes del lazy y de la API", async ({ page }) => {
  await session(page, true); let materialRequests = 0; await page.route("**/api/materials/**", (route) => { materialRequests += 1; return route.abort(); }); await page.goto("/materials"); await expect(page.getByRole("heading", { name: "No puedes abrir esta aplicación" })).toBeVisible(); await expect(page.getByText("403 · Acceso no autorizado")).toBeVisible(); expect(materialRequests).toBe(0); const chunks = await page.evaluate(() => performance.getEntriesByType("resource").map((entry) => entry.name).filter((name) => name.includes("MaterialsInventoryApp"))); expect(chunks).toHaveLength(0);
});
