import { useCallback, useEffect, useMemo, useState } from "react";
import { CircleDollarSign, RefreshCw, ShieldCheck } from "lucide-react";
import type { CostingUiAccess } from "./access";
import { costingApi, type CostingRate, type CostingRule } from "./api";

const FAMILIES = ["LABOR", "TRANSPORT", "MATERIAL", "CRATING", "ASSET", "TRAVEL", "THIRD_PARTY", "FREIGHT", "CUSTOMS", "PERMIT", "ADDITIONAL", "RISK", "CURRENCY_COMPENSATION"];
type Props = Readonly<{ authorization?: string; access: CostingUiAccess; onUnauthorized(): void }>;

const EMPTY_RULE = { family: "LABOR", code: "", name: "", classification: "PR", source: "ADMIN", unitCost: "", currency: "DOP", minimumMarginBps: "2000", recommendedMarginBps: "3000" };
const EMPTY_RATE = { baseCurrency: "USD", quoteCurrency: "DOP", rate: "", source: "Administración", effectiveAt: new Date().toISOString().slice(0, 16) };

export default function CostingRulesAdmin({ authorization, access, onUnauthorized }: Props) {
  const [section, setSection] = useState<"RULES" | "RATES">("RULES");
  const [family, setFamily] = useState("ALL");
  const [rules, setRules] = useState<readonly CostingRule[]>([]);
  const [rates, setRates] = useState<readonly CostingRate[]>([]);
  const [ruleDraft, setRuleDraft] = useState<typeof EMPTY_RULE | null>(null);
  const [rateDraft, setRateDraft] = useState<typeof EMPTY_RATE | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => {
    setBusy(true); setError(null);
    try { const [nextRules, nextRates] = await Promise.all([costingApi.rules(authorization), costingApi.rates(authorization)]); setRules(nextRules); setRates(nextRates); }
    catch (cause) { const message = cause instanceof Error ? cause.message : "COSTING_REQUEST_FAILED"; if (message.includes("UNAUTHORIZED")) onUnauthorized(); else setError(message); }
    finally { setBusy(false); }
  }, [authorization, onUnauthorized]);
  useEffect(() => { void load(); }, [load]);
  const visibleRules = useMemo(() => family === "ALL" ? rules : rules.filter((row) => row.family === family), [family, rules]);
  const saveRule = async (event: React.FormEvent) => {
    event.preventDefault(); if (!ruleDraft) return; setBusy(true); setError(null);
    try { await costingApi.versionRule(authorization, { seriesRef: null, family: ruleDraft.family, code: ruleDraft.code, name: ruleDraft.name, classification: ruleDraft.classification, source: ruleDraft.source, priority: 100, specificity: 0, conditions: {}, unitCost: ruleDraft.unitCost || null, currency: ruleDraft.currency, minimumMarginBps: ruleDraft.classification === "PR" ? Number(ruleDraft.minimumMarginBps) : null, recommendedMarginBps: ruleDraft.classification === "PR" ? Number(ruleDraft.recommendedMarginBps) : null, result: { unit: "UNIT" }, state: "ACTIVE", validFrom: new Date().toISOString(), validTo: null }); setRuleDraft(null); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "COSTING_REQUEST_FAILED"); } finally { setBusy(false); }
  };
  const saveRate = async (event: React.FormEvent) => {
    event.preventDefault(); if (!rateDraft) return; setBusy(true); setError(null);
    try { await costingApi.versionRate(authorization, { seriesRef: null, baseCurrency: rateDraft.baseCurrency, quoteCurrency: rateDraft.quoteCurrency, rate: rateDraft.rate, source: rateDraft.source, state: "ACTIVE", effectiveAt: new Date(rateDraft.effectiveAt).toISOString(), validTo: null }); setRateDraft(null); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "COSTING_REQUEST_FAILED"); } finally { setBusy(false); }
  };
  if (!access.canRulesView) return null;
  return <section className="mt-7 border-t pt-5" data-testid="costing-rules-admin"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-indigo-600">Costing</p><h2 className="text-lg font-black text-slate-950">Autoridad económica versionada</h2><p className="text-xs text-slate-500">Márgenes, personal, transporte, riesgos, monedas y reglas económicas.</p></div><div className="flex gap-2"><button type="button" onClick={() => setSection("RULES")} className={`rounded-lg px-3 py-2 text-xs font-bold ${section === "RULES" ? "bg-[#003366] text-white" : "border bg-white"}`}>Reglas</button><button type="button" onClick={() => setSection("RATES")} className={`rounded-lg px-3 py-2 text-xs font-bold ${section === "RATES" ? "bg-[#003366] text-white" : "border bg-white"}`}>Monedas</button><button type="button" aria-label="Actualizar Costing" disabled={busy} onClick={() => void load()} className="rounded-lg border bg-white p-2"><RefreshCw className="h-4 w-4" /></button></div></header>{error && <p role="alert" className="mt-3 border border-red-200 bg-red-50 p-3 text-xs text-red-800">{error}</p>}
    {section === "RULES" && <><div className="mt-3 flex flex-wrap items-center gap-2"><select aria-label="Familia económica" value={family} onChange={(event) => setFamily(event.target.value)} className="rounded-lg border px-3 py-2 text-xs"><option value="ALL">Todas las familias</option>{FAMILIES.map((value) => <option key={value}>{value}</option>)}</select>{access.canRulesManage && <button type="button" onClick={() => setRuleDraft({ ...EMPTY_RULE })} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Nueva regla económica</button>}</div><div className="mt-3 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{["Familia", "Regla", "Clase", "Costo", "Margen mín./rec.", "Fuente", "Versión", "Estado"].map((label) => <th key={label} className="border-b px-3 py-2">{label}</th>)}</tr></thead><tbody>{visibleRules.map((row) => <tr key={row.ruleRef} className="border-b last:border-0"><td className="px-3 py-2 font-bold">{row.family}</td><td className="px-3 py-2"><strong>{row.name}</strong><span className="block text-[10px] text-slate-500">{row.code}</span></td><td className="px-3 py-2">{row.classification}</td><td className="px-3 py-2">{row.unitCost == null ? "Derivado" : `${row.currency} ${row.unitCost}`}</td><td className="px-3 py-2">{row.minimumMarginBps == null ? "No aplica" : `${row.minimumMarginBps / 100}% / ${(row.recommendedMarginBps || 0) / 100}%`}</td><td className="px-3 py-2">{row.source}</td><td className="px-3 py-2">v{row.version}</td><td className="px-3 py-2"><span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-bold">{row.state}</span></td></tr>)}</tbody></table></div></>}
    {section === "RATES" && <><div className="mt-3 flex justify-end">{access.canRulesManage && <button type="button" onClick={() => setRateDraft({ ...EMPTY_RATE })} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Nueva tasa</button>}</div><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{rates.map((row) => <article key={row.rateRef} className="rounded-xl border bg-white p-3"><div className="flex items-center justify-between"><strong className="text-sm text-[#003366]">{row.baseCurrency} → {row.quoteCurrency}</strong><span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-bold">v{row.version}</span></div><p className="mt-2 text-xl font-black tabular-nums">{row.rate}</p><p className="mt-1 text-[10px] text-slate-500">{row.source} · {new Date(row.effectiveAt).toLocaleString("es-DO")}</p></article>)}</div></>}
    {ruleDraft && <form onSubmit={(event) => void saveRule(event)} className="mt-3 grid gap-3 rounded-xl border border-indigo-200 bg-indigo-50 p-4 sm:grid-cols-2"><h3 className="sm:col-span-2 text-sm font-black">Nueva versión económica</h3><label className="text-xs font-semibold">Familia<select value={ruleDraft.family} onChange={(event) => setRuleDraft({ ...ruleDraft, family: event.target.value })} className="mt-1 w-full rounded border p-2">{FAMILIES.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs font-semibold">Clase<select value={ruleDraft.classification} onChange={(event) => setRuleDraft({ ...ruleDraft, classification: event.target.value })} className="mt-1 w-full rounded border p-2"><option value="PR">Pr · propio</option><option value="EX">Ex · externo</option><option value="DE">De · desembolso</option></select></label><label className="text-xs font-semibold">Código<input required value={ruleDraft.code} onChange={(event) => setRuleDraft({ ...ruleDraft, code: event.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="text-xs font-semibold">Nombre<input required value={ruleDraft.name} onChange={(event) => setRuleDraft({ ...ruleDraft, name: event.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="text-xs font-semibold">Costo unitario<input type="number" min="0" step="0.000001" value={ruleDraft.unitCost} onChange={(event) => setRuleDraft({ ...ruleDraft, unitCost: event.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="text-xs font-semibold">Moneda<input required pattern="[A-Z]{3}" value={ruleDraft.currency} onChange={(event) => setRuleDraft({ ...ruleDraft, currency: event.target.value })} className="mt-1 w-full rounded border p-2" /></label>{ruleDraft.classification === "PR" && <><label className="text-xs font-semibold">Margen mínimo (bps)<input type="number" min="0" max="9999" value={ruleDraft.minimumMarginBps} onChange={(event) => setRuleDraft({ ...ruleDraft, minimumMarginBps: event.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="text-xs font-semibold">Margen recomendado (bps)<input type="number" min="0" max="9999" value={ruleDraft.recommendedMarginBps} onChange={(event) => setRuleDraft({ ...ruleDraft, recommendedMarginBps: event.target.value })} className="mt-1 w-full rounded border p-2" /></label></>}<div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setRuleDraft(null)} className="rounded border bg-white px-3 py-2 text-xs font-bold">Cancelar</button><button disabled={busy} className="rounded bg-indigo-600 px-3 py-2 text-xs font-bold text-white"><ShieldCheck className="mr-1 inline h-4 w-4" />Versionar</button></div></form>}
    {rateDraft && <form onSubmit={(event) => void saveRate(event)} className="mt-3 grid gap-3 rounded-xl border border-indigo-200 bg-indigo-50 p-4 sm:grid-cols-2"><h3 className="sm:col-span-2 text-sm font-black"><CircleDollarSign className="mr-1 inline h-4 w-4" />Nueva tasa histórica</h3><label className="text-xs font-semibold">Moneda origen<input required pattern="[A-Z]{3}" value={rateDraft.baseCurrency} onChange={(event) => setRateDraft({ ...rateDraft, baseCurrency: event.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="text-xs font-semibold">Moneda base<input required pattern="[A-Z]{3}" value={rateDraft.quoteCurrency} onChange={(event) => setRateDraft({ ...rateDraft, quoteCurrency: event.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="text-xs font-semibold">Tasa<input required type="number" min="0.0000000001" step="0.0000000001" value={rateDraft.rate} onChange={(event) => setRateDraft({ ...rateDraft, rate: event.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="text-xs font-semibold">Fuente<input required value={rateDraft.source} onChange={(event) => setRateDraft({ ...rateDraft, source: event.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="text-xs font-semibold sm:col-span-2">Vigente desde<input required type="datetime-local" value={rateDraft.effectiveAt} onChange={(event) => setRateDraft({ ...rateDraft, effectiveAt: event.target.value })} className="mt-1 w-full rounded border p-2" /></label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setRateDraft(null)} className="rounded border bg-white px-3 py-2 text-xs font-bold">Cancelar</button><button disabled={busy} className="rounded bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Versionar tasa</button></div></form>}
  </section>;
}
