export type LogisticsItem = Readonly<{ itemRef?: string; family: string; kind: string; label: string; quantity: number | null; unit: string | null; estimatedHours: number | null; trips: number | null; requiredQuantity: number | null; availableQuantity: number | null; reservedQuantity: number | null; shortageQuantity: number | null; availability: string | null; priceStatus: string | null; source: string; sourceVersion: number | null }>;
export type LogisticsOverride = Readonly<{ overrideRef: string; itemRef: string | null; suggestedValue: Record<string, unknown>; finalValue: Record<string, unknown>; reason: string; createdAt: string }>;
export type LogisticsIssue = Readonly<{ issueRef?: string; code: string; severity: "INFO" | "WARNING" | "BLOCKER"; family: string | null; message: string; source: string; status?: "OPEN" | "RESOLVED"; version?: number }>;
export type LogisticsRevision = Readonly<{ planRef: string; revisionRef: string; revision: number; status: string; logicalSha256: string; publishedAt: string; items: readonly LogisticsItem[]; issues: readonly LogisticsIssue[]; overrides: readonly LogisticsOverride[] }>;
export type LogisticsCalculation = Readonly<{ calculationRef: string; status: string; inputHash: string; resultHash: string; availabilityObservedAt: string; result: { items: readonly LogisticsItem[]; issues: readonly LogisticsIssue[] } }>;
export type LogisticsRule = Readonly<{ ruleRef: string; seriesRef: string; family: string; code: string; name: string; priority: number; specificity: number; conditions: Record<string, unknown>; result: Record<string, unknown>; state: string; version: number }>;
async function request<T>(authorization: string | undefined, path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(path, { ...init, credentials: "omit", cache: "no-store", headers: { ...(init.body ? { "Content-Type": "application/json" } : {}), ...(authorization ? { Authorization: `Bearer ${authorization}` } : {}), ...(init.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body?.error || "LOGISTICS_REQUEST_FAILED"); return body.data as T; }
function canonicalJson(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; const row = value as Record<string, unknown>; return `{${Object.keys(row).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(row[key])}`).join(",")}}`; }
async function sha256(value: string) { const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(bytes)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function command<T>(authorization: string | undefined, path: string, operation: string, payload: Record<string, unknown>) { const requestId = crypto.randomUUID(); const payloadHash = await sha256(canonicalJson({ operation, requestId, ...payload })); return request<T>(authorization, path, { method: "POST", body: JSON.stringify({ requestId, payloadHash, ...payload }) }); }
export const logisticsApi = Object.freeze({
  plan: (authorization: string | undefined, caseRef: string) => request<LogisticsRevision | null>(authorization, `/api/logistics/plans/${encodeURIComponent(caseRef)}`),
  calculate: (authorization: string | undefined, payload: { caseRef: string; intervalStart: string; intervalEnd: string }) => command<LogisticsCalculation>(authorization, "/api/logistics/plans/calculate", "LOGISTICS_CALCULATE", payload),
  publish: (authorization: string | undefined, calculationRef: string) => command<LogisticsRevision>(authorization, "/api/logistics/plans/publish", "LOGISTICS_PUBLISH", { calculationRef }),
  rules: (authorization?: string) => request<readonly LogisticsRule[]>(authorization, "/api/logistics/rules"),
  versionRule: (authorization: string | undefined, payload: Record<string, unknown>) => command<LogisticsRule>(authorization, "/api/logistics/rules", "LOGISTICS_RULE_VERSION", payload),
  override: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/logistics/plans/overrides", "LOGISTICS_OVERRIDE", payload),
  resolve: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/logistics/plans/issues/resolve", "LOGISTICS_ISSUE_RESOLVE", payload),
});
