import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { logisticsApi, type LogisticsRule } from "./api";
import type { LogisticsUiAccess } from "./access";

type Props = Readonly<{ authorization?: string; access: LogisticsUiAccess; onUnauthorized(): void }>;
type Draft = Readonly<{ seriesRef: string | null; family: string; code: string; name: string; priority: string; specificity: string; mode: string; kind: string; label: string; quantity: string; state: string }>;
const FAMILIES = ["LABOR", "TIME", "TRANSPORT", "MATERIAL", "ASSET", "EXTERNAL", "PER_DIEM", "LODGING", "TOLL", "PARKING", "PERMIT", "ZONE", "CRATING"];
const EMPTY: Draft = { seriesRef: null, family: "LABOR", code: "", name: "", priority: "100", specificity: "0", mode: "", kind: "", label: "", quantity: "1", state: "DRAFT" };

function fromRule(rule: LogisticsRule): Draft {
  const result = rule.result as Record<string, unknown>; const conditions = rule.conditions as Record<string, unknown>; const modes = Array.isArray(conditions.modes) ? conditions.modes : [];
  return { seriesRef: rule.seriesRef, family: rule.family, code: rule.code, name: rule.name, priority: String(rule.priority), specificity: String(rule.specificity), mode: typeof modes[0] === "string" ? modes[0] : "", kind: typeof result.kind === "string" ? result.kind : "", label: typeof result.label === "string" ? result.label : rule.name, quantity: typeof result.quantity === "number" ? String(result.quantity) : "1", state: "DRAFT" };
}

export default function LogisticsRulesAdmin({ authorization, access, onUnauthorized }: Props) {
  const [rules, setRules] = useState<readonly LogisticsRule[]>([]); const [family, setFamily] = useState("ALL"); const [error, setError] = useState<string | null>(null); const [draft, setDraft] = useState<Draft | null>(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { setRules(await logisticsApi.rules(authorization)); } catch (cause) { const code = cause instanceof Error ? cause.message : "LOGISTICS_REQUEST_FAILED"; if (code.includes("AUTH")) onUnauthorized(); else setError(code); } }, [authorization, onUnauthorized]);
  useEffect(() => { if (access.canRulesView) void load(); }, [access.canRulesView, load]);
  const visible = useMemo(() => rules.filter((row) => family === "ALL" || row.family === family), [family, rules]);
  const change = (key: keyof Draft, value: string) => setDraft((current) => current ? { ...current, [key]: value } : current);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!draft) return; setSaving(true); setError(null); try { await logisticsApi.versionRule(authorization, { seriesRef: draft.seriesRef, family: draft.family, code: draft.code.trim(), name: draft.name.trim(), priority: Number(draft.priority), specificity: Number(draft.specificity), conditions: draft.mode ? { modes: [draft.mode] } : {}, result: { kind: draft.kind.trim(), label: draft.label.trim(), quantity: Number(draft.quantity), unit: "unidad" }, state: draft.state, validFrom: null, validTo: null }); setDraft(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "LOGISTICS_REQUEST_FAILED"); } finally { setSaving(false); } };
  if (!access.canRulesView) return null;
  return <section className="mt-7" data-testid="logistics-rules-admin">
    <div className="flex flex-wrap items-end justify-between gap-3 border-b pb-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-indigo-600">Motor Logístico</p><h2 className="text-lg font-black text-slate-950">Reglas operativas versionadas</h2><p className="text-xs text-slate-500">Personal, transporte, recursos, viajes, zonas y permisos. Sin editor de programación.</p></div><div className="flex items-center gap-2"><select aria-label="Familia logística" value={family} onChange={(event) => setFamily(event.target.value)} className="rounded-lg border px-3 py-2 text-xs"><option value="ALL">Todas las familias</option>{FAMILIES.map((value) => <option key={value}>{value}</option>)}</select>{access.canRulesManage && <button type="button" onClick={() => setDraft(EMPTY)} className="rounded-lg bg-[#003366] px-3 py-2 text-xs font-bold text-white">Nueva regla</button>}</div></div>
    {error && <p role="alert" className="mt-3 border border-red-200 bg-red-50 p-3 text-xs text-red-800">{error}</p>}
    {draft && <form onSubmit={(event) => void submit(event)} className="mt-3 grid gap-3 border bg-slate-50 p-3 sm:grid-cols-2 lg:grid-cols-4" data-testid="logistics-rule-form">
      <label className="text-xs font-semibold">Familia<select value={draft.family} onChange={(event) => change("family", event.target.value)} className="mt-1 w-full rounded border bg-white p-2">{FAMILIES.map((value) => <option key={value}>{value}</option>)}</select></label>
      <label className="text-xs font-semibold">Código<input required value={draft.code} onChange={(event) => change("code", event.target.value)} className="mt-1 w-full rounded border p-2" /></label>
      <label className="text-xs font-semibold sm:col-span-2">Nombre empresarial<input required value={draft.name} onChange={(event) => change("name", event.target.value)} className="mt-1 w-full rounded border p-2" /></label>
      <label className="text-xs font-semibold">Prioridad<input required min="0" type="number" value={draft.priority} onChange={(event) => change("priority", event.target.value)} className="mt-1 w-full rounded border p-2" /></label>
      <label className="text-xs font-semibold">Especificidad<input required min="0" type="number" value={draft.specificity} onChange={(event) => change("specificity", event.target.value)} className="mt-1 w-full rounded border p-2" /></label>
      <label className="text-xs font-semibold">Modo aplicable<select value={draft.mode} onChange={(event) => change("mode", event.target.value)} className="mt-1 w-full rounded border bg-white p-2"><option value="">Todos</option><option>LOCAL</option><option>EXPORT</option><option>IMPORT</option></select></label>
      <label className="text-xs font-semibold">Estado<select value={draft.state} onChange={(event) => change("state", event.target.value)} className="mt-1 w-full rounded border bg-white p-2"><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option></select></label>
      <label className="text-xs font-semibold">Tipo de necesidad<input required value={draft.kind} onChange={(event) => change("kind", event.target.value)} className="mt-1 w-full rounded border p-2" /></label>
      <label className="text-xs font-semibold sm:col-span-2">Etiqueta visible<input required value={draft.label} onChange={(event) => change("label", event.target.value)} className="mt-1 w-full rounded border p-2" /></label>
      <label className="text-xs font-semibold">Cantidad<input required min="0" step="0.01" type="number" value={draft.quantity} onChange={(event) => change("quantity", event.target.value)} className="mt-1 w-full rounded border p-2" /></label>
      <div className="flex items-end justify-end gap-2 sm:col-span-2 lg:col-span-4"><button type="button" onClick={() => setDraft(null)} className="rounded border bg-white px-3 py-2 text-xs font-bold">Cancelar</button><button disabled={saving} className="rounded bg-[#003366] px-3 py-2 text-xs font-bold text-white">{draft.seriesRef ? "Crear nueva versión" : "Guardar regla"}</button></div>
    </form>}
    <div className="mt-3 overflow-x-auto border bg-white"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="p-2">Familia</th><th className="p-2">Regla</th><th className="p-2">Prioridad</th><th className="p-2">Especificidad</th><th className="p-2">Versión</th><th className="p-2">Estado</th>{access.canRulesManage && <th className="p-2">Acción</th>}</tr></thead><tbody>{visible.map((row) => <tr key={row.ruleRef} className="border-t"><td className="p-2 font-bold">{row.family}</td><td className="p-2"><strong>{row.name}</strong><span className="block font-mono text-[10px] text-slate-500">{row.code}</span></td><td className="p-2">{row.priority}</td><td className="p-2">{row.specificity}</td><td className="p-2">v{row.version}</td><td className="p-2">{row.state}</td>{access.canRulesManage && <td className="p-2"><button type="button" onClick={() => setDraft(fromRule(row))} className="rounded border px-2 py-1 font-bold">Nueva versión</button></td>}</tr>)}</tbody></table></div>
    {visible.length === 0 && <p className="border border-t-0 bg-white p-6 text-center text-xs text-slate-500">Sin reglas para este filtro.</p>}
  </section>;
}
