import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeftRight, Box, ClipboardList, PackageCheck, RefreshCw, Search, Warehouse } from "lucide-react";
import { materialsApi, type MaterialRow, type MovementRow, type RecipeRow, type RequirementRow, type ReservationRow, type WarehouseRow } from "./api";

type Props = Readonly<{ authorization?: string; effectivePermissions: readonly string[]; deniedPermissions: readonly string[]; onNavigate: (pathname: string) => void; onUnauthorized: () => void }>;
type View = "CATALOG" | "MOVEMENTS" | "RESERVATIONS" | "RECIPES" | "REQUIREMENTS";
type Operation = "RECEIPT" | "TRANSFER" | "RESERVE" | "ADJUSTMENT_POSITIVE" | null;
const VIEW_LABELS: ReadonlyArray<readonly [View, string]> = [["CATALOG", "Catálogo"], ["MOVEMENTS", "Movimientos"], ["RESERVATIONS", "Reservas"], ["RECIPES", "Recetas"], ["REQUIREMENTS", "Necesidades Survey"]];
function number(value: number) { return new Intl.NumberFormat("es-DO", { maximumFractionDigits: 3 }).format(value); }
function cost(value: MaterialRow["currentCost"]) { return value ? `${value.currency} ${new Intl.NumberFormat("es-DO", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value.amount)} / ${value.unitCode}` : "Sin costo"; }
function Status({ value }: { value: string }) { const active = value === "ACTIVE" || value === "RESERVED"; return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${active ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{value}</span>; }

export default function MaterialsInventoryApp({ authorization, effectivePermissions, deniedPermissions, onNavigate, onUnauthorized }: Props) {
  const [view, setView] = useState<View>("CATALOG"); const [search, setSearch] = useState(""); const [family, setFamily] = useState("ALL"); const [statusFilter, setStatusFilter] = useState("ALL"); const [warehouseFilter, setWarehouseFilter] = useState("ALL"); const [availabilityFilter, setAvailabilityFilter] = useState("ALL");
  const [catalog, setCatalog] = useState<readonly MaterialRow[]>([]); const [movements, setMovements] = useState<readonly MovementRow[]>([]); const [reservations, setReservations] = useState<readonly ReservationRow[]>([]);
  const [recipes, setRecipes] = useState<readonly RecipeRow[]>([]); const [requirements, setRequirements] = useState<readonly RequirementRow[]>([]);
  const [selected, setSelected] = useState<MaterialRow | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [warehouses, setWarehouses] = useState<readonly WarehouseRow[]>([]); const [operation, setOperation] = useState<Operation>(null); const [saving, setSaving] = useState(false);
  const allowed = (permission: string) => effectivePermissions.includes(permission) && !deniedPermissions.includes(permission);
  const refresh = useCallback(async () => {
    setLoading(true); setError(null);
    try { const [catalogData, movementData, reservationData, warehouseData, recipeData, requirementData] = await Promise.all([materialsApi.catalog(authorization), materialsApi.movements(authorization), materialsApi.reservations(authorization), materialsApi.warehouses(authorization), materialsApi.recipes(authorization), materialsApi.requirements(authorization)]); setCatalog(catalogData.items); setMovements(movementData.items); setReservations(reservationData); setWarehouses(warehouseData); setRecipes(recipeData); setRequirements(requirementData); setSelected((current) => current ? catalogData.items.find((item) => item.materialRef === current.materialRef) ?? null : null); }
    catch (cause) { const message = cause instanceof Error ? cause.message : "MATERIALS_REQUEST_FAILED"; if (message.includes("AUTH")) onUnauthorized(); else setError(message); }
    finally { setLoading(false); }
  }, [authorization, onUnauthorized]);
  useEffect(() => { void refresh(); }, [refresh]);
  const families = useMemo(() => [...new Set(catalog.map((item) => item.family))].sort(), [catalog]);
  const visible = useMemo(() => catalog.filter((item) => (family === "ALL" || item.family === family) && (statusFilter === "ALL" || item.status === statusFilter) && (warehouseFilter === "ALL" || item.inventory.byWarehouse.some((entry) => entry.warehouseRef === warehouseFilter)) && (availabilityFilter === "ALL" || availabilityFilter === "AVAILABLE" && item.inventory.available > 0 || availabilityFilter === "OUT" && item.inventory.available <= 0 || availabilityFilter === "LOW" && item.reorderPoint !== null && item.inventory.available <= item.reorderPoint) && `${item.code} ${item.name}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())), [availabilityFilter, catalog, family, search, statusFilter, warehouseFilter]);
  const totals = useMemo(() => catalog.reduce((sum, item) => ({ physical: sum.physical + item.inventory.physical, reserved: sum.reserved + item.inventory.reserved, assigned: sum.assigned + item.inventory.assigned, available: sum.available + item.inventory.available }), { physical: 0, reserved: 0, assigned: 0, available: 0 }), [catalog]);
  return <div className="min-h-screen bg-slate-100 text-slate-950">
    <header className="border-b border-slate-800 bg-[#003366] px-4 py-4 text-white sm:px-6"><div className="mx-auto flex max-w-[1600px] flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-sky-200">OSi Plus · ERP</p><h1 className="text-xl font-black">Materiales e Inventario</h1><p className="text-xs text-sky-100">Consumibles tenant-first · stock derivado del ledger</p></div><div className="flex gap-2"><button className="rounded-lg border border-white/30 px-3 py-2 text-xs font-semibold" onClick={() => void refresh()} aria-label="Actualizar inventario"><RefreshCw className="mr-2 inline h-4 w-4" />Actualizar</button><button className="rounded-lg bg-white px-3 py-2 text-xs font-bold text-[#003366]" onClick={() => onNavigate("/hub")}>Volver al Hub</button></div></div></header>
    <main className="mx-auto max-w-[1600px] p-3 sm:p-6">
      <section className="grid grid-cols-2 gap-2 sm:grid-cols-4" aria-label="Resumen de inventario"><div className="rounded-xl border bg-white p-3"><span className="text-[10px] font-bold uppercase text-slate-500">Existencia</span><strong className="mt-1 block text-xl">{number(totals.physical)}</strong></div><div className="rounded-xl border bg-white p-3"><span className="text-[10px] font-bold uppercase text-slate-500">Reservado</span><strong className="mt-1 block text-xl text-amber-700">{number(totals.reserved)}</strong></div><div className="rounded-xl border bg-white p-3"><span className="text-[10px] font-bold uppercase text-slate-500">Asignado</span><strong className="mt-1 block text-xl text-sky-700">{number(totals.assigned)}</strong></div><div className="rounded-xl border bg-white p-3"><span className="text-[10px] font-bold uppercase text-slate-500">Disponible</span><strong className="mt-1 block text-xl text-emerald-700">{number(totals.available)}</strong></div></section>
      <nav className="mt-3 flex gap-1 overflow-x-auto rounded-xl border bg-white p-1" aria-label="Secciones de inventario">{VIEW_LABELS.map(([id, label]) => <button key={id} onClick={() => setView(id)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold ${view === id ? "bg-[#003366] text-white" : "text-slate-600 hover:bg-slate-100"}`}>{label}</button>)}</nav>
      {error && <div role="alert" className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">No se pudo cargar el módulo: {error}</div>}
      {view === "CATALOG" && <section className="mt-3 grid gap-3 xl:grid-cols-[minmax(0,1.45fr)_minmax(340px,.55fr)]">
        <div className="overflow-hidden rounded-xl border bg-white"><div className="flex flex-wrap items-center gap-2 border-b p-3"><label className="flex min-w-60 flex-1 items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Search className="h-4 w-4 text-slate-400" /><span className="sr-only">Buscar material</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Código o material" className="min-w-0 flex-1 outline-none" /></label><select aria-label="Filtrar por familia" value={family} onChange={(event) => setFamily(event.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="ALL">Todas las familias</option>{families.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Filtrar por estado" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="ALL">Todos los estados</option><option value="ACTIVE">Activos</option><option value="INACTIVE">Inactivos</option></select><select aria-label="Filtrar por almacén" value={warehouseFilter} onChange={(event) => setWarehouseFilter(event.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="ALL">Todos los almacenes</option>{warehouses.map((entry) => <option key={entry.warehouseRef} value={entry.warehouseRef}>{entry.name}</option>)}</select><select aria-label="Filtrar por disponibilidad" value={availabilityFilter} onChange={(event) => setAvailabilityFilter(event.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="ALL">Toda disponibilidad</option><option value="AVAILABLE">Con disponibilidad</option><option value="OUT">Sin disponibilidad</option><option value="LOW">Bajo punto de reposición</option></select></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[920px] border-collapse text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-2">Código</th><th className="px-3 py-2">Material</th><th className="px-3 py-2">Unidad</th><th className="px-3 py-2 text-right">Existencia</th><th className="px-3 py-2 text-right">Reservado</th><th className="px-3 py-2 text-right">Asignado</th><th className="px-3 py-2 text-right">Disponible</th><th className="px-3 py-2">Costo vigente</th><th className="px-3 py-2">Estado</th></tr></thead><tbody>{visible.map((item) => <tr key={item.materialRef} tabIndex={0} onClick={() => setSelected(item)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelected(item); } }} className={`cursor-pointer border-t outline-none hover:bg-sky-50 focus:bg-sky-50 ${selected?.materialRef === item.materialRef ? "bg-sky-100" : ""}`}><td className="px-3 py-2 font-mono font-bold text-[#003366]">{item.code}</td><td className="px-3 py-2"><strong className="block">{item.name}</strong><span className="text-slate-500">{item.family}{item.subfamily ? ` · ${item.subfamily}` : ""}</span></td><td className="px-3 py-2">{item.baseUnit.code}</td><td className="px-3 py-2 text-right tabular-nums">{number(item.inventory.physical)}</td><td className="px-3 py-2 text-right tabular-nums text-amber-700">{number(item.inventory.reserved)}</td><td className="px-3 py-2 text-right tabular-nums text-sky-700">{number(item.inventory.assigned)}</td><td className="px-3 py-2 text-right font-bold tabular-nums">{number(item.inventory.available)}</td><td className="px-3 py-2 tabular-nums">{cost(item.currentCost)}</td><td className="px-3 py-2"><Status value={item.status} /></td></tr>)}</tbody></table></div>{!loading && visible.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No hay materiales para estos filtros.</p>}
        </div>
        <aside className="rounded-xl border bg-white p-4">{selected ? <><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs font-bold text-sky-700">{selected.code}</p><h2 className="text-lg font-black">{selected.name}</h2></div><Status value={selected.status} /></div><p className="mt-2 text-sm leading-6 text-slate-600">{selected.description || "Sin descripción."}</p><dl className="mt-4 divide-y text-sm"><div className="flex justify-between py-2"><dt>Familia</dt><dd className="font-semibold">{selected.family}</dd></div><div className="flex justify-between py-2"><dt>Costo vigente</dt><dd className="font-semibold">{cost(selected.currentCost)}</dd></div><div className="flex justify-between py-2"><dt>Stock mínimo</dt><dd>{selected.minimumStock ?? "No definido"}</dd></div><div className="flex justify-between py-2"><dt>Versión</dt><dd>{selected.version}</dd></div></dl><div className="mt-4 grid grid-cols-2 gap-2">{allowed("inventory:stock:receive") && <button onClick={() => setOperation("RECEIPT")} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white"><PackageCheck className="mr-1 inline h-4 w-4" />Recepción</button>}{allowed("inventory:stock:transfer") && <button onClick={() => setOperation("TRANSFER")} className="rounded-lg bg-sky-700 px-3 py-2 text-xs font-bold text-white"><ArrowLeftRight className="mr-1 inline h-4 w-4" />Transferir</button>}{allowed("inventory:reservation:manage") && <button onClick={() => setOperation("RESERVE")} className="rounded-lg border px-3 py-2 text-xs font-bold"><ClipboardList className="mr-1 inline h-4 w-4" />Reservar</button>}{allowed("inventory:stock:adjust") && <button onClick={() => setOperation("ADJUSTMENT_POSITIVE")} className="rounded-lg border px-3 py-2 text-xs font-bold"><Box className="mr-1 inline h-4 w-4" />Ajustar</button>}</div></> : <div className="grid min-h-72 place-items-center text-center text-sm text-slate-500"><div><Warehouse className="mx-auto mb-3 h-8 w-8 text-slate-300" />Seleccione un material para ver su detalle y operaciones autorizadas.</div></div>}</aside>
      </section>}
      {view === "MOVEMENTS" && <CompactTable title="Ledger append-only" rows={movements.map((row) => [row.movementType, `${row.material.code} · ${row.material.name}`, `${row.location.warehouse} · ${row.location.code}`, number(row.quantity), new Date(row.occurredAt).toLocaleString("es-DO")])} headers={["Movimiento", "Material", "Ubicación", "Cantidad", "Fecha"]} />}
      {view === "RESERVATIONS" && <section className="mt-3 overflow-hidden rounded-xl border bg-white"><h2 className="border-b p-4 font-black">Reservas separadas del stock físico</h2><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-3 py-2">Estado</th><th className="px-3 py-2">Material</th><th className="px-3 py-2">Ubicación</th><th className="px-3 py-2">Cantidad</th><th className="px-3 py-2">Versión</th><th className="px-3 py-2">Acción</th></tr></thead><tbody>{reservations.map((row) => <tr key={row.reservationRef} className="border-t"><td className="px-3 py-2"><Status value={row.status} /></td><td className="px-3 py-2">{row.material.code} · {row.material.name}</td><td className="px-3 py-2">{row.location.code}</td><td className="px-3 py-2">{number(row.quantity)}</td><td className="px-3 py-2">v{row.version}</td><td className="px-3 py-2"><div className="flex gap-2">{allowed("inventory:reservation:manage") && row.status === "RESERVED" && <button disabled={saving} onClick={async () => { setSaving(true); setError(null); try { await materialsApi.assign(authorization, { reservationRef: row.reservationRef, expectedVersion: row.version, reasonCode: "ASSIGNMENT_CONFIRMED" }); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "MATERIALS_REQUEST_FAILED"); } finally { setSaving(false); } }} className="rounded-lg border px-3 py-1.5 font-bold">Asignar</button>}{allowed("inventory:reservation:manage") && ["RESERVED", "ASSIGNED"].includes(row.status) ? <button disabled={saving} onClick={async () => { setSaving(true); setError(null); try { await materialsApi.release(authorization, { reservationRef: row.reservationRef, expectedVersion: row.version, reasonCode: "MANUAL_RELEASE" }); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "MATERIALS_REQUEST_FAILED"); } finally { setSaving(false); } }} className="rounded-lg border px-3 py-1.5 font-bold">Liberar</button> : "—"}</div></td></tr>)}</tbody></table></div>{reservations.length === 0 && <p className="p-8 text-center text-sm text-slate-500">Sin registros.</p>}</section>}
      {view === "RECIPES" && <CompactTable title="Recetas de empaque · sin selección manual desde Survey" rows={recipes.map((row) => [row.code, row.name, row.status, row.versions[0] ? `v${row.versions[0].version} · ${row.versions[0].lines.length} líneas` : "Sin versión"])} headers={["Código", "Receta", "Estado", "Versión vigente"]} />}
      {view === "REQUIREMENTS" && <CompactTable title="Necesidades derivadas de Survey · snapshots inmutables" rows={requirements.flatMap((row) => row.items.map((item) => [row.status, `${row.recipe.code} v${row.recipe.version}`, `${item.code} · ${item.name}`, `${number(item.quantity)} ${item.unit.code}`, `r${row.revision}`]))} headers={["Estado", "Receta", "Material sugerido", "Requerido", "Revisión"]} />}
      {operation && selected && <OperationDialog operation={operation} material={selected} warehouses={warehouses} saving={saving} onClose={() => setOperation(null)} onSubmit={async (payload) => { setSaving(true); setError(null); try { if (operation === "RESERVE") await materialsApi.reserve(authorization, payload); else await materialsApi.movement(authorization, payload); setOperation(null); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "MATERIALS_REQUEST_FAILED"); } finally { setSaving(false); } }} />}
    </main>
  </div>;
}
function CompactTable({ title, headers, rows }: { title: string; headers: readonly string[]; rows: readonly (readonly (string | number)[])[] }) { return <section className="mt-3 overflow-hidden rounded-xl border bg-white"><h2 className="border-b p-4 font-black">{title}</h2><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{headers.map((header) => <th key={header} className="px-3 py-2">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t">{row.map((cell, cellIndex) => <td key={cellIndex} className="px-3 py-2">{cell}</td>)}</tr>)}</tbody></table></div>{rows.length === 0 && <p className="p-8 text-center text-sm text-slate-500">Sin registros.</p>}</section>; }
function OperationDialog({ operation, material, warehouses, saving, onClose, onSubmit }: { operation: Exclude<Operation, null>; material: MaterialRow; warehouses: readonly WarehouseRow[]; saving: boolean; onClose: () => void; onSubmit: (payload: Record<string, unknown>) => Promise<void> }) {
  const locations = warehouses.flatMap((warehouse) => warehouse.locations.map((location) => ({ ...location, warehouse: warehouse.name }))).filter((location) => location.status === "ACTIVE"); const [locationRef, setLocationRef] = useState(locations[0]?.locationRef || ""); const [counterpartLocationRef, setCounterpartLocationRef] = useState(locations[1]?.locationRef || ""); const [quantity, setQuantity] = useState("1"); const [reasonCode, setReasonCode] = useState(operation === "RECEIPT" ? "PURCHASE_RECEIPT" : operation === "TRANSFER" ? "INTERNAL_TRANSFER" : operation === "RESERVE" ? "CASE_REQUIREMENT" : "PHYSICAL_COUNT");
  const label = operation === "RECEIPT" ? "Registrar recepción" : operation === "TRANSFER" ? "Transferir material" : operation === "RESERVE" ? "Crear reserva" : "Registrar ajuste positivo";
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" role="presentation"><form role="dialog" aria-modal="true" aria-labelledby="material-operation-title" onSubmit={(event) => { event.preventDefault(); const base = { materialRef: material.materialRef, locationRef, quantity: Number(quantity) }; void onSubmit(operation === "RESERVE" ? { ...base, caseRef: null, requirementRef: null, cratingReference: null } : { ...base, movementType: operation === "TRANSFER" ? "TRANSFER_OUT" : operation, counterpartLocationRef: operation === "TRANSFER" ? counterpartLocationRef : null, lotCode: null, reasonCode, reservationRef: null, requirementRef: null }); }} className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><h2 id="material-operation-title" className="text-lg font-black">{label}</h2><p className="mt-1 text-sm text-slate-600">{material.code} · {material.name}</p><div className="mt-4 grid gap-3"><label className="text-xs font-bold text-slate-700">Ubicación<select required value={locationRef} onChange={(event) => setLocationRef(event.target.value)} className="mt-1 block w-full rounded-lg border px-3 py-2 font-normal"><option value="">Seleccionar</option>{locations.map((location) => <option key={location.locationRef} value={location.locationRef}>{location.warehouse} · {location.path}</option>)}</select></label>{operation === "TRANSFER" && <label className="text-xs font-bold text-slate-700">Destino<select required value={counterpartLocationRef} onChange={(event) => setCounterpartLocationRef(event.target.value)} className="mt-1 block w-full rounded-lg border px-3 py-2 font-normal"><option value="">Seleccionar</option>{locations.filter((location) => location.locationRef !== locationRef).map((location) => <option key={location.locationRef} value={location.locationRef}>{location.warehouse} · {location.path}</option>)}</select></label>}<label className="text-xs font-bold text-slate-700">Cantidad ({material.baseUnit.code})<input required min="0.001" step="0.001" type="number" value={quantity} onChange={(event) => setQuantity(event.target.value)} className="mt-1 block w-full rounded-lg border px-3 py-2 font-normal" /></label>{operation !== "RESERVE" && <label className="text-xs font-bold text-slate-700">Motivo<input required value={reasonCode} onChange={(event) => setReasonCode(event.target.value.toUpperCase())} pattern="[A-Z][A-Z0-9_-]+" className="mt-1 block w-full rounded-lg border px-3 py-2 font-normal" /></label>}</div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancelar</button><button disabled={saving || !locationRef} className="rounded-lg bg-[#003366] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? "Guardando…" : "Confirmar"}</button></div></form></div>;
}
