import { useEffect, useRef, useState } from "react";

export type SignaturePoint = Readonly<{ x: number; y: number }>;
export function SignaturePad({ onChange }: { onChange: (strokes: readonly (readonly SignaturePoint[])[]) => void }) {
  const canvas = useRef<HTMLCanvasElement>(null); const [strokes, setStrokes] = useState<SignaturePoint[][]>([]); const active = useRef<SignaturePoint[] | null>(null);
  const point = (event: React.PointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)), y: Math.max(0, Math.min(1, (event.clientY - rect.top) / rect.height)) }; };
  useEffect(() => { const target = canvas.current; if (!target) return; const ratio = window.devicePixelRatio || 1; target.width = Math.round(target.clientWidth * ratio); target.height = Math.round(180 * ratio); const context = target.getContext("2d"); if (!context) return; context.scale(ratio, ratio); context.clearRect(0, 0, target.clientWidth, 180); context.strokeStyle = "#0f172a"; context.lineWidth = 2.5; context.lineCap = "round"; context.lineJoin = "round"; for (const stroke of strokes) { context.beginPath(); stroke.forEach((entry, index) => index ? context.lineTo(entry.x * target.clientWidth, entry.y * 180) : context.moveTo(entry.x * target.clientWidth, entry.y * 180)); context.stroke(); } }, [strokes]);
  const finish = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!active.current) return; event.currentTarget.releasePointerCapture(event.pointerId); const next = [...strokes, active.current]; active.current = null; setStrokes(next); onChange(next); };
  return <div><canvas ref={canvas} aria-label="Firma dibujada" role="img" className="h-[180px] w-full touch-none rounded-xl border-2 border-slate-300 bg-white" onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); active.current = [point(event)]; }} onPointerMove={(event) => { if (!active.current) return; active.current.push(point(event)); setStrokes([...strokes, [...active.current]]); }} onPointerUp={finish} onPointerCancel={finish} /><button type="button" className="mt-2 min-h-11 rounded-lg border px-4 text-sm font-semibold" onClick={() => { setStrokes([]); onChange([]); }}>Limpiar firma</button></div>;
}
