export type CommercialEntitySummary = Readonly<{ entityRef: string; code: string; displayName: string; legalName: string | null; kind: string; countryCode: string | null; status: string; validFrom: string | null; validTo: string | null; version: number; client: { clientRef: string; displayName: string; type: string; status: string } | null }>;
export type CommercialRelationshipSummary = Readonly<{ relationshipRef: string; source: { entityRef: string; displayName: string; kind: string }; target: { entityRef: string; displayName: string; kind: string }; type: string; reference: string | null; status: string; validFrom: string | null; validTo: string | null; version: number }>;
export type CommercialCaseSnapshot = Readonly<{
  commercialContextRef: string; seriesRef: string; version: number; commercialRelationshipRef: string | null; payerRef: string | null; pricingAgreementRef: string | null; referralAgreementRef: string | null;
  parties: readonly { role: string; entityRef: string; relationshipRef: string | null; displayName: string; kind: string; validFrom: string | null; validTo: string | null; contacts: readonly { contactRef: string; displayName: string; position: string | null; preferredChannel: string | null }[] }[];
  agreement: null | { pricingAgreementRef: string; version: number; validFrom: string | null; validTo: string | null; tariff: null | { tariffRef: string; code: string; name: string; version: number; currency: string }; adjustments: readonly { adjustmentRef: string; kind: string; calculationType: string; value: number; base: string; reasonCode: string; authorized: boolean; validFrom: string | null; validTo: string | null }[] };
  referral: null | { referralAgreementRef: string; version: number; calculationType: string; value: number; currency: string | null; reference: string; validFrom: string | null; validTo: string | null };
  associations: readonly { membershipRef: string; associationRef: string; associationName: string; membershipNumber: string | null; validFrom: string | null; validTo: string | null }[];
  instructions: readonly { instructionRef: string; category: string; serviceScope: Record<string, unknown>; content: Record<string, unknown>; logicalSha256: string }[];
  logicalSha256: string;
}>;

async function request<T>(authorization: string | undefined, url: string, init: RequestInit = {}): Promise<T> { const response = await fetch(url, { ...init, headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...(authorization ? { Authorization: authorization } : {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(String(payload.error || "COMMERCIAL_RELATIONSHIPS_REQUEST_FAILED")); return payload.data as T; }
export class CommercialRelationshipsApi {
  private readonly authorization?: string;
  constructor(authorization?: string) { this.authorization = authorization; }
  entities(search = "") { return request<{ page: number; pageSize: number; total: number; items: readonly CommercialEntitySummary[] }>(this.authorization, `/api/commercial-relationships/entities?search=${encodeURIComponent(search)}`); }
  relationships() { return request<readonly CommercialRelationshipSummary[]>(this.authorization, "/api/commercial-relationships/relationships"); }
  workspace() { return request<{ tariffs: readonly Record<string, unknown>[]; pricingAgreements: readonly Record<string, unknown>[]; referrals: readonly Record<string, unknown>[]; commissions: readonly Record<string, unknown>[]; associations: readonly Record<string, unknown>[]; certifications: readonly Record<string, unknown>[] }>(this.authorization, "/api/commercial-relationships/workspace"); }
  caseContext(caseRef: string) { return request<CommercialCaseSnapshot | null>(this.authorization, `/api/commercial-relationships/cases/${encodeURIComponent(caseRef)}`); }
  async createEntity(payload: Record<string, unknown>) { return request<CommercialEntitySummary>(this.authorization, "/api/commercial-relationships/entities", { method: "POST", body: JSON.stringify(await command("ENTITY_CREATE", payload)) }); }
  async updateEntity(payload: Record<string, unknown>) { return request<CommercialEntitySummary>(this.authorization, "/api/commercial-relationships/entities", { method: "PATCH", body: JSON.stringify(await command("ENTITY_UPDATE", payload)) }); }
  async createRelationship(payload: Record<string, unknown>) { return request<CommercialRelationshipSummary>(this.authorization, "/api/commercial-relationships/relationships", { method: "POST", body: JSON.stringify(await command("RELATIONSHIP_CREATE", payload)) }); }
  async publishContext(caseRef: string, payload: Record<string, unknown>) { return request<CommercialCaseSnapshot>(this.authorization, `/api/commercial-relationships/cases/${encodeURIComponent(caseRef)}`, { method: "POST", body: JSON.stringify(await command("CASE_CONTEXT_PUBLISH", payload, caseRef)) }); }
}
function canonical(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; const object = value as Record<string, unknown>; return `{${Object.keys(object).sort().map((key) => `${JSON.stringify(key)}:${canonical(object[key])}`).join(",")}}`; }
async function command(operation: string, body: Record<string, unknown>, caseRef?: string) { const requestId = crypto.randomUUID(); const input = caseRef ? { operation, requestId, caseRef, ...body } : { operation, requestId, ...body }; const bytes = new TextEncoder().encode(canonical(input)); const digest = await crypto.subtle.digest("SHA-256", bytes); const payloadHash = [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); return { requestId, payloadHash, ...body }; }
