DROP TRIGGER IF EXISTS "communication_audit_events_append_only" ON "communication_audit_events";
DROP TRIGGER IF EXISTS "communication_commands_append_only" ON "communication_commands";
DROP TRIGGER IF EXISTS "communication_records_guard" ON "communication_records";
DROP TRIGGER IF EXISTS "communication_template_versions_guard" ON "communication_template_versions";
DROP TRIGGER IF EXISTS "communication_templates_guard" ON "communication_templates";
DROP FUNCTION IF EXISTS "communication_append_only"();
DROP FUNCTION IF EXISTS "communication_record_guard"();
DROP FUNCTION IF EXISTS "communication_template_version_guard"();
DROP FUNCTION IF EXISTS "communication_template_guard"();
DROP TABLE IF EXISTS "communication_audit_events";
DROP TABLE IF EXISTS "communication_commands";
DROP TABLE IF EXISTS "communication_records";
DROP TABLE IF EXISTS "communication_template_versions";
DROP TABLE IF EXISTS "communication_templates";
DROP TYPE IF EXISTS "CommunicationStatus";
DROP TYPE IF EXISTS "CommunicationMilestone";
DROP TYPE IF EXISTS "CommunicationAudience";
DROP TYPE IF EXISTS "CommunicationChannel";
DROP TYPE IF EXISTS "CommunicationTemplateVersionState";
DROP TYPE IF EXISTS "CommunicationTemplateState";
DROP TYPE IF EXISTS "CommunicationTemplateCategory";
DELETE FROM "_prisma_migrations" WHERE "migration_name" = '20260913010000_v17_communications_templates';
