import { expect, test, type Page } from "@playwright/test";

const REF = { membership: "048f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", model: "148f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", asset: "248f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", warehouse: "348f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", location: "448f6d8f-8d11-4f39-8a2d-1b6c7e8f9012", offer: "548f6d8f-8d11-4f39-8a2d-1b6c7e8f9012" };
const permissions = ["assets:model:view", "assets:model:manage", "assets:instance:view", "assets:instance:manage", "assets:reservation:manage", "assets:assignment:manage", "assets:inspection:perform", "assets:maintenance:view", "assets:maintenance:manage", "assets:incident:manage", "assets:external:view", "assets:external:manage"];
const model = { modelRef: REF.model, code: "DRILL", name: "Taladro inalámbrico", description: "Equipo sintético", family: "POWER_TOOLS", resourceType: "TOOL", serialPolicy: "REQUIRED", identificationPolicy: { qr: true }, capacity: { units: 1 }, status: "ACTIVE", version: 1, instanceCount: 1 };
const asset = { assetRef: REF.asset, internalCode: "TL-000001", serialNumber: "SERIAL-SYNTHETIC", barcode: null, model, operationalStatus: "AVAILABLE", physicalCondition: "GOOD", location: { locationRef: REF.location, code: "TOOLS", name: "Herramientas", path: "MAIN/TOOLS", warehouse: { warehouseRef: REF.warehouse, code: "MAIN", name: "Principal" } }, acquiredAt: "2026-09-04", acquisitionCost: 100, replacementCost: 150, currency: "DOP", usageHours: 4, usageCycles: 2, odometerKm: null, version: 1, availability: { available: true, blockedStatus: false, reserved: false, assigned: false, maintenance: false, interval: { startsAt: "2026-09-04T12:00:00.000Z", endsAt: "2026-09-04T13:00:00.000Z" } }, assignments: [], reservations: [], inspections: [], incidents: [], maintenance: [], costs: [], history: [{ eventRef: REF.offer, eventType: "ASSET_CREATED", referenceType: "ASSET", occurredAt: "2026-09-04T12:00:00.000Z" }] };

async function session(page: Page, deny = false) {
  await page.addInitScript(({ membership }) => { localStorage.setItem("osi-plus.token", "synthetic.assets.token"); localStorage.setItem("osi-plus.session", JSON.stringify({ name: "Recursos sintético", role: "A", membershipRef: membership, memberships: [{ membershipRef: membership, tenantName: "Tenant sintético", role: "A", preferred: true }] })); }, { membership: REF.membership });
  await page.route("**/api/auth/me", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, user: { name: "Recursos sintético", role: "A", status: "ACTIVE", permissions: deny ? [] : permissions, deniedPermissions: deny ? ["assets:instance:view"] : [], membership: { membershipRef: REF.membership, tenantName: "Tenant sintético", role: "A" }, memberships: [{ membershipRef: REF.membership, tenantName: "Tenant sintético", role: "A", preferred: true }] } }) }));
}
async function api(page: Page) {
  const posts: string[] = [];
  await page.route("**/api/assets/models", async (route) => route.fulfill({ status: route.request().method() === "POST" ? 201 : 200, contentType: "application/json", body: JSON.stringify({ ok: true, data: route.request().method() === "POST" ? model : [model] }) }));
  await page.route("**/api/assets/instances**", async (route) => { const url = new URL(route.request().url()); const detail = url.pathname.endsWith(REF.asset); return route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, data: detail ? asset : { page: 1, pageSize: 25, total: 1, items: [asset] } }) }); });
  await page.route("**/api/assets/external/offers", async (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, data: [{ offerRef: REF.offer, provider: { reference: "PROVIDER-SYNTHETIC", displayName: "Proveedor sintético" }, model: null, resourceDescription: "Montacargas alquilado", capacity: { quantity: 1 }, rate: null, validity: { from: null, to: null }, availabilityStatus: "UNCONFIRMED", contractualReference: null, status: "ACTIVE", activeReservations: 0, version: 1 }] }) }));
  await page.route("**/api/assets/**", async (route) => { if (route.request().method() === "GET") return route.fallback(); posts.push(new URL(route.request().url()).pathname); return route.fulfill({ status: 201, contentType: "application/json", body: JSON.stringify({ ok: true, data: { accepted: true } }) }); });
  return posts;
}

test("tabla compacta, detalle y operaciones", async ({ page }, testInfo) => {
  await session(page); const posts = await api(page); await page.goto("/assets"); await expect(page.getByRole("heading", { name: "Herramientas y Equipos" })).toBeVisible(); await expect(page.getByText("Taladro inalámbrico").first()).toBeVisible();
  await page.getByPlaceholder("Código, recurso o serial").fill("TL-000001"); await page.getByLabel("Familia").selectOption("POWER_TOOLS"); await page.getByLabel("Ubicación").selectOption("MAIN/TOOLS"); await page.getByLabel("Disponibilidad").selectOption("AVAILABLE"); await page.getByText("Taladro inalámbrico").first().click(); await expect(page.getByText("Disponibilidad", { exact: true })).toBeVisible(); await expect(page.getByText("Historial", { exact: true })).toBeVisible();
  for (const action of ["Reservar", "Asignar", "Entregar", "Devolver", "Inspeccionar", "Incidencia", "Mantenimiento", "Registrar costo"]) { await page.getByRole("button", { name: action }).click(); await expect(page.getByRole("dialog")).toBeVisible(); await page.getByRole("button", { name: "Cancelar" }).click(); }
  await page.getByRole("button", { name: "Reservar" }).click(); await page.getByRole("button", { name: "Confirmar" }).click(); await expect.poll(() => posts.includes("/api/assets/reservations")).toBeTruthy();
  await page.getByRole("button", { name: "Recursos externos" }).click(); await expect(page.getByText("Montacargas alquilado")).toBeVisible(); await expect(page.getByText("Precio pendiente")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), `${testInfo.project.name} no debe tener overflow`).toBe(false);
});

test("deny bloquea antes del lazy y de toda API de activos", async ({ page }) => {
  await session(page, true); let requests = 0; await page.route("**/api/assets/**", (route) => { requests += 1; return route.abort(); }); await page.goto("/assets"); await expect(page.getByRole("heading", { name: "No puedes abrir esta aplicación" })).toBeVisible(); expect(requests).toBe(0); const chunks = await page.evaluate(() => performance.getEntriesByType("resource").map((entry) => entry.name).filter((name) => name.includes("ToolsEquipmentApp"))); expect(chunks).toHaveLength(0);
});
