export type AssetModelRow = Readonly<{ modelRef: string; code: string; name: string; description: string | null; family: string; resourceType: "TOOL" | "EQUIPMENT"; serialPolicy: string; capacity: Record<string, unknown>; status: string; version: number; instanceCount?: number }>;
export type AssetRow = Readonly<{ assetRef: string; internalCode: string; serialNumber: string | null; barcode: string | null; model: AssetModelRow; operationalStatus: string; physicalCondition: string; location: null | { locationRef: string; code: string; name: string; path: string; warehouse?: { warehouseRef: string; code: string; name: string } }; acquiredAt: string | null; acquisitionCost: number | null; replacementCost: number | null; currency: string | null; usageHours: number | null; usageCycles: number | null; odometerKm: number | null; version: number; availability: { available: boolean; blockedStatus: boolean; reserved: boolean; assigned: boolean; maintenance: boolean; interval: { startsAt: string; endsAt: string } }; assignments?: readonly Record<string, unknown>[]; reservations?: readonly Record<string, unknown>[]; inspections?: readonly Record<string, unknown>[]; incidents?: readonly Record<string, unknown>[]; maintenance?: readonly Record<string, unknown>[]; costs?: readonly Record<string, unknown>[]; history?: readonly Record<string, unknown>[] }>;
export type ExternalOfferRow = Readonly<{ offerRef: string; provider: { reference: string; displayName: string }; model: AssetModelRow | null; resourceDescription: string; capacity: Record<string, unknown>; rate: null | { amount: number; currency: string; temporalUnit: string }; validity: { from: string | null; to: string | null }; availabilityStatus: string; contractualReference: string | null; status: string; activeReservations: number; version: number }>;
async function request<T>(authorization: string | undefined, path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(path, { ...init, headers: { ...(init.body ? { "Content-Type": "application/json" } : {}), ...(authorization ? { Authorization: `Bearer ${authorization}` } : {}), ...(init.headers || {}) }, credentials: "omit", cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body?.error || "ASSET_REQUEST_FAILED"); return body.data as T; }
function canonicalJson(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; const row = value as Record<string, unknown>; return `{${Object.keys(row).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(row[key])}`).join(",")}}`; }
async function sha256(value: string) { const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(bytes)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function command<T>(authorization: string | undefined, path: string, operation: string, payload: Record<string, unknown>, method = "POST"): Promise<T> { const requestId = crypto.randomUUID(); const payloadHash = await sha256(canonicalJson({ operation, requestId, ...payload })); return request<T>(authorization, path, { method, body: JSON.stringify({ requestId, payloadHash, ...payload }) }); }
export const toolsEquipmentApi = Object.freeze({
  models: (authorization?: string) => request<readonly AssetModelRow[]>(authorization, "/api/assets/models"),
  instances: (authorization?: string, query = "") => request<{ page: number; pageSize: number; total: number; items: readonly AssetRow[] }>(authorization, `/api/assets/instances${query}`),
  detail: (authorization: string | undefined, assetRef: string) => request<AssetRow>(authorization, `/api/assets/instances/${encodeURIComponent(assetRef)}`),
  externalOffers: (authorization?: string) => request<readonly ExternalOfferRow[]>(authorization, "/api/assets/external/offers"),
  createModel: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/models", "ASSET_MODEL_CREATE", payload),
  createInstance: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/instances", "ASSET_INSTANCE_CREATE", payload),
  createExternalOffer: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/external/offers", "EXTERNAL_OFFER_CREATE", payload),
  reserve: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/reservations", "ASSET_RESERVATION_CREATE", payload),
  assign: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/assignments", "ASSET_ASSIGNMENT_CREATE", payload),
  handout: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/assignments/handout", "ASSET_HANDOUT", payload),
  returnAsset: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/assignments/return", "ASSET_RETURN", payload),
  inspect: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/inspections", "ASSET_INSPECTION_CREATE", payload),
  incident: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/incidents", "ASSET_INCIDENT_CREATE", payload),
  maintenance: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/maintenance", "ASSET_MAINTENANCE_CREATE", payload),
  cost: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/costs", "ASSET_COST_VERSION_CREATE", payload),
  externalReservation: (authorization: string | undefined, payload: Record<string, unknown>) => command(authorization, "/api/assets/external/reservations", "EXTERNAL_RESERVATION_CREATE", payload),
});
