import { getMembershipRef } from "@/lib/sessionStore";

const UUID_V4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
type RecordValue = Record<string, unknown>;
export type ServiceCatalogItem = Readonly<{ serviceRef: string; code: string; name: string; category: string | null; usage: "PRIMARY" | "COMPLEMENTARY" | "BOTH"; compatibleModes: readonly ("LOCAL" | "EXPORT" | "IMPORT")[]; status: "ACTIVE" | "INACTIVE"; sortOrder: number; version: number; usageCount: number; allowedComplementaryRefs: readonly string[] }>;
export type CaseServiceSelection = Readonly<{ selectionRef: string | null; revision: number; mode: "LOCAL" | "EXPORT" | "IMPORT" | null; source: "MANUAL" | "DEFAULT_COMBINATION" | null; defaultCombinationRef: string | null; primary: Readonly<{ serviceRef: string; code: string; name: string; category: string | null; catalogVersion: number; source: string }> | null; complementaries: readonly Readonly<{ serviceRef: string; code: string; name: string; category: string | null; catalogVersion: number; source: string }>[]; otherServices: readonly Readonly<{ description: string; classificationStatus: "PENDING" }>[]; historyCount: number }>;
export type CaseServiceWorkspace = Readonly<{ caseRef: string; mode: "LOCAL" | "EXPORT" | "IMPORT"; selection: CaseServiceSelection; primaries: readonly ServiceCatalogItem[]; allowedComplementaries: readonly Readonly<{ primaryServiceRef: string; service: ServiceCatalogItem }>[]; defaults: readonly Readonly<{ combinationRef: string; primaryServiceRef: string; name: string; isDefault: boolean; version: number; complementaryRefs: readonly string[] }>[] }>;
export type ServiceMode = Readonly<{ modeRef: string; code: string; name: string; description: string | null; state: "DRAFT" | "PUBLISHED" | "INACTIVE"; version: number }>;
export type ServiceRequirement = Readonly<{ requirementRef: string; kind: "PERSONNEL" | "MATERIAL" | "ASSET" | "VEHICLE" | "TRANSPORT" | "DURATION" | "CRATING"; code: string; name: string; quantity: number | null; unitCode: string | null; hours: number | null; days: number | null; phaseCode: string | null; materialRef: string | null; assetModelRef: string | null; capabilityRef: string | null; disposition: string | null; chargeType: string | null; configuration: RecordValue; position: number }>;
export type ServicePackage = Readonly<{ packageRef: string; versionRef: string; code: string; name: string; description: string | null; category: string | null; tags: readonly string[]; state: "DRAFT" | "PUBLISHED" | "INACTIVE"; version: number; validFrom: string | null; validTo: string | null; modes: readonly Readonly<{ modeRef: string; code: string; name: string }>[]; primary: Readonly<{ serviceRef: string; code: string; name: string }> | null; complementaries: readonly Readonly<{ serviceRef: string; code: string; name: string }>[]; requirements: readonly ServiceRequirement[] }>;
export type ServiceMaterialPolicy = Readonly<{ policyRef: string; versionRef: string; code: string; name: string; version: number; state: "DRAFT" | "PUBLISHED" | "INACTIVE"; packageVersionRef: string | null; serviceRef: string | null; modeRef: string | null; preferenceCode: string | null; standardCode: string; validFrom: string | null; validTo: string | null; lines: readonly Readonly<{ lineRef: string; materialRef: string | null; assetModelRef: string | null; materialClass: string; disposition: string; proportion: number | null; chargeType: string }>[] }>;
export type CaseServiceConfigurationWorkspace = Readonly<{ caseRef: string; mode: string; current: null | Readonly<{ configurationRef: string; revision: number; packageRef: string | null; packageVersion: number | null; materialPolicyRef: string | null; materialPolicyVersion: number | null; source: string; items: readonly Readonly<{ itemRef: string; kind: string; source: string; code: string; name: string; quantity: number | null; unitCode: string | null; hours: number | null; days: number | null; disposition: string | null; chargeType: string | null; proportion: number | null }>[]; conflicts: readonly Readonly<{ conflictRef: string; kind: string; state: string }>[] }>; packages: readonly ServicePackage[]; materialPolicies: readonly ServiceMaterialPolicy[]; precedence: readonly string[] }>;

export class CrmServicesApiError extends Error { readonly status: number; readonly code: string; constructor(status: number, code: string) { super(code); this.name = "CrmServicesApiError"; this.status = status; this.code = code; } }
function record(value: unknown): RecordValue { if (!value || typeof value !== "object" || Array.isArray(value)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return value as RecordValue; }
function exact(value: RecordValue, keys: readonly string[]) { if (JSON.stringify(Object.keys(value).sort()) !== JSON.stringify([...keys].sort())) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); }
function text(value: unknown, uuid = false) { if (typeof value !== "string" || !value || value.length > 320 || (uuid && !UUID_V4.test(value))) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return value; }
function integer(value: unknown) { if (!Number.isSafeInteger(value) || Number(value) < 0) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Number(value); }
function nullableString(value: unknown) { return value === null ? null : text(value); }
function nullableNumber(value: unknown) { if (value === null) return null; if (typeof value !== "number" || !Number.isFinite(value)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return value; }
function publicRecord(value: unknown, keys: readonly string[]): RecordValue { const row = record(value); exact(row, keys); return row; }
function mode(value: unknown): ServiceMode { const row = publicRecord(value, ["modeRef", "code", "name", "description", "state", "version"]); return Object.freeze({ modeRef: text(row.modeRef, true), code: text(row.code), name: text(row.name), description: nullableString(row.description), state: text(row.state) as ServiceMode["state"], version: integer(row.version) }); }
function requirement(value: unknown): ServiceRequirement { const row = publicRecord(value, ["requirementRef", "kind", "code", "name", "quantity", "unitCode", "hours", "days", "phaseCode", "materialRef", "assetModelRef", "capabilityRef", "disposition", "chargeType", "configuration", "position"]); record(row.configuration); return Object.freeze({ requirementRef: text(row.requirementRef, true), kind: text(row.kind) as ServiceRequirement["kind"], code: text(row.code), name: text(row.name), quantity: nullableNumber(row.quantity), unitCode: nullableString(row.unitCode), hours: nullableNumber(row.hours), days: nullableNumber(row.days), phaseCode: nullableString(row.phaseCode), materialRef: row.materialRef === null ? null : text(row.materialRef, true), assetModelRef: row.assetModelRef === null ? null : text(row.assetModelRef, true), capabilityRef: row.capabilityRef === null ? null : text(row.capabilityRef, true), disposition: nullableString(row.disposition), chargeType: nullableString(row.chargeType), configuration: row.configuration as RecordValue, position: integer(row.position) }); }
function servicePackage(value: unknown): ServicePackage { const row = publicRecord(value, ["packageRef", "versionRef", "code", "name", "description", "category", "tags", "state", "version", "validFrom", "validTo", "modes", "primary", "complementaries", "requirements"]); if (!Array.isArray(row.tags) || !Array.isArray(row.modes) || !Array.isArray(row.complementaries) || !Array.isArray(row.requirements)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); const item = (entry: unknown) => { const current = publicRecord(entry, ["serviceRef", "code", "name"]); return Object.freeze({ serviceRef: text(current.serviceRef, true), code: text(current.code), name: text(current.name) }); }; return Object.freeze({ packageRef: text(row.packageRef, true), versionRef: text(row.versionRef, true), code: text(row.code), name: text(row.name), description: nullableString(row.description), category: nullableString(row.category), tags: Object.freeze(row.tags.map((entry) => text(entry))), state: text(row.state) as ServicePackage["state"], version: integer(row.version), validFrom: nullableString(row.validFrom), validTo: nullableString(row.validTo), modes: Object.freeze(row.modes.map((entry) => { const current = publicRecord(entry, ["modeRef", "code", "name"]); return Object.freeze({ modeRef: text(current.modeRef, true), code: text(current.code), name: text(current.name) }); })), primary: row.primary === null ? null : item(row.primary), complementaries: Object.freeze(row.complementaries.map(item)), requirements: Object.freeze(row.requirements.map(requirement)) }); }
function materialPolicy(value: unknown): ServiceMaterialPolicy { const row = publicRecord(value, ["policyRef", "versionRef", "code", "name", "version", "state", "packageVersionRef", "serviceRef", "modeRef", "preferenceCode", "standardCode", "validFrom", "validTo", "lines"]); if (!Array.isArray(row.lines)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Object.freeze({ policyRef: text(row.policyRef, true), versionRef: text(row.versionRef, true), code: text(row.code), name: text(row.name), version: integer(row.version), state: text(row.state) as ServiceMaterialPolicy["state"], packageVersionRef: row.packageVersionRef === null ? null : text(row.packageVersionRef, true), serviceRef: row.serviceRef === null ? null : text(row.serviceRef, true), modeRef: row.modeRef === null ? null : text(row.modeRef, true), preferenceCode: nullableString(row.preferenceCode), standardCode: text(row.standardCode), validFrom: nullableString(row.validFrom), validTo: nullableString(row.validTo), lines: Object.freeze(row.lines.map((entry) => { const current = publicRecord(entry, ["lineRef", "materialRef", "assetModelRef", "materialClass", "disposition", "proportion", "chargeType", "preparationRule", "maintenanceRule", "deteriorationRule", "replacementRule", "conditions"]); for (const key of ["preparationRule", "maintenanceRule", "deteriorationRule", "replacementRule", "conditions"]) record(current[key]); return Object.freeze({ lineRef: text(current.lineRef, true), materialRef: current.materialRef === null ? null : text(current.materialRef, true), assetModelRef: current.assetModelRef === null ? null : text(current.assetModelRef, true), materialClass: text(current.materialClass), disposition: text(current.disposition), proportion: nullableNumber(current.proportion), chargeType: text(current.chargeType) }); })) }); }
function catalog(value: unknown): ServiceCatalogItem { const row = record(value); exact(row, ["serviceRef", "code", "name", "category", "usage", "compatibleModes", "status", "sortOrder", "version", "usageCount", "allowedComplementaryRefs"]); if (!Array.isArray(row.compatibleModes) || !Array.isArray(row.allowedComplementaryRefs)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Object.freeze({ serviceRef: text(row.serviceRef, true), code: text(row.code), name: text(row.name), category: row.category === null ? null : text(row.category), usage: row.usage as ServiceCatalogItem["usage"], compatibleModes: Object.freeze(row.compatibleModes.map((mode) => text(mode) as "LOCAL" | "EXPORT" | "IMPORT")), status: row.status as ServiceCatalogItem["status"], sortOrder: integer(row.sortOrder), version: integer(row.version), usageCount: integer(row.usageCount), allowedComplementaryRefs: Object.freeze(row.allowedComplementaryRefs.map((ref) => text(ref, true))) }); }
function canonical(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; const row = value as RecordValue; return `{${Object.keys(row).sort().map((key) => `${JSON.stringify(key)}:${canonical(row[key])}`).join(",")}}`; }
async function hash(value: unknown) { const bytes = new TextEncoder().encode(canonical(value)); return [...new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))].map((item) => item.toString(16).padStart(2, "0")).join(""); }
function selectionItem(value: unknown) { const row = record(value); exact(row, ["serviceRef", "code", "name", "category", "catalogVersion", "source"]); return Object.freeze({ serviceRef: text(row.serviceRef, true), code: text(row.code), name: text(row.name), category: row.category === null ? null : text(row.category), catalogVersion: integer(row.catalogVersion), source: text(row.source) }); }
function selection(value: unknown): CaseServiceSelection {
  const row = record(value); exact(row, ["selectionRef", "revision", "mode", "source", "defaultCombinationRef", "primary", "complementaries", "otherServices", "historyCount"]);
  if (!Array.isArray(row.complementaries) || !Array.isArray(row.otherServices)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID");
  const otherServices = row.otherServices.map((value) => { const item = record(value); exact(item, ["description", "classificationStatus"]); if (item.classificationStatus !== "PENDING") throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Object.freeze({ description: text(item.description), classificationStatus: "PENDING" as const }); });
  return Object.freeze({ selectionRef: row.selectionRef === null ? null : text(row.selectionRef, true), revision: integer(row.revision), mode: row.mode === null ? null : text(row.mode) as CaseServiceSelection["mode"], source: row.source === null ? null : text(row.source) as CaseServiceSelection["source"], defaultCombinationRef: row.defaultCombinationRef === null ? null : text(row.defaultCombinationRef, true), primary: row.primary === null ? null : selectionItem(row.primary), complementaries: Object.freeze(row.complementaries.map(selectionItem)), otherServices: Object.freeze(otherServices), historyCount: integer(row.historyCount) });
}
function workspace(value: unknown): CaseServiceWorkspace {
  const row = record(value); exact(row, ["caseRef", "mode", "selection", "primaries", "allowedComplementaries", "defaults"]);
  if (!Array.isArray(row.primaries) || !Array.isArray(row.allowedComplementaries) || !Array.isArray(row.defaults)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID");
  return Object.freeze({ caseRef: text(row.caseRef, true), mode: text(row.mode) as CaseServiceWorkspace["mode"], selection: selection(row.selection), primaries: Object.freeze(row.primaries.map(catalog)), allowedComplementaries: Object.freeze(row.allowedComplementaries.map((value) => { const item = record(value); exact(item, ["primaryServiceRef", "service"]); return Object.freeze({ primaryServiceRef: text(item.primaryServiceRef, true), service: catalog(item.service) }); })), defaults: Object.freeze(row.defaults.map((value) => { const item = record(value); exact(item, ["combinationRef", "primaryServiceRef", "name", "isDefault", "version", "complementaryRefs"]); if (!Array.isArray(item.complementaryRefs) || typeof item.isDefault !== "boolean") throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Object.freeze({ combinationRef: text(item.combinationRef, true), primaryServiceRef: text(item.primaryServiceRef, true), name: text(item.name), isDefault: item.isDefault, version: integer(item.version), complementaryRefs: Object.freeze(item.complementaryRefs.map((ref) => text(ref, true))) }); })) });
}

function caseConfiguration(value: unknown): CaseServiceConfigurationWorkspace {
  const row = publicRecord(value, ["caseRef", "mode", "current", "packages", "materialPolicies", "precedence"]);
  if (!Array.isArray(row.packages) || !Array.isArray(row.materialPolicies) || !Array.isArray(row.precedence)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID");
  let current: CaseServiceConfigurationWorkspace["current"] = null;
  if (row.current !== null) {
    const item = publicRecord(row.current, ["configurationRef", "revision", "mode", "serviceSelectionRef", "serviceSelectionRevision", "packageRef", "packageVersion", "materialPolicyRef", "materialPolicyVersion", "surveyPublicationRef", "commercialAgreementRef", "preference", "duration", "precedence", "source", "createdAt", "items", "conflicts"]);
    if (!Array.isArray(item.items) || !Array.isArray(item.conflicts)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID");
    record(item.preference); record(item.duration); record(item.precedence);
    current = Object.freeze({ configurationRef: text(item.configurationRef, true), revision: integer(item.revision), packageRef: item.packageRef === null ? null : text(item.packageRef, true), packageVersion: item.packageVersion === null ? null : integer(item.packageVersion), materialPolicyRef: item.materialPolicyRef === null ? null : text(item.materialPolicyRef, true), materialPolicyVersion: item.materialPolicyVersion === null ? null : integer(item.materialPolicyVersion), source: text(item.source), items: Object.freeze(item.items.map((entry) => { const currentItem = publicRecord(entry, ["itemRef", "kind", "source", "authorityRef", "code", "name", "quantity", "unitCode", "hours", "days", "disposition", "chargeType", "proportion", "details"]); if (currentItem.authorityRef !== null) text(currentItem.authorityRef, true); record(currentItem.details); return Object.freeze({ itemRef: text(currentItem.itemRef, true), kind: text(currentItem.kind), source: text(currentItem.source), code: text(currentItem.code), name: text(currentItem.name), quantity: nullableNumber(currentItem.quantity), unitCode: nullableString(currentItem.unitCode), hours: nullableNumber(currentItem.hours), days: nullableNumber(currentItem.days), disposition: nullableString(currentItem.disposition), chargeType: nullableString(currentItem.chargeType), proportion: nullableNumber(currentItem.proportion) }); })), conflicts: Object.freeze(item.conflicts.map((entry) => { const conflict = publicRecord(entry, ["conflictRef", "kind", "state"]); return Object.freeze({ conflictRef: text(conflict.conflictRef, true), kind: text(conflict.kind), state: text(conflict.state) }); })) });
  }
  return Object.freeze({ caseRef: text(row.caseRef, true), mode: text(row.mode), current, packages: Object.freeze(row.packages.map(servicePackage)), materialPolicies: Object.freeze(row.materialPolicies.map(materialPolicy)), precedence: Object.freeze(row.precedence.map((entry) => text(entry))) });
}

export class CrmServicesApi {
  private readonly tokenProvider: () => string | null;
  constructor(tokenProvider: () => string | null) { this.tokenProvider = tokenProvider; }
  private async request(path: string, init: RequestInit = {}) {
    const token = this.tokenProvider(); const membershipRef = getMembershipRef();
    if (!token || !membershipRef) throw new CrmServicesApiError(401, "COMMERCIAL_AUTH_REQUIRED");
    const response = await fetch(`/api/crm/services${path}`, { ...init, credentials: "omit", cache: "no-store", headers: { Authorization: `Bearer ${token}`, "X-OSI-Membership-Ref": membershipRef, ...(init.body ? { "Content-Type": "application/json" } : {}) } });
    const body = record(await response.json());
    if (!response.ok) throw new CrmServicesApiError(response.status, typeof body.error === "string" ? body.error : "CRM_SERVICES_UNAVAILABLE");
    exact(body, ["ok", "data"]); if (body.ok !== true) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID");
    return body.data;
  }
  async workspace(caseRef: string, signal?: AbortSignal): Promise<CaseServiceWorkspace> {
    if (!UUID_V4.test(caseRef)) throw new CrmServicesApiError(404, "CRM_SERVICES_RESOURCE_NOT_FOUND");
    return workspace(await this.request(`/cases/${encodeURIComponent(caseRef)}`, { signal }));
  }
  async saveSelection(caseRef: string, unsigned: Omit<RecordValue, "payloadHash">) {
    const payload = { operation: "CASE_SELECTION_SAVE", ...unsigned }; const body = { ...unsigned, payloadHash: await hash(payload) };
    return this.request(`/cases/${encodeURIComponent(caseRef)}`, { method: "PATCH", body: JSON.stringify(body) });
  }
  async catalog(signal?: AbortSignal): Promise<readonly ServiceCatalogItem[]> { const value = await this.request("/catalog", { signal }); if (!Array.isArray(value)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Object.freeze(value.map(catalog)); }
  async createCatalog(unsigned: Omit<RecordValue, "payloadHash">) { const payload = { operation: "CATALOG_CREATE", ...unsigned }; return this.request("/catalog", { method: "POST", body: JSON.stringify({ ...unsigned, payloadHash: await hash(payload) }) }); }
  async updateCatalog(serviceRef: string, unsigned: Omit<RecordValue, "payloadHash">) { const payload = { operation: "CATALOG_UPDATE", ...unsigned }; return this.request(`/catalog/${encodeURIComponent(serviceRef)}`, { method: "PATCH", body: JSON.stringify({ ...unsigned, payloadHash: await hash(payload) }) }); }
  async history(serviceRef: string) { return this.request(`/catalog/${encodeURIComponent(serviceRef)}`) as Promise<Readonly<{ serviceRef: string; events: readonly Readonly<{ action: string; version: number; createdAt: string }>[] }>>; }
  async defaults(primaryServiceRef: string) { return this.request(`/defaults?primaryRef=${encodeURIComponent(primaryServiceRef)}`) as Promise<readonly Readonly<{ combinationRef: string; code: string; name: string; status: "ACTIVE" | "INACTIVE"; isDefault: boolean; version: number; complementaries: readonly ServiceCatalogItem[] }>[]>; }
  async saveDefaults(unsigned: Omit<RecordValue, "payloadHash">) { const payload = { operation: "DEFAULTS_SAVE", ...unsigned }; return this.request("/defaults", { method: "POST", body: JSON.stringify({ ...unsigned, payloadHash: await hash(payload) }) }); }
  async modes(signal?: AbortSignal): Promise<readonly ServiceMode[]> { const value = await this.request("/modes", { signal }); if (!Array.isArray(value)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Object.freeze(value.map(mode)); }
  async saveMode(unsigned: Omit<RecordValue, "payloadHash">) { const payload = { operation: "MODE_SAVE", ...unsigned }; return this.request("/modes", { method: "POST", body: JSON.stringify({ ...unsigned, payloadHash: await hash(payload) }) }); }
  async catalogModes(signal?: AbortSignal): Promise<readonly Readonly<{ serviceRef: string; modeRefs: readonly string[] }>[]> { const value = await this.request("/catalog-modes", { signal }); if (!Array.isArray(value)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Object.freeze(value.map((entry) => { const row = publicRecord(entry, ["serviceRef", "modeRefs"]); if (!Array.isArray(row.modeRefs)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Object.freeze({ serviceRef: text(row.serviceRef, true), modeRefs: Object.freeze(row.modeRefs.map((item) => text(item, true))) }); })); }
  async saveCatalogModes(unsigned: Omit<RecordValue, "payloadHash">) { const payload = { operation: "CATALOG_MODES_SAVE", ...unsigned }; return this.request("/catalog-modes", { method: "POST", body: JSON.stringify({ ...unsigned, payloadHash: await hash(payload) }) }); }
  async packages(signal?: AbortSignal): Promise<readonly ServicePackage[]> { const value = await this.request("/packages", { signal }); if (!Array.isArray(value)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Object.freeze(value.map(servicePackage)); }
  async savePackage(unsigned: Omit<RecordValue, "payloadHash">) { const payload = { operation: "PACKAGE_SAVE", ...unsigned }; return this.request("/packages", { method: "POST", body: JSON.stringify({ ...unsigned, payloadHash: await hash(payload) }) }); }
  async materialPolicies(signal?: AbortSignal): Promise<readonly ServiceMaterialPolicy[]> { const value = await this.request("/material-policies", { signal }); if (!Array.isArray(value)) throw new CrmServicesApiError(502, "CRM_SERVICES_RESPONSE_INVALID"); return Object.freeze(value.map(materialPolicy)); }
  async saveMaterialPolicy(unsigned: Omit<RecordValue, "payloadHash">) { const payload = { operation: "MATERIAL_POLICY_SAVE", ...unsigned }; return this.request("/material-policies", { method: "POST", body: JSON.stringify({ ...unsigned, payloadHash: await hash(payload) }) }); }
  async caseConfiguration(caseRef: string, signal?: AbortSignal): Promise<CaseServiceConfigurationWorkspace> { if (!UUID_V4.test(caseRef)) throw new CrmServicesApiError(404, "SERVICE_PACKAGES_RESOURCE_NOT_FOUND"); return caseConfiguration(await this.request(`/configurations/${encodeURIComponent(caseRef)}`, { signal })); }
  async saveCaseConfiguration(caseRef: string, unsigned: Omit<RecordValue, "payloadHash">) { const payload = { operation: "CASE_CONFIGURATION_SAVE", ...unsigned }; return this.request(`/configurations/${encodeURIComponent(caseRef)}`, { method: "POST", body: JSON.stringify({ ...unsigned, payloadHash: await hash(payload) }) }); }
}
