import { useCallback, useEffect, useMemo, useState } from "react";
import { History, Layers3, Plus, Power, Settings2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { CrmServicesApi, CrmServicesApiError, type ServiceCatalogItem } from "./api";

type Props = Readonly<{ authorization?: string; canManage: boolean; onUnauthorized(): void }>;
type Draft = Readonly<{ serviceRef?: string; expectedVersion?: number; code: string; name: string; category: string; usage: "PRIMARY" | "COMPLEMENTARY" | "BOTH"; compatibleModes: readonly string[]; status: "ACTIVE" | "INACTIVE"; sortOrder: number; allowedComplementaryRefs: readonly string[] }>;
const EMPTY: Draft = Object.freeze({ code: "", name: "", category: "", usage: "PRIMARY", compatibleModes: ["LOCAL"], status: "ACTIVE", sortOrder: 0, allowedComplementaryRefs: [] });

export default function ServiceCatalogAdmin({ authorization, canManage, onUnauthorized }: Props) {
  const api = useMemo(() => new CrmServicesApi(() => authorization || null), [authorization]);
  const [rows, setRows] = useState<readonly ServiceCatalogItem[]>([]);
  const [draft, setDraft] = useState<Draft | null>(null);
  const [history, setHistory] = useState<Readonly<{ name: string; events: readonly Readonly<{ action: string; version: number; createdAt: string }>[] }> | null>(null);
  const [defaultsFor, setDefaultsFor] = useState<ServiceCatalogItem | null>(null);
  const [defaultRefs, setDefaultRefs] = useState<readonly string[]>([]);
  const [defaultRecord, setDefaultRecord] = useState<Readonly<{ combinationRef: string; code: string; name: string; version: number }> | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => { const controller = new AbortController(); setLoading(true); void api.catalog(controller.signal).then(setRows).catch((cause) => { if (cause instanceof CrmServicesApiError && cause.status === 401) onUnauthorized(); else setError("No fue posible cargar el catálogo."); }).finally(() => setLoading(false)); return () => controller.abort(); }, [api, onUnauthorized]);
  useEffect(load, [load]);
  const complementary = rows.filter((item) => item.status === "ACTIVE" && ["COMPLEMENTARY", "BOTH"].includes(item.usage));
  const edit = (item: ServiceCatalogItem) => {
    setDraft({ serviceRef: item.serviceRef, expectedVersion: item.version, code: item.code, name: item.name, category: item.category || "", usage: item.usage, compatibleModes: item.compatibleModes, status: item.status, sortOrder: item.sortOrder, allowedComplementaryRefs: item.allowedComplementaryRefs });
  };
  const save = async () => {
    if (!draft) return; setSaving(true); setError(null);
    try {
      const shared = { requestId: crypto.randomUUID(), name: draft.name.trim(), category: draft.category.trim() || null, usage: draft.usage, compatibleModes: [...draft.compatibleModes].sort(), sortOrder: draft.sortOrder, allowedComplementaryRefs: draft.allowedComplementaryRefs };
      if (draft.serviceRef) await api.updateCatalog(draft.serviceRef, { ...shared, expectedVersion: draft.expectedVersion, status: draft.status });
      else await api.createCatalog({ ...shared, code: draft.code.trim().toUpperCase() });
      setDraft(null); load();
    } catch (cause) { setError(cause instanceof CrmServicesApiError && cause.code === "CRM_SERVICES_VERSION_CONFLICT" ? "El servicio cambió; recargue antes de guardar." : "No fue posible guardar el servicio."); } finally { setSaving(false); }
  };
  const toggleStatus = async (item: ServiceCatalogItem) => {
    setSaving(true); setError(null); try { await api.updateCatalog(item.serviceRef, { requestId: crypto.randomUUID(), expectedVersion: item.version, name: item.name, category: item.category, usage: item.usage, compatibleModes: [...item.compatibleModes].sort(), status: item.status === "ACTIVE" ? "INACTIVE" : "ACTIVE", sortOrder: item.sortOrder, allowedComplementaryRefs: item.allowedComplementaryRefs }); load(); } catch { setError("No fue posible cambiar el estado sin afectar la configuración vigente."); } finally { setSaving(false); }
  };
  const openDefaults = async (item: ServiceCatalogItem) => { setDefaultsFor(item); setError(null); try { const values = await api.defaults(item.serviceRef); const current = values.find((value) => value.isDefault && value.status === "ACTIVE") || null; setDefaultRecord(current ? { combinationRef: current.combinationRef, code: current.code, name: current.name, version: current.version } : null); setDefaultRefs(current?.complementaries.map((entry) => entry.serviceRef) || []); } catch { setError("No fue posible cargar las combinaciones."); } };
  const saveDefault = async () => { if (!defaultsFor) return; setSaving(true); try { await api.saveDefaults({ requestId: crypto.randomUUID(), primaryServiceRef: defaultsFor.serviceRef, combinationRef: defaultRecord?.combinationRef || null, code: defaultRecord?.code || `${defaultsFor.code}_DEFAULT`, name: defaultRecord?.name || `Predeterminado ${defaultsFor.name}`, isDefault: true, status: "ACTIVE", expectedVersion: defaultRecord?.version || null, complementaryRefs: defaultRefs }); setDefaultsFor(null); } catch { setError("No fue posible guardar la combinación predeterminada."); } finally { setSaving(false); } };
  return <section data-testid="service-catalog-admin" className="mt-5">
    <div className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-200 pb-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-indigo-600">Administración / Servicios</p><h2 className="text-xl font-black text-slate-950">Catálogo tenant-first</h2><p className="text-xs text-slate-500">Código | Servicio | Tipo | Modos | Estado | Usos | Acciones</p></div>{canManage && <Button onClick={() => setDraft(EMPTY)}><Plus />Nuevo servicio</Button>}</div>
    {error && <p role="alert" className="mt-3 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <div className="mt-3 overflow-x-auto border bg-white"><div className="grid min-w-[850px] grid-cols-[120px_minmax(180px,1fr)_120px_150px_90px_60px_260px] border-b bg-slate-50 px-3 py-2 text-[10px] font-bold uppercase text-slate-500"><span>Código</span><span>Servicio</span><span>Tipo</span><span>Modos</span><span>Estado</span><span>Usos</span><span>Acciones</span></div>{loading ? <p className="p-6 text-center text-sm text-slate-500">Cargando…</p> : rows.map((item) => <div key={item.serviceRef} className="grid min-w-[850px] grid-cols-[120px_minmax(180px,1fr)_120px_150px_90px_60px_260px] items-center border-b px-3 py-2 text-xs"><code className="font-bold text-[#003366]">{item.code}</code><span className="truncate font-semibold">{item.name}</span><span>{item.usage}</span><span>{item.compatibleModes.join(", ") || "—"}</span><span>{item.status}</span><span>{item.usageCount}</span><span className="flex gap-1"><Button size="sm" variant="ghost" disabled={!canManage} onClick={() => edit(item)}><Settings2 />Editar</Button>{["PRIMARY", "BOTH"].includes(item.usage) && <Button size="sm" variant="ghost" disabled={!canManage} onClick={() => void openDefaults(item)}><Layers3 />Combo</Button>}<Button size="sm" variant="ghost" onClick={() => void api.history(item.serviceRef).then((value) => setHistory({ name: item.name, events: value.events }))}><History />Historial</Button><Button aria-label={`${item.status === "ACTIVE" ? "Desactivar" : "Activar"} ${item.name}`} size="icon" variant="ghost" disabled={!canManage || saving} onClick={() => void toggleStatus(item)}><Power /></Button></span></div>)}</div>
    <Dialog open={Boolean(draft)} onOpenChange={(open) => { if (!open) setDraft(null); }}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{draft?.serviceRef ? "Editar servicio" : "Crear servicio"}</DialogTitle><DialogDescription>La referencia y el código son estables. Los nombres no son autoridad.</DialogDescription></DialogHeader>{draft && <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Código<input disabled={Boolean(draft.serviceRef)} value={draft.code} onChange={(event) => setDraft({ ...draft, code: event.target.value })} className="mt-1 h-10 w-full rounded border px-3" /></label><label className="text-xs font-bold">Servicio<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} className="mt-1 h-10 w-full rounded border px-3" /></label><label className="text-xs font-bold">Categoría<input value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })} className="mt-1 h-10 w-full rounded border px-3" /></label><label className="text-xs font-bold">Tipo<select value={draft.usage} onChange={(event) => setDraft({ ...draft, usage: event.target.value as Draft["usage"] })} className="mt-1 h-10 w-full rounded border px-3"><option>PRIMARY</option><option>COMPLEMENTARY</option><option>BOTH</option></select></label><fieldset className="sm:col-span-2"><legend className="text-xs font-bold">Modos compatibles</legend><div className="mt-1 flex gap-4">{["LOCAL", "EXPORT", "IMPORT"].map((mode) => <label key={mode} className="text-sm"><input type="checkbox" checked={draft.compatibleModes.includes(mode)} onChange={() => setDraft({ ...draft, compatibleModes: draft.compatibleModes.includes(mode) ? draft.compatibleModes.filter((value) => value !== mode) : [...draft.compatibleModes, mode] })} /> {mode}</label>)}</div></fieldset>{["PRIMARY", "BOTH"].includes(draft.usage) && <fieldset className="sm:col-span-2"><legend className="text-xs font-bold">Complementarios permitidos</legend><div className="mt-1 grid gap-1 border p-2 sm:grid-cols-2">{complementary.filter((item) => item.serviceRef !== draft.serviceRef).map((item) => <label key={item.serviceRef} className="text-sm"><input type="checkbox" checked={draft.allowedComplementaryRefs.includes(item.serviceRef)} onChange={() => setDraft({ ...draft, allowedComplementaryRefs: draft.allowedComplementaryRefs.includes(item.serviceRef) ? draft.allowedComplementaryRefs.filter((ref) => ref !== item.serviceRef) : [...draft.allowedComplementaryRefs, item.serviceRef] })} /> {item.name}</label>)}</div></fieldset>}<Button className="sm:col-span-2" disabled={saving || !draft.code || !draft.name} onClick={() => void save()}>{saving ? "Guardando…" : "Guardar"}</Button></div>}</DialogContent></Dialog>
    <Dialog open={Boolean(defaultsFor)} onOpenChange={(open) => { if (!open) setDefaultsFor(null); }}><DialogContent><DialogHeader><DialogTitle>Combinación predeterminada</DialogTitle><DialogDescription>Se copiará al caso; los cambios posteriores no reescriben su historia.</DialogDescription></DialogHeader><div className="divide-y border">{complementary.filter((item) => defaultsFor?.allowedComplementaryRefs.includes(item.serviceRef)).map((item) => <label key={item.serviceRef} className="flex items-center gap-2 p-2 text-sm"><input type="checkbox" checked={defaultRefs.includes(item.serviceRef)} onChange={() => setDefaultRefs((current) => current.includes(item.serviceRef) ? current.filter((ref) => ref !== item.serviceRef) : [...current, item.serviceRef])} />{item.name}</label>)}</div><Button disabled={saving} onClick={() => void saveDefault()}>Guardar combinación</Button></DialogContent></Dialog>
    <Dialog open={Boolean(history)} onOpenChange={(open) => { if (!open) setHistory(null); }}><DialogContent><DialogHeader><DialogTitle>Historial · {history?.name}</DialogTitle><DialogDescription>Eventos auditados; no expone identidades internas.</DialogDescription></DialogHeader><div className="divide-y border">{history?.events.map((event, index) => <div key={`${event.createdAt}-${index}`} className="flex justify-between gap-3 p-2 text-xs"><span>{event.action}</span><span>v{event.version} · {new Intl.DateTimeFormat("es-DO").format(new Date(event.createdAt))}</span></div>)}</div></DialogContent></Dialog>
  </section>;
}
