import { useState, type ComponentType } from "react";
import {
  ArrowLeft, BarChart3, BriefcaseBusiness, Check, ChevronDown, ClipboardCheck, Edit3, FileText, History,
  LayoutGrid, ListChecks, MessageSquare, PackageCheck, Paperclip, Plus, Settings2,
  Power, Save, Star, StickyNote, Tags, Trash2, Users, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";

type CaseTab = "SUMMARY" | "SERVICES" | "SURVEY" | "ACTIVITY" | "TASKS" | "QUOTE" | "NOTES" | "FILES" | "COMMUNICATION";
type CatalogView = "PRIMARY" | "COMPLEMENTARY" | "COMBO";

const TABS: ReadonlyArray<readonly [CaseTab, string, ComponentType<{ className?: string }>]> = [
  ["SUMMARY", "Resumen", FileText], ["SERVICES", "Servicios", BriefcaseBusiness],
  ["SURVEY", "Survey", ClipboardCheck], ["ACTIVITY", "Actividad", History],
  ["TASKS", "Tareas", ListChecks], ["QUOTE", "Cotización", BriefcaseBusiness],
  ["NOTES", "Notas", StickyNote], ["FILES", "Archivos", Paperclip],
  ["COMMUNICATION", "Comunicación", MessageSquare],
];

const PRIMARY_SERVICES = [
  ["MOV_RES", "Mudanza residencial", "Mudanzas"], ["MOV_CORP", "Mudanza corporativa y de oficinas", "Mudanzas"],
  ["MOV_DIP", "Mudanza diplomática", "Mudanzas"], ["STORAGE_FURN", "Almacenaje de mobiliario", "Almacenaje"],
  ["STORAGE_LOG", "Almacenaje logístico", "Almacenaje"], ["RECORD_STORAGE", "Record storage", "Archivo"],
  ["TRANSPORT", "Transporte y distribución", "Logística"], ["CUSTOMS", "Gestión aduanal", "Aduanas"],
  ["PACK_INDUSTRIAL", "Embalaje industrial", "Embalaje"], ["PACK_TECH", "Embalaje tecnológico", "Embalaje"],
  ["FINE_ART", "Manejo y embalaje de obras de arte", "Especializados"], ["CRATING", "Crating o fabricación de guacales", "Especializados"],
] as const;

const COMPLEMENTARY_SERVICES = [
  ["PACK_UNPACK", "Embalaje y desembalaje", "Preparación"], ["ASSEMBLY", "Desarme y armado", "Preparación"],
  ["MATERIALS", "Materiales y cajas", "Preparación"], ["LOAD_UNLOAD", "Carga y descarga", "Logística y transporte"],
  ["LOCAL_TRANSPORT", "Transporte local", "Logística y transporte"], ["LAST_MILE", "Distribución o última milla", "Logística y transporte"],
  ["PORT_AIR", "Manejo portuario o aeroportuario", "Logística y transporte"], ["TEMP_STORAGE", "Almacenaje temporal", "Almacenaje"],
  ["LONG_STORAGE", "Almacenaje prolongado", "Almacenaje"], ["CRATING", "Crating o guacales", "Especializados"],
  ["CUSTOMS", "Gestión aduanal", "Especializados"], ["RIGGING", "Elevación o rigging", "Especializados"],
  ["SPECIAL_PROTECTION", "Protección especializada", "Especializados"],
] as const;

const SERVICE_COMBOS = [
  { code: "MOV_RES_STD", name: "Residencial estándar", primary: "MOV_RES", items: ["PACK_UNPACK", "ASSEMBLY", "MATERIALS", "LOCAL_TRANSPORT"], isDefault: true },
  { code: "MOV_RES_INT", name: "Residencial internacional", primary: "MOV_RES", items: ["PACK_UNPACK", "CRATING", "CUSTOMS", "PORT_AIR", "TEMP_STORAGE", "SPECIAL_PROTECTION"] },
  { code: "MOV_CORP_FULL", name: "Oficina completa", primary: "MOV_CORP", items: ["PACK_UNPACK", "ASSEMBLY", "LOAD_UNLOAD", "LOCAL_TRANSPORT", "LAST_MILE", "MATERIALS"], isDefault: true },
  { code: "FINE_ART_CARE", name: "Arte con protección integral", primary: "FINE_ART", items: ["CRATING", "RIGGING", "SPECIAL_PROTECTION", "PORT_AIR"], isDefault: true },
] as const;

const fieldClass = "mt-1 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm text-slate-900 outline-none focus:border-[#0b5b91] focus:ring-2 focus:ring-sky-100";
const labelClass = "text-[11px] font-bold uppercase tracking-[.06em] text-slate-500";

function ComplementaryMultiSelect({ selected, onChange }: Readonly<{ selected: string[]; onChange(next: string[]): void }>) {
  const [open, setOpen] = useState(false);
  const groups = [...new Set(COMPLEMENTARY_SERVICES.map(([, , group]) => group))];
  const allSelected = selected.length === COMPLEMENTARY_SERVICES.length;
  const toggle = (code: string) => onChange(selected.includes(code) ? selected.filter((item) => item !== code) : [...selected, code]);
  return <div className="relative">
    <button type="button" aria-label="Servicios complementarios" aria-expanded={open} onClick={() => setOpen((value) => !value)} className="flex h-8 items-center gap-2 rounded-md border border-slate-300 bg-white px-3 text-xs font-bold text-[#003366] outline-none focus:border-[#0b5b91] focus:ring-2 focus:ring-sky-100"><Plus className="h-3.5 w-3.5" /><span>Elegir</span><ChevronDown className={`h-3.5 w-3.5 transition ${open ? "rotate-180" : ""}`} /></button>
    {open && <div className="absolute right-0 z-30 mt-1 w-[min(620px,calc(100vw-2rem))] rounded-xl border border-slate-200 bg-white p-3 shadow-xl">
      <div className="mb-3 flex items-center justify-between border-b border-slate-100 pb-2"><label className="flex cursor-pointer items-center gap-2 text-xs font-black text-[#003366]"><input type="checkbox" checked={allSelected} onChange={() => onChange(allSelected ? [] : COMPLEMENTARY_SERVICES.map(([code]) => code))} className="h-4 w-4 accent-[#0b5b91]" />Seleccionar todos</label><button type="button" className="rounded p-1 text-slate-500 hover:bg-slate-100" aria-label="Cerrar selector" onClick={() => setOpen(false)}><X className="h-4 w-4" /></button></div>
      <div className="grid gap-x-5 gap-y-3 sm:grid-cols-2">{groups.map((group) => { const items = COMPLEMENTARY_SERVICES.filter(([, , itemGroup]) => itemGroup === group); const groupSelected = items.every(([code]) => selected.includes(code)); return <fieldset key={group} className="min-w-0"><legend className="mb-1 flex w-full items-center justify-between text-[10px] font-black uppercase tracking-[.08em] text-slate-500"><span>{group}</span><button type="button" className="normal-case tracking-normal text-[#0b5b91]" onClick={() => onChange(groupSelected ? selected.filter((code) => !items.some(([itemCode]) => itemCode === code)) : [...new Set([...selected, ...items.map(([code]) => code)])])}>{groupSelected ? "Quitar grupo" : "Todo el grupo"}</button></legend><div className="space-y-0.5">{items.map(([code, name]) => <label key={code} className="flex cursor-pointer items-center gap-2 rounded px-1.5 py-1.5 text-xs text-slate-700 hover:bg-slate-50"><input type="checkbox" checked={selected.includes(code)} onChange={() => toggle(code)} className="h-4 w-4 shrink-0 accent-[#0b5b91]" />{name}</label>)}</div></fieldset>; })}</div>
      <div className="mt-3 flex justify-end border-t border-slate-100 pt-2"><Button type="button" size="sm" onClick={() => setOpen(false)}>Aplicar {selected.length ? `(${selected.length})` : ""}</Button></div>
    </div>}
  </div>;
}

function CatalogDialog({ open, onClose }: Readonly<{ open: boolean; onClose(): void }>) {
  const [view, setView] = useState<CatalogView>("PRIMARY");
  const [adding, setAdding] = useState(false);
  const [disabledCodes, setDisabledCodes] = useState<string[]>([]);
  const [editingCode, setEditingCode] = useState("");
  const [defaultComboCodes, setDefaultComboCodes] = useState<Record<string, string>>({ MOV_RES: "MOV_RES_STD", MOV_CORP: "MOV_CORP_FULL", FINE_ART: "FINE_ART_CARE" });
  if (!open) return null;
  const rows: Array<readonly [string, string, string]> = view === "PRIMARY"
    ? PRIMARY_SERVICES.map(([code, name, category]) => [code, name, category])
    : view === "COMPLEMENTARY"
      ? COMPLEMENTARY_SERVICES.map(([code, name, group]) => [code, name, group])
      : SERVICE_COMBOS.map(({ code, name, primary }) => [code, name, PRIMARY_SERVICES.find(([itemCode]) => itemCode === primary)?.[1] || primary]);
  const activeKey = (code: string) => `${view}-${code}`;
  const toggleStatus = (code: string) => setDisabledCodes((current) => current.includes(activeKey(code)) ? current.filter((item) => item !== activeKey(code)) : [...current, activeKey(code)]);
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-3" data-testid="services-admin-catalog">
    <section role="dialog" aria-modal="true" aria-labelledby="catalog-title" className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-2xl">
      <header className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 px-5 py-4"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#0070a8]">Administración · Comercial y CRM</p><h2 id="catalog-title" className="mt-1 text-xl font-black text-[#003366]">Catálogo de servicios</h2><p className="mt-1 text-sm text-slate-500">Configuración tenant-first para selección, estadísticas y análisis.</p></div><button type="button" aria-label="Cerrar catálogo" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" onClick={onClose}><X className="h-4 w-4" /></button></header>
      <div className="grid gap-3 border-b border-slate-200 bg-slate-50 p-4 sm:grid-cols-4"><div className="rounded-lg border bg-white p-3"><span className="text-xs text-slate-500">Principales activos</span><strong className="mt-1 block text-xl text-[#003366]">12</strong></div><div className="rounded-lg border bg-white p-3"><span className="text-xs text-slate-500">Complementarios activos</span><strong className="mt-1 block text-xl text-[#003366]">13</strong></div><div className="rounded-lg border bg-white p-3"><span className="text-xs text-slate-500">Combos activos</span><strong className="mt-1 block text-xl text-[#003366]">4</strong></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-3"><span className="text-xs text-amber-800">Otros por clasificar</span><strong className="mt-1 block text-xl text-amber-900">1</strong></div></div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-4 py-3"><div role="tablist" aria-label="Tipo de catálogo" className="flex flex-wrap rounded-lg bg-slate-100 p-1">{([['PRIMARY','Servicios principales'],['COMPLEMENTARY','Complementarios'],['COMBO','Combos']] as const).map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={view === value} className={`rounded-md px-3 py-2 text-xs font-bold ${view === value ? "bg-white text-[#003366] shadow" : "text-slate-500"}`} onClick={() => { setView(value); setEditingCode(""); }}>{label}</button>)}</div><Button type="button" size="sm" onClick={() => setAdding((value) => !value)}><Plus />{view === "COMBO" ? "Nuevo combo" : "Nuevo tipo de servicio"}</Button></div>
      {adding && <div className="grid gap-3 border-b border-sky-200 bg-sky-50 p-4 sm:grid-cols-4"><label className={`${labelClass} sm:col-span-2`}>Nombre<input className={fieldClass} placeholder="Nombre administrable" /></label><label className={labelClass}>Categoría<input className={fieldClass} placeholder="Categoría KPI" /></label><label className={labelClass}>Uso<select className={fieldClass}><option>Principal</option><option>Complementario</option><option>Ambos</option></select></label><div className="flex justify-end gap-2 sm:col-span-4"><Button type="button" size="sm" variant="outline" onClick={() => setAdding(false)}>Cancelar</Button><Button type="button" size="sm" onClick={() => setAdding(false)}>Agregar al catálogo</Button></div></div>}
      <div className="divide-y divide-slate-100">{rows.map(([code, name, category]) => { const disabled = disabledCodes.includes(activeKey(code)); const comboRow = SERVICE_COMBOS.find((item) => item.code === code); const isDefault = view === "COMBO" && !!comboRow && defaultComboCodes[comboRow.primary] === code; return <div key={`${view}-${code}`} className="px-4 py-3"><div className="grid items-center gap-2 text-sm sm:grid-cols-[125px_1fr_170px_75px_140px]"><code className="text-xs font-bold text-slate-500">{code}</code><strong className={disabled ? "text-slate-400 line-through" : "text-slate-800"}>{name}{isDefault && <span className="ml-2 inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-[9px] uppercase text-amber-900"><Star className="h-3 w-3 fill-current" />Predeterminado</span>}</strong><span className="text-xs text-slate-500">{category}</span><span className={`w-fit rounded-full px-2 py-1 text-[10px] font-bold uppercase ${disabled ? "bg-slate-200 text-slate-600" : "bg-emerald-100 text-emerald-800"}`}>{disabled ? "Inactivo" : "Activo"}</span><div className="flex justify-end gap-1">{view === "COMBO" && comboRow && <button type="button" title="Establecer como predeterminado" aria-label={`Establecer ${name} como predeterminado`} disabled={isDefault || disabled} onClick={() => setDefaultComboCodes((current) => ({ ...current, [comboRow.primary]: code }))} className="grid h-8 w-8 place-items-center rounded-md border border-amber-200 text-amber-700 hover:bg-amber-50 disabled:opacity-40"><Star className={`h-3.5 w-3.5 ${isDefault ? "fill-current" : ""}`} /></button>}<button type="button" title="Editar" aria-label={`Editar ${name}`} onClick={() => setEditingCode(editingCode === code ? "" : code)} className="grid h-8 w-8 place-items-center rounded-md border border-slate-200 text-slate-600 hover:bg-slate-50"><Edit3 className="h-3.5 w-3.5" /></button><button type="button" title={disabled ? "Activar" : "Desactivar"} aria-label={`${disabled ? "Activar" : "Desactivar"} ${name}`} onClick={() => toggleStatus(code)} className={`grid h-8 w-8 place-items-center rounded-md border ${disabled ? "border-emerald-200 text-emerald-700" : "border-rose-200 text-rose-700"}`}><Power className="h-3.5 w-3.5" /></button></div></div>{editingCode === code && <div className="mt-3 grid gap-2 rounded-lg border border-sky-200 bg-sky-50 p-3 sm:grid-cols-[1fr_220px_auto]"><label className={labelClass}>Nombre visible<input aria-label={`Nombre visible de ${name}`} className={fieldClass} defaultValue={name} /></label><label className={labelClass}>{view === "COMBO" ? "Servicio principal" : "Grupo para análisis"}<input className={fieldClass} defaultValue={category} /></label><div className="flex items-end"><Button type="button" size="sm" onClick={() => setEditingCode("")}><Save />Guardar cambio</Button></div></div>}</div>; })}</div>
      <footer className="border-t border-slate-200 bg-slate-50 px-4 py-3 text-xs text-slate-600">Los servicios usados históricamente se desactivan; nunca se eliminan ni cambian el significado de casos anteriores.</footer>
    </section>
  </div>;
}

function ServicesPanel({ onOpenCatalog }: Readonly<{ onOpenCatalog(): void }>) {
  const [primary, setPrimary] = useState("");
  const [scope, setScope] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const [combo, setCombo] = useState("");
  const [comboName, setComboName] = useState("");
  const [savingCombo, setSavingCombo] = useState(false);
  const [comboSaved, setComboSaved] = useState(false);
  const [customDefaults, setCustomDefaults] = useState<Record<string, { name: string; items: string[] }>>({});
  const [otherDescription, setOtherDescription] = useState("");
  const [saved, setSaved] = useState(false);
  const valid = primary.length > 0 && scope.length > 0 && (primary !== "OTHER" || otherDescription.trim().length >= 3);
  const availableCombos = SERVICE_COMBOS.filter((item) => item.primary === primary);
  const changeSelected = (next: string[]) => { setSelected(next); setSaved(false); setComboSaved(false); };
  const applyCombo = (code: string) => { setCombo(code); if (code === `CUSTOM-${primary}` && customDefaults[primary]) changeSelected([...customDefaults[primary].items]); else { const found = SERVICE_COMBOS.find((item) => item.code === code); if (found) changeSelected([...found.items]); } };
  const selectPrimary = (code: string) => {
    setPrimary(code); setSaved(false); setComboSaved(false);
    const custom = customDefaults[code];
    const defaultCombo = SERVICE_COMBOS.find((item) => item.primary === code && "isDefault" in item && item.isDefault);
    if (custom) { setCombo(`CUSTOM-${code}`); setSelected([...custom.items]); }
    else if (defaultCombo) { setCombo(defaultCombo.code); setSelected([...defaultCombo.items]); }
    else { setCombo(""); setSelected([]); }
  };
  return <section role="tabpanel" aria-labelledby="services-heading" className="rounded-xl border border-slate-200 bg-white shadow-sm" data-testid="services-case-panel">
    <header className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 bg-slate-50 px-4 py-3"><div><div className="flex flex-wrap items-center gap-2"><h2 id="services-heading" className="font-black text-[#003366]">Servicios del caso</h2><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${saved ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-900"}`}>{saved ? "Definido" : "Pendiente"}</span></div><p className="mt-1 text-xs text-slate-500">Definición comercial posterior al ICP y anterior a Survey.</p></div><Button type="button" size="sm" variant="outline" onClick={onOpenCatalog}><Settings2 />Configurar catálogo</Button></header>
    <div className="grid gap-4 p-4 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><label className={labelClass}>Servicio principal *<select aria-label="Servicio principal" className={fieldClass} value={primary} onChange={(event) => selectPrimary(event.target.value)}><option value="">Seleccionar del catálogo</option>{PRIMARY_SERVICES.map(([code, name]) => <option key={code} value={code}>{name}</option>)}<option value="OTHER">Otro servicio no catalogado</option></select></label><label className={labelClass}>Alcance *<select aria-label="Alcance" className={fieldClass} value={scope} onChange={(event) => { setScope(event.target.value); setSaved(false); }}><option value="">Confirmar alcance</option><option>Local</option><option>Nacional</option><option>Exportación</option><option>Importación</option><option>Sin traslado</option><option>No aplica</option></select></label><label className={labelClass}>Combo asignado<select aria-label="Combo de complementarios" className={fieldClass} value={combo} disabled={!availableCombos.length && !customDefaults[primary]} onChange={(event) => applyCombo(event.target.value)}><option value="">{primary && !availableCombos.length && !customDefaults[primary] ? "Sin combo configurado" : "Elegir otra combinación"}</option>{customDefaults[primary] && <option value={`CUSTOM-${primary}`}>{customDefaults[primary].name} · Predeterminado</option>}{availableCombos.map((item) => <option key={item.code} value={item.code}>{item.name}{"isDefault" in item && item.isDefault && !customDefaults[primary] ? " · Predeterminado" : ""}</option>)}</select></label></div>{primary === "OTHER" && <label className={labelClass}>Descripción de otro servicio *<textarea aria-label="Descripción de otro servicio" className="mt-1 min-h-20 w-full rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm font-normal normal-case tracking-normal outline-none focus:ring-2 focus:ring-amber-100" value={otherDescription} onChange={(event) => { setOtherDescription(event.target.value); setSaved(false); }} placeholder="Describe el servicio solicitado para que Administración pueda clasificarlo" /><span className="mt-1 block text-xs font-normal normal-case tracking-normal text-amber-800">Quedará identificado como «Otro pendiente de clasificación».</span></label>}
        <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 pb-2"><div className="flex items-center gap-2"><h3 className={labelClass}>Servicios complementarios</h3><span className="text-xs font-black text-[#003366]">· {selected.length}</span>{combo && <span title="Se precargó el combo asignado al servicio principal" className="inline-flex items-center gap-1 text-[10px] font-semibold text-amber-700"><Star className="h-3 w-3 fill-current" />Precargados</span>}</div><div className="flex gap-2"><ComplementaryMultiSelect selected={selected} onChange={changeSelected} /><button type="button" title="Guardar selección como combo predeterminado" aria-label="Guardar como combo" disabled={!primary || !selected.length} onClick={() => { setSavingCombo(true); setComboSaved(false); }} className="grid h-8 w-8 place-items-center rounded-md border border-slate-300 text-[#003366] hover:bg-slate-50 disabled:opacity-40"><Save className="h-3.5 w-3.5" /></button></div></div>
        {savingCombo && <div className="flex flex-wrap items-end gap-2 rounded-lg border border-sky-200 bg-sky-50 p-3"><label className={`${labelClass} min-w-[240px] flex-1`}>Nombre del nuevo combo<input aria-label="Nombre del nuevo combo" className={fieldClass} value={comboName} onChange={(event) => setComboName(event.target.value)} placeholder="Ej.: Mudanza residencial completa" /></label><Button type="button" size="sm" variant="outline" onClick={() => setSavingCombo(false)}>Cancelar</Button><Button type="button" size="sm" disabled={comboName.trim().length < 3} onClick={() => { setCustomDefaults((current) => ({ ...current, [primary]: { name: comboName.trim(), items: [...selected] } })); setCombo(`CUSTOM-${primary}`); setSavingCombo(false); setComboSaved(true); }}><Star />Guardar como predeterminado</Button></div>}
        {comboSaved && <p role="status" className="flex items-center gap-2 border-y border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-800"><Check className="h-4 w-4" />Combo «{comboName}» asignado como predeterminado. Se precargará al volver a seleccionar este servicio principal.</p>}
        {selected.length ? <div className="overflow-hidden border-y border-slate-200" data-testid="selected-complementaries-list"><div className="grid grid-cols-[minmax(0,1fr)_90px_32px] bg-slate-100 px-2 py-1.5 text-[10px] font-black uppercase tracking-[.06em] text-slate-500 sm:grid-cols-[1fr_170px_40px] sm:px-3"><span>Servicio complementario</span><span>Grupo</span><span></span></div>{selected.map((code, index) => { const item = COMPLEMENTARY_SERVICES.find(([itemCode]) => itemCode === code); return item ? <div key={code} className={`grid grid-cols-[minmax(0,1fr)_90px_32px] items-center px-2 py-2 text-xs sm:grid-cols-[1fr_170px_40px] sm:px-3 ${index % 2 ? "bg-slate-50" : "bg-white"}`}><strong className="min-w-0 pr-2 text-slate-700">{item[1]}</strong><span className="min-w-0 text-[10px] text-slate-500 sm:text-xs">{item[2]}</span><button type="button" title="Quitar" aria-label={`Quitar ${item[1]}`} onClick={() => changeSelected(selected.filter((value) => value !== code))} className="grid h-7 w-7 place-items-center text-rose-600 hover:bg-rose-50"><Trash2 className="h-3.5 w-3.5" /></button></div> : null; })}</div> : <p className="py-3 text-xs text-slate-500">Sin servicios complementarios seleccionados.</p>}
      </div>
      <aside className="space-y-3"><div className="rounded-lg border border-indigo-200 bg-indigo-50 p-3"><BarChart3 className="h-5 w-5 text-indigo-700" /><h3 className="mt-2 text-sm font-black text-indigo-950">Preparado para análisis</h3><p className="mt-1 text-xs leading-5 text-indigo-800">Principal, alcance y complementarios se registran por códigos estables para estadísticas, KPI y rendimiento.</p></div><div className="rounded-lg border border-slate-200 p-3"><Tags className="h-5 w-5 text-[#0b5b91]" /><h3 className="mt-2 text-sm font-black text-[#003366]">Selección actual</h3><dl className="mt-2 space-y-2 text-xs"><div className="flex justify-between gap-2"><dt className="text-slate-500">Principal</dt><dd className="text-right font-semibold">{PRIMARY_SERVICES.find(([code]) => code === primary)?.[1] || (primary === "OTHER" ? "Otro" : "Pendiente")}</dd></div><div className="flex justify-between gap-2"><dt className="text-slate-500">Alcance</dt><dd className="font-semibold">{scope || "Pendiente"}</dd></div><div className="flex justify-between gap-2"><dt className="text-slate-500">Complementarios</dt><dd className="font-semibold">{selected.length}</dd></div></dl></div></aside></div>
    <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 bg-slate-50 px-4 py-3"><p className="text-xs text-slate-500">Guardar creará una revisión de la definición; no sobrescribe silenciosamente el historial.</p><Button type="button" disabled={!valid} onClick={() => setSaved(true)}><PackageCheck />{saved ? "Servicios guardados" : "Guardar definición"}</Button></footer>
  </section>;
}

function Placeholder({ tab }: Readonly<{ tab: CaseTab }>) {
  const label = TABS.find(([value]) => value === tab)?.[1] || tab;
  return <section role="tabpanel" className="rounded-xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><h2 className="font-black text-[#003366]">{label}</h2><p className="mt-2 text-sm text-slate-500">Área independiente de la Ficha del Caso. No se presentan datos simulados.</p></section>;
}

export default function ServicesVisualPreview() {
  const [tab, setTab] = useState<CaseTab>("SERVICES");
  const [catalogOpen, setCatalogOpen] = useState(false);
  return <div className="flex min-h-screen bg-[#f4f7fb]" data-testid="crm-services-visual-preview"><aside className="hidden w-64 shrink-0 bg-[#003b70] text-white lg:flex lg:flex-col"><div className="flex h-16 items-center gap-3 border-b border-white/15 px-5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white font-black text-[#003b70]">OS</span><div><strong className="block">OSi Plus ERP</strong><small className="uppercase tracking-[.15em] text-blue-200">Gestión integrada</small></div></div><nav className="space-y-1 p-3"><div className="mb-3 flex items-center gap-3 rounded-lg border border-white/15 px-3 py-2 text-blue-100"><LayoutGrid className="h-4 w-4 text-amber-300" />OSi Plus Hub</div><p className="px-3 py-2 text-[10px] font-bold uppercase tracking-[.15em] text-blue-300">Aplicaciones ERP</p><div className="flex items-center gap-3 rounded-lg px-3 py-2 text-blue-200"><LayoutGrid className="h-4 w-4" />General</div><div className="flex items-center gap-3 rounded-lg px-3 py-2 text-blue-200"><Settings2 className="h-4 w-4" />Administración</div><div className="rounded-lg bg-sky-500 px-3 py-2 font-bold"><span className="flex items-center gap-3"><BriefcaseBusiness className="h-4 w-4" />Comercial</span><div className="ml-7 mt-3 border-l border-sky-200/40 pl-3 text-xs"><strong>Pipeline</strong><p className="mt-3 text-sky-100">Clientes · En integración</p><p className="mt-3 text-sky-100">Seguimiento · En integración</p></div></div><div className="flex items-center gap-3 rounded-lg px-3 py-2 text-blue-200"><Users className="h-4 w-4" />Coordinación</div></nav><div className="mt-auto border-t border-white/15 p-4"><strong className="block text-sm">FREDERICK ESPINAL</strong><span className="text-xs text-blue-200">ROL A · Preview visual</span></div></aside>
    <main className="min-w-0 flex-1"><header className="border-b border-slate-200 bg-white px-4 py-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[11px] font-black uppercase tracking-[.2em] text-[#0070a8]">Ficha del caso</p><h1 className="mt-2 text-2xl font-black text-[#003366]">Cliente de ejemplo</h1><p className="mt-1 text-sm text-slate-500"><span className="font-mono font-bold text-[#003366]">ICP-001</span> · Caso recién creado · Servicio pendiente · Sin responsable</p><div className="mt-3 flex gap-2"><span className="rounded bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-800">Caso sin asignar</span><span className="rounded bg-sky-50 px-2 py-1 text-[10px] font-bold text-sky-800">Definir servicios</span></div></div><Button type="button" variant="outline"><ArrowLeft />Volver al Inbox</Button></div></header>
      <div role="tablist" aria-label="Áreas de la Ficha del Caso" className="flex gap-1 overflow-x-auto border-b border-slate-300 bg-stone-200 p-1">{TABS.map(([value, label, Icon]) => <button key={value} type="button" role="tab" aria-selected={tab === value} onClick={() => setTab(value)} className={`flex shrink-0 items-center gap-1.5 rounded px-3 py-2 text-xs font-bold ${tab === value ? "bg-[#df8750] text-white shadow-sm" : "text-slate-700 hover:bg-white/70"}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</div>
      <div className="p-3 sm:p-4">{tab === "SERVICES" ? <ServicesPanel onOpenCatalog={() => setCatalogOpen(true)} /> : <Placeholder tab={tab} />}</div>
    </main><CatalogDialog open={catalogOpen} onClose={() => setCatalogOpen(false)} />
  </div>;
}
